scrapers/ct/__init__.py
scrapers/ct/bills.py

CT: FTP listing isn't working, switch metadata to use HTTP, add 2021

---

scrapers/ne/__init__.py

Waiting on data, do not merge yet.

NE: 2021 session

---

scrapers/ri/__init__.py

Waiting for data, do not merge yet

RI: 2021 session

---

scrapers/ma/__init__.py
scrapers/ma/bills.py

MA seems to have changed their site layout, we'll adapt the scrapers once they post some actions.

MA: Add 2021, disable actions for now.

---

scrapers/ma/__init__.py

Waiting on state to file bills, do not merge yet.

MA: 2021 session

---

scrapers/mi/__init__.py

once bills are present will address openstates/issues#215 and openstates/issues#161

MI: 2021 session metadata

---

scrapers/nc/__init__.py

will fix openstates/issues#217 once there are bills
openstates/issues#161

NC: 2021 session metadata

---

scrapers/il/bills.py

We were adding some amendments as documents instead of versions in IL, this resolves that.

IL: Amendments should be versions

---

scrapers/sd/bills.py

Now that SD is posting actions, enable the scrape
https://github.com/openstates/issues/issues/238

SD: Enable action scrape

---

scrapers/ar/bills.py

Enabled scraping of bill webpages for other primary sponsors and cosponsors.

AR: scrape sponsors

---

scrapers/va/__init__.py
scrapers/va/events.py

VA: Scrape events

---

scrapers/va/events.py

On some servers I was seeing an error "UnknownTimezoneWarning: tzname EST identified but not understood.", so this fixes it.

VA events: fix for timezone issues

---

scrapers/ar/__init__.py
scrapers/ar/events.py

AR: New events scraper

---

scrapers/dc/__init__.py
scrapers/dc/events.py

DC: Fix events scraper

---

scrapers/az/__init__.py
scrapers/az/events.py

AZ: Events scraper

---

scrapers/ar/bills.py

Added document scraping for bills. Tried to assign appropriate classifications based on this issue: https://github.com/openstates/issues/issues/15

AR: add document scraping for bills

---

scrapers/ga/__init__.py
scrapers/ga/events.py

GA: Add event scraper

---

scrapers/id/__init__.py
scrapers/id/events.py

ID: Events scraper

---

scrapers/nm/__init__.py
scrapers/nm/events.py

NM: Add Event Scraper

---

scrapers/ok/__init__.py
scrapers/ok/events.py

OK: event scraper

---

scrapers/ut/events.py

UT: Fix Event Scraper

---

scrapers/wy/__init__.py

https://github.com/openstates/issues/issues/257

WY: fix session regex due to site change

---

scrapers/wy/__init__.py
scrapers/wy/events.py

WY: Scrape events

---

scrapers/ia/bills.py

IA Prefiles, openstates/issues#252

---

scrapers/ar/bills.py

Added scraping for amendments on bills and removed leftover print statements.

AR: add scraping of amendments

---

scrapers/mt/__init__.py
scrapers/mt/events.py

MT: Scrape Events

---

scrapers/md/events.py

MD: New Events scraper for 2021

---

scrapers/mn/__init__.py
scrapers/mn/events.py

MN: Events scraper

---

scrapers/ms/__init__.py
scrapers/ms/events.py

MS Event Scrapers

---

scrapers/sd/bills.py

Fixes https://github.com/openstates/issues/issues/258

SD: Protect against unexpected data amendment data structure

---

scrapers/ma/bills.py

https://github.com/openstates/issues/issues/262

MA: adjust supplement regex to be case insensitive

---

scrapers/mo/events.py
scrapers/ri/events.py

A few fresh special cases for events scrapers.

Events scraper parsing fixes

---

scrapers/wv/__init__.py
scrapers/wv/events.py

WV: events scraper

---

scrapers/nc/__init__.py
scrapers/nc/events.py

NC: Scrape events

---

scrapers/in/__init__.py
scrapers/in/events.py

IN: Scrape events

---

.pre-commit-config.yaml
scrapers/wv/__init__.py
scrapers/wv/bills.py

WV: 2021 WIP

---

scrapers/va/__init__.py
scrapers/va/csv_bills.py

Don't merge this yet, just for discussion on the best way to handle this.

VA: hack to pull in continuation special data

---

scrapers/wi/__init__.py
scrapers/wi/common.py

Despite the name, it started this week.

WI: Add 2021 January Special Session

---

scrapers/va/csv_bills.py

Attempts to fix https://github.com/openstates/issues/issues/328
However I don't have the Virginia FTP credentials - could somebody else test or DM me credentials?

VA: fix source URLs in weird 2021 special+regular session

---

scrapers/ar/people.py

Added the scraping of voting aliases for people to fix this issue:
https://github.com/openstates/issues/issues/254

AR: scrape vote name

---

scrapers/hi/bills.py

Addresses https://github.com/openstates/issues/issues/357 by restoring the HR scrape, and using current report URLs that the HI webmaster pointed me to.

HI: use current bill reports and restore HR scrape

---

scrapers/me/bills.py

ME lists committee actions in a random spot on the house page, so grab them.

ME: scrape committee actions

---

scrapers/mi/bills.py

https://github.com/openstates/issues/issues/363

MI: parse both short and long years in action dates

---

scrapers/nv/bills.py

https://github.com/openstates/issues/issues/360

WIP: NV: Scrape carryover bills, replace identifer

---

.deepsource.toml
scrapers/ca/bills.py
scrapers/la/events.py
scrapers/ma/bills.py
scrapers/nd/votes.py
scrapers/ri/bills.py
scrapers/wa/bills.py
scrapers/wi/bills.py

**Description**
Summary:
- Fixed implicit string concatenation
- Fixed iterating dictionary
- Use negative index to get last element
- Add .deepsource.toml
I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/openstates-scrapers/).
DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.
If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. …

Fixed Code Quality Issues

---

scrapers/ar/people.py

Fixes https://github.com/openstates/issues/issues/366

Adds state to Arkansas Legislators' addresses

---

scrapers/ak/bills.py
scrapers/co/actions.py
scrapers/hi/bills.py
scrapers/id/bills.py
scrapers/in/bills.py
scrapers/ky/bills.py
scrapers/la/bills.py
scrapers/md/bills.py
scrapers/mo/bills.py
scrapers/ms/bills.py
scrapers/mt/actions.py
scrapers/nv/bills.py
scrapers/ok/actions.py
scrapers/sd/bills.py
scrapers/tx/bills.py
scrapers/vt/bills.py

Misc updates to bill actions, mostly catching became-law and veto that were missed last session.

Bill action classification updates

---

scrapers/ak/bills.py

AK posted some sponsors that weren't matching our regex, so update it.

AK: sponsor fixes

---

scrapers/nm/__init__.py
scrapers/nm/bills.py

Don't merge until bills are posted.

NM: Add 2021 first special

---

scrapers/oh/bills.py

Fixes https://github.com/openstates/issues/issues/379

OH: Create exception for HR 35 which is missing a title at source

---

scrapers/ar/bills.py

Allows scraping of veto related actions and vote events.

AR: add veto for action and vote classification

---

scrapers/tx/bills.py

Addresses [openstates/issues/#375](https://github.com/openstates/issues/issues/375)

TX: Bills: Clean up action classifier

---

scrapers/az/bills.py

https://github.com/openstates/issues/issues/405

AZ: fix for actions with true as a date

---

scrapers/or/bills.py

https://github.com/openstates/issues/issues/409

OR: remove deprecated action class

---

scrapers/ca/bills.py
scrapers/ca/models.py

Unfortunately, like California PDFs, the link to the bill analyses doesn't actually grab the bill analyses, so this URL is mostly as a data store. I'm using it in a fork of the project to actually download the CA bill PDFs and analyses PDFs, but I'm not sure where to put that code within the openstates ecosystem.

CA: Adding Bill Analyses to 

---

scrapers/nv/bills.py

Fixes https://github.com/openstates/issues/issues/428 by catching selector error. The actions table can just be totally missing for at least one bill: https://www.leg.state.nv.us/App/NELIS/REL/81st2021/Bill/FillSelectedBillTab?selectedTab=Overview&billKey=7574&_=1621628330.988863

NV: fix exception thrown when bill actions table is totally missing

---

scrapers/tx/bills.py

We were only grabbing the first version in the TX XML, process them all.

TX: Grab all versions after the first

---

scrapers/vt/events.py
scrapers/wy/events.py

Date and duplicate document fixes for WY, VT

WY, VT Events scraper fixes

---

scrapers/fl/__init__.py

2022 session is now listed, but contains zero bills

FL: ignore 2022 session (it is in the future)

---

scrapers/mo/__init__.py

Do not merge until data is posted to test.

MO: add first special

---

scrapers_next/ca/people.py

Converted old CA people scraper to spatula framework. SenList and AssemblyList are their own classes. Note that emails are not public/available. Also note that CA has a vacant assembly seat. @jamesturk

Ca spatula scrape

---

scrapers_next/wa/people.py

fixed error of using regex in lstrip. This error did not change anything in the output but good to make it correct anyway. @jamesturk

fixed error of using regex in lstrip

---

scrapers/ct/bills.py

See https://www.cga.ct.gov/asp/cgabillstatus/cgabillstatus.asp?selBillType=Bill&bill_num=SB1059&which_year=2021

CT: classify veto

---

scrapers/tx/__init__.py
scrapers/tx/bills.py

TX: add 2021 First Special

---

scrapers_next/tx/committees.py

- note/potential issue: accented characters don't show up correctly in the data
- other than that, i tried my best to hardcode the fields as little as possible!

TX committees scraper

---

scrapers_next/mn/committees.py

- will have to update if more parties are represented outside of DFL and R!

more specific delimiter for names

---

scrapers_next/ga/committees.py

changed link note to 'homepage'

---

scrapers_next/mn/committees.py

i added a quick check and warning to make sure that each Senate committee had a homepage :) also wasn't sure if I should add the list of committees as a source too, but did for the time being! Can easily remove it as well if we'd prefer not to have it!

added homepage links to MN committees

---

scrapers_next/ia/people.py
scrapers_next/tx/committees.py

- I decided to make another data model just so I could pass in a url to add as a source in LegDetail, so if there's a more straightforward way, I'll do that!
- as i was copying code from TX comm.py, I noticed a spelling mistake so changed that, and changed the num_of_fields to a range that is more reliable (length of the actual number of fields, instead of hard-coding the number)

Iowa people scraper conversion to spatula

---

scrapers_next/nj/people.py

- the individual legislator pages are kind of unpredictable, so when adding offices, I tried to exhaust every single possibility
- I didn't include much more extra information because of the unpredictability

NJ People Scraper spatula conversion

---

scrapers/ar/__init__.py

Don't merge until they drop some bills.

AR: Add 2021 First Special

---

scrapers_next/de/people.py

Converting DE people scraper to use spatula framework. A few things to note:
1. the image src is not actually showing up as an image (looks like bytes?). Not sure how to grab the actual images.
2. Not sure if I should add detail_link as the 'homepage' link. For example, the source is https://legis.delaware.gov/LegislatorDetail?personId=3058 but the url shows up as https://legis.delaware.gov/AssemblyMember/151/BriggsKing.
3. There is no district office information listed.
@jamesturk

De people spatula

---

scrapers/ar/events.py
scrapers/dc/bills.py
scrapers/or/bills.py

DC: classify a new wording for became law
OR: Update for new website source URL scheme
AR: Events: Fix 'call of the chair' breaking time parser.
h/u @jessemortenson @jamesturk this will invalidate the cache on all Oregon bills.

Misc Small Scraper Updates

---

scrapers/tx/__init__.py

Currently doesn't have bills, will create ticket to add session when bills are posted this weekend.

TX: Ignore 2nd special

---

scrapers_next/dc/people.py

Writing dc people scraper to use spatula framework.
Notes:
1. Councilmember Kenyan R. McDuffie is listed twice. I skip him the first time.
2. Is there a way to use placeholders when I first assign p = ScrapePerson()? Right now I either use empty strings, or "Democratic" for the party (and later overwrite). See line 86.
3. I assign p.district as either 'chariman' (all lower), 'At-Large', or 'Ward \d'. Should I change any of this?
4. No district office info available.
5. What would I assign chamber for these people?
6. I am assigning the detail pages as 'homepage.' Some people also have websites, which I am adding to p.extras. ex: https://dccouncil.us/council/councilmember-robert-c-white-jr/ vs http://www.RobertWhiteAtLarge.com/
@jamesturk

Dc people spatula

---

scrapers/usa/bills.py

- add dates to versions
- US: add scrape_public_law_version method
- US: skip public law check if not enrolled

us public law

---

scrapers/nj/committees.py

I stole code from `bills.py` to get `committees.py` working again. I tested it for the 2020-2021 session only, so far.
I ran into a new committee member role code (or "position on committee" code). "C" mean chair, "V" is vice-chair, "" is member, and now there's "O", which I assume means member of a commission. See, for example, one commission where all members have role code "O": [SELECT COMMISSION ON EMERGENCY COVID-19 BORROWING (SCEB)](https://www.njleg.state.nj.us/committees/sceb.asp); they're only called "members" on this page.
For now, I assign members with role code "O" to role "member", same as for code "". **Should members with role code "O" get a different role name instead?**

NJ: Get committee scraper working again

---

poetry.lock
pyproject.toml
scrapers_next/ky/people.py

Converting KY people scraper to use spatula framework. Notes:
1. Need to add verify=False to both URLs once spatula is updated.
2. skipping vacant seats
3. There are 3 different types of addresses listed (Mailing Address, Legislative Address, Capitol Address). I am currently adding Mailing Address to extras. I am assigning Legislative Address as p.district_office.address. I am assigning Capitol Address as p.capitol_office.address. ex: https://legislature.ky.gov/Legislators/Pages/Legislator-Profile.aspx?DistrictNumber=119
4. There are 3 different types of phones/fax listed (Home, Work, LRC). I am currently adding Work to extras. I am assigning Home as p.district_office.address. I am assigning LRC as p.capitol_office.address. ex: https://legislature.ky.gov/Legislators/Pages/Legislator-Profil …

Ky people spatula

---

scrapers/ak/bills.py

https://github.com/openstates/issues/issues/472

Fix for joint ak bills

---

poetry.lock
scrapers_next/ri/committees.py

Writing RI committee scraper using spatula framework. Notes:
1. Needed to create a separate SubCommitteeDetail() class for 3 subcommittee pages. Needed to use dictionaries to connect subcommittee names to respective members (html was not structured well).
http://webserver.rilegislature.gov/HouseFinance/HFinanceSCom.html
http://webserver.rilegislature.gov/HouseOversight/HOversightSCom.html
http://webserver.rilegislature.gov/SFinance/SFinanceSCom.html
2. Most committees have clerk names, phones, and emails listed. Phone numbers are all missing area codes.
@jamesturk

Ri committe scrape

---

scrapers_next/la/people.py

Writing LA people scraper using the spatula framework.
Note: there is no capitol office information listed (just district offices).
@jamesturk

La people spatula

---

scrapers_next/wa/committees.py

Writing WA committee scraper using spatula framework. Not able to connect to sources at the moment.
@jamesturk

Wa committee spatula

---

scrapers_next/tn/people.py

Writing TN people scraper using spatula framework. A lot of personal information being store in p.extras
@jamesturk

Tn people spatula

---

scrapers_next/sc/people.py

Writing SC people scraper using spatula framework. Notes:
1. Emails are not available for any legislators.
2. Currently assigning 'Home Address' to p.district_office.address. Could alternatively assign to p.additional_offices.
3. The code to grab phone numbers could be simplified if we don't care about their labels. For example, a legislator can have 1-4 phones listed. Currently avoiding/checking for duplicates.
ex: https://www.scstatehouse.gov/member.php?code=1640908894
- Columbia Address Business Phone assigning to p.capitol_office.voice
- Columbia Address Home/Cell Phone assigning to p.extras
- Home Address Home Phone assigning to p.extras
- Home Address Business Phone assigning to p.district_office.voice
@jamesturk

Sc people spatula

---

scrapers_next/pa/people.py

Writing PA people scraper using spatula framework. Notes:
1. No email addresses available for anyone.
2. Many/most people have multiple district offices listed. I stored all in additional_offices w/ contact_type='District Office' rather than district_office.address. Could put the 1st in district_office.address if that's preferred and the rest in additional_offices.
@jamesturk

Pa people spatula

---

scrapers/tx/__init__.py

Includes 3rd special session, dates based on [this article](https://www.texastribune.org/2021/09/07/texas-special-session-redistricting/)

TX: add 3rd special

---

scrapers_next/wv/people.py

Writing WV people scraper using spatula framework. Notes:
1. Skipping vacant Senate seat (district 16).
2. Not everyone has a district office / district phone available, but grabbing those who do.
@jamesturk

Wv people spatula

---

scrapers/az/bills.py

https://github.com/openstates/issues/issues/492

AZ: Fix for new date format in one action

---

scrapers/az/bills.py

Should help fix [492](https://github.com/openstates/issues/issues/492)

AZ: add headers to request

---

scrapers_next/al/committees.py

Writing AL committee scraper using spatula library. Notes:
1. There are Joint Committees at this link: http://www.legislature.state.al.us/aliswww/ISD/House/JointInterimCommittees.aspx. However, the detail links for each of these committees are hidden by javascript:__doPostBack('ctl00$ContentPlaceHolder1$gvJICommittees','cmdCommittee$0'). At the moment, just returning com object without scraping these members.
@jamesturk

Al committee spatula

---

scrapers/ok/__init__.py

Special session starts on November 15, set up a reminder to add it to scraped session when we get closer and to check for prefiles

OK: ignore special session for now

---

scrapers/fl/__init__.py
scrapers/fl/bills.py

Prefiles now posted for session start next week

FL: Second Special Session

---

scrapers/usa/bills.py

@jamesturk this works with --scrape, just wanted to flag before merging in case you needed to run migrations first or anything.

USA: Move to structured legal cites

---

scrapers/nv/__init__.py
scrapers/nv/common.py

NOTE: Don't merge until they file some bills.

NV: 2021 first special

---

scrapers_next/nh/committees.py

New branch for the NH committee

NH: committees

---

scrapers_next/ks/committees.py

KS: committees

---

scrapers/md/__init__.py

Prefiles for special session have been [posted](https://mgaleg.maryland.gov/mgawebsite/Legislation/Index/house)!

MD: support special session

---

scrapers/ar/__init__.py
scrapers/nm/__init__.py

Also ignore NM special session until bills are posted (session starts today so will check later)

AR: support special session

---

scrapers/wy/__init__.py
scrapers/wy/bills.py

Also update a few urls to HTTPS

WY: Add 2022 Session

---

scrapers/in/__init__.py

Prefiles have been [posted](http://iga.in.gov/legislative/2022/bills/)

IN: support 2022 prefiles

---

scrapers/md/__init__.py

Prefiles [posted](https://mgaleg.maryland.gov/2022rs/misc/billsmasterlist/legislation.json)

MD: support 2022 prefiles

---

scrapers/sd/__init__.py
scrapers/sd/bills.py

Bills haven't been [posted](https://sdlegislature.gov/api/Bills/Session/Light/64) yet, will hold off on merging until they are.

SD: Support 2022

---

poetry.lock
pyproject.toml
scrapers/in/events.py

Add the cloudscraper library to help with cloudflare protected IN events listing page.

IN: Events: Cloudflare fixes

---

scrapers_next/in/people.py

Scrape all Republican House members instead of just the first page.

IN: people fix

---

docker-compose.yml
scrapers/ga/__init__.py
scrapers/nd/__init__.py
scrapers/nv/__init__.py
scrapers/ok/__init__.py
scrapers/tn/__init__.py

Updated init files for GA, ND, NV, OK, & TN to reflect end of special sessions. Also added update to docker-compose.yml to avoid docker version errors, but lmk if I should remove.

Update Inactive Special Sessions

---

scrapers/ri/__init__.py

DO NOT MERGE until bills are filed and looking good.

RI: 2022 session

---

scrapers/wv/__init__.py

https://github.com/openstates/issues/issues/597

WV: fix special session classification

---

scrapers/tn/__init__.py

https://github.com/openstates/issues/issues/601

TN: disable ssl verify on session list page

---

scrapers/ar/__init__.py
scrapers/ar/bills.py

Looks like they updated the vote page layout, updated the xpaths to be correct. Also added 2022 Fiscal session that should start this week but active is still set to False until bills posted.

AR: fix vote issue

---

scrapers/wv/__init__.py

DO NOT MERGE until bills are filed and looking good.

WV: 2022 session

---

scrapers/hi/bills.py

HI started posting versions behind a form instead of their sidebar; so add them to the scraper.

HI: Scrape versions from header as well as sidebar

---

scrapers/al/bills.py

Special sessions have the fun session url format again.

AL: update url for special session bills

---

scrapers/ri/bills.py

https://github.com/openstates/issues/issues/617

RI: Allow for multiple bill spans with gaps

---

scrapers/oh/bills.py

SCR 14 was getting missed since it doesn't have a title

OH: get resolution missing title

---

README.md

Fix README's URLs

---

scrapers/ga/__init__.py

GA: Adjust session end year

---

scrapers/ky/events.py

Widen KY Events regex to remove adjournment of the house.

KY: Events: Regex Fix

---

scrapers/ct/__init__.py

DO NOT MERGE until bills are filed and looking good.

CT: 2022 session

---

scrapers/az/bills.py

Should resolve https://github.com/openstates/issues/issues/629

AZ Bill Scrape Failing

---

scrapers/az/bills.py

Scraper is timing out on calls all over, so added high timeouts to get calls.

AZ: increase timeout on self.get calls

---

scrapers/ut/__init__.py

Special session started [today](https://le.utah.gov/session/2022S3/Proclamation.pdf) for one bill

UT: add special session

---

scrapers/wv/events.py

Fix events "shortly after the second floor session"

WV: event scraper fixes

---

scrapers/va/__init__.py
scrapers/va/csv_bills.py

Successfully scrapes special session, file structure is wonky on FTP site so added in a check for that.

VA: add special session categorization & url

---

.pre-commit-config.yaml
scrapers_next/sd/people.py

Fix for SD people data on VJ Smith
https://github.com/openstates/issues/issues/655

Fix duplicate middle initial

---

scrapers_next/vt/people.py

https://github.com/openstates/issues/issues/641
https://github.com/openstates/issues/issues/640#issue-1133206039

VT scraper errors

---

poetry.lock
scrapers/wy/__init__.py
scrapers/wy/bills.py
scrapers_next/mi/people.py
scrapers_next/tn/people.py

- Fix for MI people data on John Bizon
https://github.com/openstates/issues/issues/637
- Fix for TN people data on Cameron Sexton
https://github.com/openstates/issues/issues/654
- Fix for WY bill data: 2021 Special Session 1 amendment version links

Fixes on bill and people data

---

scrapers/fl/bills.py

adds HTML and PDF bill version links only if the url ends with "HTML"
only adds PDF bill version link if url ends with "PDF"

FL pdf html bill versions

---

scrapers_next/pr/people.py

rewrote scraper for house for Puerto Rico based on the source url change

PR house scraper

---

scrapers/ut/__init__.py

Doesn't have any bills posted so ignoring session on scrape

UT: ignore 2023 session for now

---

scrapers/fl/__init__.py

Special session starts next week and there's a single bill posted

FL: support special session c

---

scrapers/ar/bills.py

We can avoid ftp urls through some string manipulation. Special sessions have a different format too.

AR: Update URLs

---

scrapers/az/bills.py
scrapers/ms/bills.py

Also fixes issue with AZ pdf links

MS: Add PDF Links

---

scrapers/mn/bills.py

Looks like this doesn't need to be a separate request any more, and we can pull PDFs.

MN: Get pdf versions and more version metadata

---

scrapers/fl/__init__.py
scrapers/fl/bills.py

House has 2 bills posted so far, session starts on Monday

FL: Enable 2022D Session

---

scrapers/usa/votes.py

Updating the vote scraper to run, had new status to capture for successful scraping

USA: add resolution failed to senate status map

---

scrapers/ok/__init__.py

OK: support third special session

---

scrapers/mn/__init__.py
scrapers/tx/__init__.py
scrapers_next/de/people.py

And add timeout to DE people detail scraper

Pull MN & TX Historical Sessions

---

scrapers/mn/__init__.py
scrapers/tx/__init__.py
scrapers_next/de/people.py

Reverts openstates/openstates-scrapers#4062

Revert "Pull MN & TX Historical Sessions"

---

poetry.lock
pyproject.toml

pin openstates-core to git rather than pypi

---

scrapers/nh/bills.py

handle bad vote lines in NH

---

scrapers/in/__init__.py

Bills posted for session start on monday

IN: 2022 Special Session

---

scrapers/ar/__init__.py

Pending, don't merge until there are bills to test.

AR: 2022 Third Special

---

scrapers_next/il/people.py

fix IL people scraper

---

scrapers_next/ia/people.py

fix IA people scraper

---

scrapers_next/nc/people.py
scrapers_next/nd/people.py
scrapers_next/ok/people.py
scrapers_next/wa/people.py

Small people scraper fixes

---

scrapers_next/ga/people.py

fix GA people scraper

---

scrapers_next/fl/committees.py
scrapers_next/fl/people.py

fix FL people scraper

---

scrapers_next/ca/people.py

fix CA people scraping

---

scrapers_next/al/people.py

fix problems with AL people scraping

---

scrapers_next/co/people.py
scrapers_next/dc/people.py
scrapers_next/de/people.py
scrapers_next/hi/people.py
scrapers_next/ks/people.py
scrapers_next/ky/people.py
scrapers_next/ma/people.py
scrapers_next/mn/people.py
scrapers_next/mo/people.py
scrapers_next/nh/people.py
scrapers_next/nv/people.py

DC, CO, DE, NH, HI, NV, KS, MN, MO, KY, and MA

small changes to people scrapers

---

scrapers_next/pr/people.py

PR people scraping fixes

---

scrapers/id/__init__.py

ID: get special session bills

---

scrapers/ar/bills.py

raise empty scrape error when no bills in AR

---

scrapers/va/csv_bills.py

This _might_ solve the random VA auth problems by simply retrying the connection to the SFTP site a few times. Hard to fully validate because the failures seem so random, but...
Also add compression to the SSH session to speed up data over the wire slightly.

Va auth retries

---

.dockerignore
scrapers/ar/bills.py
scrapers/va/common.py
scrapers/va/csv_bills.py

Actually closing the sftp connection between runs seems to help. I think this may have been a race condition with sessions not timing out quickly enough.

Va auth retries fix v2

---

scrapers/dc/__init__.py
scrapers/dc/bills.py
scrapers/dc/events.py
scripts/run-docker.sh

DNS changed from dccouncil.us -> dccouncil.gov

Dc fix for bad URLs

---

scrapers/ms/__init__.py

They added it to the session list but don't have bill info posted yet.

MS: Ignore 2023 Session Temporarily

---

scrapers/wy/__init__.py

Session showed up, but no bills yet.

WY: ignore 2023 for now

---

scrapers/in/__init__.py

Bills haven't been posted yet, but they did add the session as an option via the API

IN: Ignore 2023 Session

---

scrapers/nc/bills.py

Looks like they're updating site urls still. Hopefully this doesn't mean a whole new site soon. This fixes [scraper issue 800](https://github.com/openstates/issues/issues/800)

NC: Update Bill Detail URL

---

scrapers/ny/events.py

NY house changed their markup a bit.

NY: Events: Xpath fix

---

scrapers/tx/__init__.py

Resolves https://github.com/openstates/issues/issues/808

TX: add 2023

---

scrapers/sc/events.py

Add status, classification, participants, and media links to SC events.

SC: Event scraper updates

---

scrapers_next/in/people.py

be less strict with members in IN

---

scrapers_next/wa/people.py

allow for fewer members in WA

---

scrapers_next/ak/people.py

Alaska replaced the XML list page of members with an HTML list page. This PR contains a rewritten AK people scraper that successfully scrapes all member data from the new HTML list page.

AK: people scraper rewritten for HTML List Page

---

scrapers_next/ny/people.py
scrapers_next/sc/people.py

1. reduce size of legislature in NY
2. handle an empty starting string for a capitol addressin SC

Two people scraper fixes

---

scrapers_next/nd/people.py

some ND members don't have photos

---

scrapers_next/in/people.py

reduce D senators in IN

---

scrapers/wa/__init__.py

WA: add meta for 2023, not active

---

scrapers/ar/__init__.py
scrapers/ar/bills.py

@NewAgeAirbender FYI you'll need to add a new set of secrets to the job definition 
AR_FTP_USER
AR_FTP_PASSWORD
I don't remember off the top of my head where this lives but if you can't find it let james and I know.

AR: Fix bill scraper for new ftp

---

scrapers/ga/__init__.py
scrapers/ga/util.py

GA: 2023 Prefiles

---

scrapers/hi/bills.py
scrapers/hi/utils.py

Looks like they've updated the committee page, this gets them again

HI: Fix Committee Shortcodes

---

scrapers/nv/__init__.py

Looks like they posted a bunch of bills on the 16th

NV: 2023 Prefiles

---

scrapers/me/__init__.py

Session starts the 7th, check back then.

ME: Add 2023, ignored for now

---

scrapers/ca/__init__.py

Got it ready to roll when the bill data is actually posted

CA: 2023 session

---

scrapers/ia/__init__.py

No data yet for 2023, just figured I should add it while I was in the file.

IA: Set RPM & Add 2023 Session Metadata

---

scrapers/wa/__init__.py
scrapers/wa/bills.py

https://github.com/openstates/issues/issues/814

WA: 2023, fix for prefile dates, citations

---

scrapers/ca/__init__.py
scrapers/fl/__init__.py

Session doesn't have bills posted, also updates end date on CA.

FL: Ignore 2022A

---

scrapers/ca/__init__.py

disable special session for now

---

scrapers/me/__init__.py

ME: Scrape 2023

---

scrapers/ia/votes.py

Need the new session in the vote scraper

IA: Add 2023 to Votes

---

scrapers/ms/__init__.py
scrapers/sd/__init__.py
scrapers/ut/__init__.py

Mostly update dates and move from ignored to just an inactive session

MULTI: update metadata

---

scrapers_next/oh/people.py

Issue that triggered investigation was resolved by a change to the legislative site. However, other discoveries were made that prompted changes.
1. The first few runs of the scraper failed due to `urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ohiohouse.gov', port=443): Read timed out. (read timeout=5)`
- I raised `timeout` from `30` to `100` to attempt to rectify this. The frequency of `ReadTimeoutError` fails seems to have been reduced (but not eliminated). However, please let me know if I misunderstood how to adjust this attribute.
2. After seeing a message logged to the terminal that one of the senators' social media handles was not matched, I discovered that senator's twitter url was formatted differently.
- I converted the url's to all lowercase and added …

OH people: timeout level raised, social media fixes

---

scrapers_next/sc/people.py

SC people scraper was failing with:
1. IndexError when working on capitol address
- Problem line: `line2 = cap_addr_path.getchildren()[0].tail`
- Cause: member's page missing a capitol address
- Solution: wrapped section in conditional to handle and store capitol address only when XPath selector encounters one
2. AttributeError when working on home address
- Problem line: `city, h_zip = self.zip2_re.search(home_line2).groups()`
- Cause: member who had only a zip code on the second line of their home address
- Solution: split section into conditionals to handle each case
Additionally discovered:
1. Unnecessary/unwanted space stored before comma in a couple addresses
- Solution: regex substitution

SC people: fixes for missing address, alt address format

---

scrapers_next/nv/people.py

NV people scraper was failing because indexing approach to identifying each data field was reliant on consistency across all members' detail rows (but the number/types of these fields differed throughout the table).
- Error: `IndexError: list index out of range` on line 58: `leg_bldg_phone = extra_info_detail[3].text_content().strip()`
- Solution: Iterate through details fields, using conditionals to store details in person object according to the field name / label on the site.
- Also added custom exception to be raised (`NewDetailFieldEncountered(BaseException)`). If the legislative site adds any other detail fields, or changes the names of any of the current labels, this exception will be raised so scraper can be updated accordingly.

NV people: new process for parsing/storing extra details

---

scrapers/usa/__init__.py

Just noticed this was defaulting to only one old session.

USA: Add hardcoded session list

---

scrapers/in/actions.py
scrapers/in/bills.py

Indiana action classification updates. These updates aim to increase action classification coverage as well as standardize the classification code so that it utilizes the BaseCategorizer class defined [here](https://github.com/openstates/openstates-scrapers/blob/3e5b5b1eec50f71a7b15b8be1c409a8be483694d/scrapers/utils/actions.py#L62).

IN action classification updates

---

scrapers/dc/actions.py
scrapers/dc/bills.py

DC action classification updates. These updates aim to increase action classification coverage as well as standardize the classification code so that it utilizes the BaseCategorizer class defined [here](https://github.com/openstates/openstates-scrapers/blob/3e5b5b1eec50f71a7b15b8be1c409a8be483694d/scrapers/utils/actions.py#L62).

DC action classification updates

---

scrapers_next/hi/people.py

HI people scraper was rewritten in response to a complete redesign of the page on the legislative site.

HI people: scraper rewritten for new member list page

---

scrapers/ca/__init__.py

Making sure the date is accurate

CA: Update Special Metadata

---

poetry.lock
scrapers/ut/events.py

simplify ut event loop and bump openstates dep

---

scrapers/al/events.py

fix spelling in AL events scraper

---

scrapers/sc/bills.py

They haven't actually published the doc files yet, holding off for now. Emailed their webmaster for an estimate on timeline, hoping for a response

SC: skip creating .docx versions

---

scrapers/ga/events.py
scrapers/ks/events.py
scrapers/md/events.py
scrapers/mo/events.py
scrapers/nc/events.py
scrapers/nd/events.py
scrapers/nm/events.py
scrapers/sc/events.py
scrapers/usa/events.py
scrapers/vt/events.py
scrapers/wi/events.py

Fix some jurisdictions where emptyscrapes for events can happen

---

scrapers/oh/events.py

OH returns broken json when there are no objects

---

scrapers/ct/events.py

fix CT events

---

scrapers/wv/events.py

WV: fix event duplicates

---

scrapers/wv/events.py

WV: fix linting

---

scrapers/nh/events.py

better dup discovery for nh

---

scrapers/mi/bills.py

The previous solution never correctly evaluated to Z or ZZ

Fix for HJR that includes HJR Z

---

scrapers_next/ca/people.py

Scraper was failing when running `AssemblyList` class. The following are the errors and solutions:
1. Data validation error for `image` attribute of person object
- Issue: When img src wasn't present on page, a `None` type was being stored when only a `str` type is valid.
- Solution: Added `or ""` to store an empty string when `phone_url` is `None` type.
2. Capitol and district office handling was experiencing selector errors and was not storing all offices listed
- Solution: Capitol and district office address and phone handling entirely rewritten to utilize regex pattern matching.

CA people: AssemblyList fixes for img + office handling

---

jurisdiction_configs.json
scrapers_next/ar/people.py
scrapers_next/ga/people.py
scrapers_next/il/people.py
scrapers_next/ma/people.py
scrapers_next/me/people.py
scrapers_next/mo/people.py
scrapers_next/mt/people.py
scrapers_next/sd/people.py
scrapers_next/wy/people.py

The following Jurisdictions needed Session numbers/ids updates for the People Scrapers
AR
GA
IL
MA
ME
MO
MT
SD
WY

Updated Session Numbers/IDs for People Scrapers for 2023 Sessions

---

scrapers_next/me/people.py

Looks like they've left off some columns that we'll want eventually, hence commenting them out instead of deleting entirely. Correctly scrapes Senate Legislator data.

ME: Senate Index Fix

---

scrapers/nc/__init__.py

Created but no bills posted yet

NC: ignore 2023 for now

---

scrapers/dc/__init__.py

DC: Scrape 25th Session

---

scrapers/ok/events.py

allow for empty scrape in OK

---

scrapers/ky/events.py
scrapers/ny/events.py
scrapers/wy/events.py

Fix empty events in KY, NY, and WY

Empty events

---

scrapers/mn/events.py

set default mime type for MN

---

scrapers/nd/events.py

fix nd event

---

scrapers/nd/__init__.py

reduce ND RPM even more

---

.github/workflows/ca-docker.yml
.github/workflows/docker.yml
.github/workflows/lint.yml
.github/workflows/scrape.yml

update CI steps for scrapers

---

scrapers/mn/__init__.py

MN: set 2023 live

---

poetry.lock

bump deps (should fix NJ event scraping)

---

scrapers/ky/__init__.py

Ready to merge when they actually post bills

KY: 2023 session

---

scrapers/usa/__init__.py

No bills yet, but prepared the metadata

USA: Prep 118th Session

---

scrapers/nm/__init__.py

Also removed a few ignored sessions that we had metadata for.

NM: 2023 live

---

scrapers/ks/__init__.py

KS: set 2023 live

---

scrapers/la/__init__.py
scrapers/la/bills.py

No bills, suppose to prefiling in February

LA: 2023 Metadata

---

scrapers/ky/events.py
scrapers/mt/bills.py

fix MT motion lines without breaks and add user agent to KY requests

---

scrapers/ri/__init__.py

RI: set 2023 live

---

scrapers/ne/__init__.py

No bills yet, just prepping the metadata

NE: 2023 Metadata

---

scrapers/ma/__init__.py

MA: 2023 Session

---

scrapers/ne/__init__.py

Ready when they actually post bills

NE: set 2023 live

---

scrapers_next/wi/people.py

Updated Hardcoded Value for WI People Scraper for 2023 Session

Updated Hardcoded Value for WI People Scraper

---

scrapers/oh/events.py

handle empty scrape in OH

---

scrapers_next/nh/committees.py

I forgot to check what branch I was working on before I wrote this :/ . Sorry for the misleading branch name! These are the changes for the **NH committee scraper** . Fixes related to [OS-875](https://civic-eagle.atlassian.net/browse/OS-875) .

NH: exception handling for bad redirects, adding comments, cleaning up variable names

---

scrapers_next/vt/people.py

Updated VT url for 2023-2024 Session

Updated VT url for 2023-2024 Session

---

scrapers/hi/bills.py

HI might send canonical URLs now

---

scrapers/mt/events.py

some events are missing rooms

---

scrapers/id/events.py

handle empty scrape in ID

---

scrapers/mt/events.py

MT events: handle duplicate links

---

scrapers/mt/events.py

MT Events: handle duplicate documents better

---

scrapers/mt/events.py

cleaner fixes for MT event problems

---

scrapers/in/events.py
scrapers/in/utils.py

A refactor on the INDIANA events scraper to use the official API because we were getting blocked  by cloudflare

refactor: use official API for Indiana

---

scrapers/id/__init__.py

1 resolution posted, I'll take it

ID: Set 2023 Live

---

scrapers/or/__init__.py

Finally letting us see all the prefiles, theres 1k+ bills now

OR: 2023 live

---

.devcontainer/devcontainer.json
.devcontainer/install.sh

This creates a devcontainer that installs the necessary dependencies locally, this allows JSON scrapes to be run from the container.  (This does not attempt to set up the database/etc. but it'd be theoretically possible to add a more complex devcontainer if desired.)

Add devcontainer

---

scrapers_next/or/people.py

Updated the url for OR People Scraper for New 2023 Session

Updated OR People Scraper for New Session 

---

scrapers_next/il/committees.py

Committee scraper for IL - associated with [OS-463](https://civic-eagle.atlassian.net/browse/OS-463). 
Specific concern: I wasn't sure if it was necessary to have two separate HouseDetail and SenateDetail classes if they both did the same thing. I currently have both HouseList and SenateList pointing to a singular ChamberDetail class to grab membership information. Let me know if you'd like me to change this (or anything else)!

IL committee scraper

---

poetry.lock

chore: update openstates

---

scrapers/nc/__init__.py

No bills posted yet, ready for when they do.
[House](https://www.ncleg.gov/Legislation/Bills/FiledBillsFeed/2023/H) bills & [Senate](https://www.ncleg.gov/Legislation/Bills/FiledBillsFeed/2023/S)

NC: set 2023 live

---

scrapers/al/__init__.py

Prefiles are suppose to be up starting yesterday but nothing yet so just prepped the metadata

AL: 2023 metadata

---

scrapers/il/__init__.py

https://github.com/openstates/issues/issues/881

IL: fix for scraped name change

---

scrapers/tx/events.py
scrapers/wv/events.py

TX events can be empty
WV event stream spelling errors

Scraper fixes 2023 01 12

---

scrapers/hi/__init__.py
scrapers/hi/bills.py

Not posted yet, ready when they are. Suppose to be today (1-11)

HI: 2023 prefiles

---

scrapers/ca/events.py
scrapers/dc/events.py
scrapers/in/events.py
scrapers/nd/events.py

CA had a bad property (`type`) defined
DC had a typo `commitee` vs. `committee`
IN needed to handle duplicates better
ND needed to handle duplicates better

Event fixes 2023 01 13

---

.github/workflows/ca-docker.yml
docker-compose.yml
scripts/exec.sh

fix CA container build

---

.github/workflows/ca-docker.yml

actually push container

---

scrapers/al/events.py
scrapers/ny/events.py

handle empty location in ny and empty scrape in AL

---

scrapers_next/ak/committees.py
scrapers_next/co/committees.py
scrapers_next/ks/committees.py
scrapers_next/mo/committees.py

Just running through some that were broken & could easily fix the urls or selectors

Committee URL updates

---

.github/workflows/lint.yml

add --diff to black output so we can see what needs to change

---

scrapers/mn/events.py

fix bill discovery regex for MN

---

scrapers/sc/events.py

handle weird formatting of event locations when canceled

---

scrapers_next/sc/people.py

handle independent in SC

---

scrapers_next/in/people.py

fix IN Democratic Senate scrape

---

scrapers_next/nm/people.py

fix NM people scraper

---

scrapers/mn/events.py

Catch periods in the bill name as well as spaces...

Mn event house fix

---

scrapers/mo/events.py
scrapers/ok/events.py

Fix duplicate events for MO and OK

2023 01 20 fixes

---

scrapers/nh/bills.py
scrapers/nh/events.py

Added security to the site, usually still gets there but quiets the code editor a bit.

NH: add https

---

scrapers/la/__init__.py
scrapers/la/bills.py

LA: 2023 session live

---

scrapers_next/ne/committees.py

Newly written scraper for Nebraska.
For standing committees run `StandingCommList` and for select+special committees run `SelectCommList`.

NE comm: new write, gets standing, select, special

---

scrapers_next/mi/committees.py

Slightly changed their site, but not a whole lot

MI: update Senate committee member selector

---

scrapers/ia/votes.py
scrapers/md/events.py
scrapers/mo/bills.py
scrapers/nm/bills.py
scrapers/usa/events.py

Fix USA events (bad validation of `nomination` event type)
Fix IA events (bad grammar)
Fix MD events (empty committee names)
Fix MO scrape (writing empty notes into bill versions)
Fix NM scrape (doubling up on https://github.com/openstates/openstates-scrapers/pull/4414, this makes custom mappings more consistent)

2023 01 24 fixes

---

scrapers/mn/events.py

fix MN senate committee links

---

scrapers_next/ms/committees.py

New committee scraper written in spatula for Mississippi.
It scrapes two XML pages, one for House and one for Senate.

MS comms: new committee scraper

---

poetry.lock

bump os-core version to handle nominations right

---

poetry.lock
pyproject.toml
scrapers/hi/events.py
scrapers/ks/events.py
scrapers/mt/events.py
scrapers/or/events.py
scrapers/usa/events.py

Fix MT missing a time for events
Fix OR events adding bad links
Fix duplicates in KS
Fix nomination type for USA events

2023 01 25 fixes

---

scrapers/mo/events.py
scrapers/nd/events.py
scrapers/ne/bills.py
scrapers/wv/events.py

ND events fix
WV events fix (more bad naming)
NE bills fix
MO events fix

2023 01 27 fixes

---

scrapers_next/in/committees.py
scrapers_next/ma/committees.py

Please review the code I had to add verify false flag & I suppressed warnings for ssl error.

Added MA committees scraper  

---

scrapers_next/vt/committees.py

Scraper for VT using JSON page.

VT Committee scraper

---

scrapers/nc/bills.py

We were totally missing actions, this gets them now

NC: fix actions xpath

---

scrapers_next/ct/committees.py

New spatula-based scraper for getting Connecticut legislative committee data.

CT committee scraper

---

.github/workflows/lint.yml
poetry.lock
pyproject.toml

use poetry linter in CI so it's consistent

---

.pre-commit-config.yaml
scrapers/nd/events.py

Update pre-commit settings to follow what we actually expect in this repo

Pre commit updates

---

scrapers/la/__init__.py

LA: 2023 special live

---

scrapers/hi/events.py
scrapers/il/events.py

Duplicate events in HI
Bad event pages in IL

2023 02 02 fixes

---

scrapers/fl/__init__.py
scrapers/fl/bills.py

Have 3 bills posted for the session that starts next week. Also moved the special session for 2022 to be with the rest of the 2022 sessions.

FL: special session live

---

scrapers/az/events.py
scrapers/usa/events.py

AZ duplicate fix
USA missing doc type and date parsing improvements

2023 02 06 fixes

---

scrapers/ky/events.py

duplicate events in KY

---

scrapers_next/de/committees.py

Created DE committee scraper

---

scrapers/ks/events.py
scrapers/nm/events.py
scrapers/or/events.py
scrapers/wv/events.py

NM event empty agendas
OR empty event agendas
KS dedupe key could be too long
WV had another bad date string

2023 02 09 fixes

---

scrapers_next/hi/committees.py

Created HI committee scraper

---

scrapers_next/nm/committees.py

New spatula-based scraper written for New Mexico.

NM committee Scraper

---

scrapers/ia/actions.py
scrapers/ia/bills.py

Iowa action classification updates, related to [OS-1077](https://civic-eagle.atlassian.net/browse/OS-1077). These updates aim to increase action classification coverage as well as standardize the classification code so that it utilizes the BaseCategorizer class defined [here](https://github.com/openstates/openstates-scrapers/blob/3e5b5b1eec50f71a7b15b8be1c409a8be483694d/scrapers/utils/actions.py#L62).

IA: action classification updates

---

scrapers/wy/actions.py
scrapers/wy/bills.py

Action classification updates for WY. Relates to [OS-1076](https://civic-eagle.atlassian.net/browse/OS-1076)

WY: action classification update

---

scrapers_next/or/committee.py

Hi,
I added the OR committee scraper using the Spatula.

adding OR committee scraper

---

scrapers_next/ia/committees.py

This new committee scraper for Iowa was [built by GH user @jonathanortega2023](https://github.com/openstates/openstates-scrapers/pull/4376), with some modifications made on top of their work.

IA comm: scraper built by @jonathanortega2023

---

scrapers_next/mi/people.py

Updates the people scraper to write out office addresses as they appear on legislators' page. Relates to Issue 1 of [OS-1176](https://civic-eagle.atlassian.net/browse/OS-1176)

MI: people scraper update

---

scrapers_next/wv/committees.py

[Related Issue](https://github.com/openstates/issues/issues/866)
- add committee scraper for West Virginia

WV Committee Scraper

---

scrapers_next/mi/people.py

Reverts openstates/openstates-scrapers#4496
HOW did I accidentally merge the wrong PR in? Im so sorry!

Revert "MI: people scraper update"

---

scrapers_next/pr/committees.py

I left all the committee names and roles in Spanish, didn't think it made sense to change them! Let me know if there are any questions.

PR Committee Scraper

---

scrapers_next/al/people.py

Created people scraper for AL.
Should I combine SenList and RepList into one class or should I keep them separate?

AL people scraper

---

scrapers_next/al/committees.py

AL committee scraper

---

scrapers/ok/events.py

OK: New event scraper

---

scrapers_next/ok/committees.py

Senate scraper was working, but all other chamber committees needed rewrite.
This PR wrote new scrapers for:
- `House`
- `HouseAppropriationsSubComs`
- `Joint`
- `Conference`
- `Special`
And added skip for empty committees in the Senate scraper.

OK comm: rewrite lower, legislature chamber comms

---

scrapers/ga/events.py

Modified events.py to scrape bill ids from agenda pdf and add them to the event.

Modified GA events.py to scrape bill ids from agenda pdf

---

scrapers/ar/events.py

Modified AR events.py to scrape bill id's from the agenda pdf.

Bugfix for AR events.py

---

scrapers/wv/events.py

Changes:
- Fixed bill id formatting
- Fixed date formatting that was causing scraper to exit with an error

Bugfix WV events

---

scrapers_next/ny/committees.py

1. Issue: This fix was prompted by a SelectorError that occurred when a committee did not have an address present.
- Solution: The selector process was reformatted to allow for such cases while also accommodating other variance in committee addresses
2. Issue: an additional SelectorError occurred when identifying the roles of either a single Chair or multiple Co-Chairs.
- Solution: The block was simplified to check the length of the list of chairs, and determine chair role title based on that value.

NY comm: fix address, chair role selector errors

---

scrapers/tn/events.py

Fixed TN events.py so bill ids are scraped.

Fixed bill scraping for TN events.py

---

scrapers_next/ny/people.py

Scraper fix related to [DATA-2361](https://civic-eagle.atlassian.net/browse/DATA-2361).

NY: adding scraping for address and voice for senators

---

scrapers/tx/events.py

- Prevented duplicate events from being added.
- Update regex so correct bill ids are extracted.

Bugfix for TX events

---

scrapers/ct/events.py

Added bill id scraping from pdfs.

bugfix for CT events.py

---

scrapers/ok/events.py

Updated to scrape linked pdf for bill ids.

Bugfix OK events.py

---

scrapers/ia/bills.py

Looks like we're having connection issues on bobsled so tried a few different ways to get around it. Did get one successful full run locally!

IA: Connection Fix

---

scrapers/nh/events.py

Fixed xpath selectors and formatted bill ids

Fixed xpath selectors for bills in NH events.py

---

scrapers/nv/events.py

Switched over to scraping this page: https://www.leg.state.nv.us/App/NELIS/REL/82nd2023/Meetings

Updated NV events.py

---

scrapers/ms/events.py

Changed the site used to scrape senate events and added regex to capture bill ids in house scraper

Changed senate scraping for MS events.py

---

scrapers/id/events.py
scrapers/ks/events.py
scrapers/mi/events.py
scrapers/ms/bills.py
scrapers/ms/events.py
scrapers/wi/events.py

Fix ID events with empty description
Handle empty events in KS
Handle duplicate events in MI
Handle poorly formatted times in MS events
Handle strange empty arrays in MS bills
Fix URL and empty events for WI events

2023 03 14 fixes

---

scrapers/ia/bills.py

Issue: Scraper was missing House and Senate study bills ("HSB" and "SSB") by scraping the "All Bills" page.
Solution: This PR adds additional scraping of the dropdown menu options for each chamber's study bills from the "Bill Book" page.
- *This PR only adds the "Bill Book" source for those specific bill types, while maintaining the "All Bills" page as the primary source for bills due to its neater (and perhaps more reliable) presentation of a bill's title and sponsors.*

IA bills: add bill book page scrapes for study bills

---

scrapers/sc/events.py

- Modified to scrape all chambers if no chamber is provided
- Fixed some time parsing issues
- Added bill id scraping from agenda pdfs

Bugfixes for SC events.py

---

scrapers/oh/events.py

Added bill scraping from agenda PDFs

Add bill id scraping for OH events.py

---

scrapers/il/__init__.py

Somehow missed in setting new sessions live

IL: set 102nd inactive

---

scrapers/ak/events.py

Expanded room names and address abbreviations into full addresses

Expanded address abbreviations in AK events.py

---

scrapers/md/bills.py

MD Sometimes posts tests bills to the site that they later delete, ignore them.
Relates to https://github.com/openstates/issues/issues/979

MD: Skip test bills

---

scrapers/nv/events.py

Issue
- Events scraper was failing with `spatula.selectors.SelectorError: XPath(.//a[@title="View the agenda for this meeting"]/@href) on <div class='row py-2 py-md-1'> @ line 31738 got 0 results, expected 1`
- This was caused by the absence of agenda or agenda link for committee floor meetings
Solution
- use of `try...except` clause, as well as alternative handling for date and time, so that it is never dependent on agenda PDF, even in special cases

NV events: handle events without agenda link

---

scrapers/il/events.py

Changed event descriptions and added a space to bill ids

bug fixes IL events.py

---

scrapers/mt/bills.py

This PR refactors Montana bills scraper's `_parse_votes()` method into `_parse_pdf_votes()` and `_parse_html_votes()`, and temporarily skips committee vote PDFs (leaving `_parse_pdf_votes()` uncalled) during scraper run.
The idea behind this is that most (if not all) committee vote PDFs were failing to be parsed, and the many failed attempts is likely what has been causing the scraper as a whole to fail.
Note on the *temporary* nature of this change: separately from this PR, I am locally testing the PDF links to determine the parsing issue. Once I have determined it, I will write a solution and create a new PR that adds committee vote PDF parsing back into the scraper's functions.

MT bills: (temporarily) skip committee vote PDFs

---

scrapers_next/la/committees.py
scrapers_next/la/people.py

People
-------
- Regex added to validate fax number formats
Committees
------------
- Regex used to fix names with misplaced suffixes

LA: people and comms updates

---

scrapers/al/actions.py
scrapers/al/bills.py

Add some more action classifications, and start scraping votes.

AL: Bills and Votes enhancements

---

scrapers/al/bills.py
scrapers/usa/votes.py

AL: Scrape Enacted actions and final acts
USA: Fix for votes scraper, skip non-bill votes

AL, USA: Misc small fixes

---

scrapers/ar/bills.py

This PR comments out the code block that would trigger scraper to get vote events during run of Arkansas bills scraper.
Context
--------
- This is the second bills scraper to continually fail on vote event processing within the last couple weeks (the other being MT bills, for which this temporary solution [was also implemented](https://github.com/openstates/openstates-scrapers/pull/4599))
- Ultimately, this may require changes to OS-Core code for vote events processing. The issue is still being investigated.
- In the meantime, a `TODO` statement has been added in this PR re: reincorporating the commented-out code block once the underlying issue has been identified and resolved.

AR bills: ~temporarily~ disable vote events processing

---

scrapers_next/fl/people.py

Was missing updated urls for legislators

FL: add links to legislators

---

scrapers/ca/bills.py

Slight tweak, also adds a set to subjects so we don't get duplicate subjects

CA: fix SB867 subject & add set to subject

---

scrapers/ut/__init__.py

UT: scrape special session

---

scrapers/de/bills.py

Resolves https://github.com/openstates/issues/issues/1051

DE: Fix for broken citation reference

---

scrapers/wa/actions.py

https://github.com/openstates/issues/issues/1055

WA: Bills: Fix for errant action classifier

---

scrapers/sc/events.py

This is in testing, hold off merging.

SC: Events: Manual fix for weird time

---

scrapers_next/de/people.py
scrapers_next/hi/people.py
scrapers_next/id/people.py
scrapers_next/me/people.py
scrapers_next/mn/people.py
scrapers_next/nc/people.py
scrapers_next/ri/people.py
scrapers_next/sc/people.py
scrapers_next/tn/people.py
scrapers_next/wy/people.py

Just did an update on the People repo & had some scrapers that needed some tweaks

Multi: People Scraper Fixes

---

scrapers/vt/bills.py

Due to a change in how VT presents their versions, we were overwriting bill versions across different printings. 
So for example "as passed the senate" was getting named "Official" and potentially overwriting the "As introduced" printing, because it shared the same document name.

VT: Fix for overwritten versions

---

scrapers/ks/bills.py

Bringing KS in line with how we label it in the rest of the states.

KS: Bills: Classify primary sponsor correctly

---

poetry.lock
pyproject.toml
scrapers/vi/__init__.py
scrapers/vi/bills.py

@showerst I think this is a start towards fixing up VI.

start fixing VI scrapers

---

scrapers/oh/bills.py

Do not merge until test run is finished.

OH: fix for multiple action date formats in source

---

scrapers/tx/events.py

Adds house and senate committee hearing videos to the scraper.

TX: Event Videos

---

scrapers/in/events.py

Address issues with committee names, source urls, and handle some server errors more gracefully.

fix many IN event bugs

---

scrapers/in/events.py

CloudFlare 520s on objects that aren't returning properly. We'll just return nothing in that case and move on.

handle 520s better

---

scrapers/ok/__init__.py

Starts on 10/3 so likely have some time until bills are posted

OK: Ignore 2nd Special Until Bills Posted

---

scrapers/ok/__init__.py

Need to pull this since the session is scraping

OK: remove 2023S2 from ignored_scrape_sessions

---

scrapers/tx/__init__.py

Sets most of the TX 2023 sessions inactive & updates the session dates to be accurate

TX: update sessions active & end_dates

---

scrapers/wy/events.py

Scrape back a few months for updates in WY, and fix broken attachment urls.

WY: Events: Scrape back more months

---

scrapers/md/__init__.py

Just so we're ready to rock when prefiles are posted

MD: add metadata for 2024 session

---

scrapers/mn/bills.py

Just having issues with `SSLCertVerificationError` on runs

MN: verify=false on bill requests

---

scrapers/pr/__init__.py

Changing up how we get the session list since we're having issues even getting to the first page

PR: add headers to get_session_list request

---

scrapers/pr/__init__.py

PR: bump timeout setting

---

scrapers/usa/votes.py

Also set default year when argument not passed explicitly

USA: votes scraper fix missing senate vote classification

---

scrapers/mo/bills.py

MO: subjects page does work occasionally

---

scrapers/mo/bills.py

The developers got back to me really quickly & were able to add bill subjects to the detail pages on the XML site so we don't have to scrape them in the beginning or deal with 403 errors. Also updates `http` to `https` for source sites.

MO: pull subjects from bill detail page for House bills

---

scrapers/sd/__init__.py
scrapers/sd/bills.py

SD: 2024 Session

---

scrapers_next/de/people.py

Running through some of the people scrapers & doing some fixes. There's a case where they list the district but dont have any people data on it since it's a vacant seat.

DE: pass if district missing person

---

scrapers_next/al/people.py
scrapers_next/pa/people.py
scrapers_next/sc/people.py

Just a few more misc fixes on people scrapers

AL, PA, & SC People Fixes

---

scrapers/ky/__init__.py

No bills posted yet, merge when there are

KY: 2024 metadata

---

scrapers/nm/__init__.py

NM: 2024 prefiles

---

scrapers/la/__init__.py
scrapers/la/bills.py

Still don't have bills posted yet so active is set to False

LA: add 2024 session & special sessions

---

scrapers/mo/events.py

I've updated the events scraping logic from XML source.

MO: scrape events for MO House from XML source

---

scrapers/la/__init__.py

There are 2 bills prefiled & posted

LA: 2024 live

---

scrapers/mn/bills.py
scrapers/mn/vote_events.py

I've added the vote scraping logic for MN Senate.

MN: add senate votes scraping logic

---

scrapers/ga/__init__.py

GA: fix end_date & set 2023_ss inactive

---

scrapers/ak/__init__.py
scrapers/az/__init__.py
scrapers/gu/__init__.py
scrapers/ia/__init__.py
scrapers/il/__init__.py
scrapers/in/__init__.py
scrapers/ma/__init__.py
scrapers/mn/__init__.py
scrapers/pa/__init__.py
scrapers/tn/__init__.py
scrapers/vt/__init__.py
scrapers/wa/__init__.py

Adjust dates in a couple ccases with TODO: fix dates

Multiple: update session end dates for multi-year sessions

---

scrapers/va/events.py

openstates/issues [1145](https://github.com/openstates/issues/issues/1145)

VA: improve Senate/upper events scraper

---

scrapers/ma/events.py

[#1149](https://github.com/openstates/issues/issues/1149)

MA: event scraper not getting agenda items / bills

---

scrapers/ok/__init__.py
scrapers_next/dc/committees.py

They posted 1 bill. Also updates the url for the DC committee scraper

OK: 2023S4 Live

---

scrapers/oh/bills.py

OH scraper should get committee related to an action [#1151](https://github.com/openstates/issues/issues/1151)

OH: scraper should get committee related to an action

---

scrapers/vt/events.py

VT: event scraper associating same bills with all meetings of a committee [#1150](https://github.com/openstates/issues/issues/1150)

VT: event scraper associating same bills with all meetings of a committee

---

scrapers_next/az/committees.py
scrapers_next/co/committees.py
scrapers_next/id/people.py
scrapers_next/in/committees.py
scrapers_next/mi/committees.py
scrapers_next/sd/committees.py
scrapers_next/va/committees.py

Running through some of the spatula scrapers & finding some fixes.

Multi: update sessions on committee & people scrapers

---

scrapers/or/__init__.py

OR: 2024 Live

---

scrapers/ok/events.py

House events API stopped returning senate events, so get them from the source.

OK: Scrape senate events

---

scrapers/ct/bills.py

[#1154](https://github.com/openstates/issues/issues/1154)
Trying to cut down on requests / speed up the CT scraper. WIP.

WIP: CT: remove alternate sponsor scrape

---

scrapers/ms/events.py

Couldn't follow the redirect for Senate so just set the link instead

MS: update Event urls

---

scrapers/ca/bills.py

Now SB 1211 is the problem instead of SB 889

CA: update bill with colon instead of period on subject

---

scrapers/nh/actions.py
scrapers_next/il/committees.py
scrapers_next/wy/committees.py

NH is adding `passage` to the wrong actions since it's not strict enough. Updates year in WY & committee codes in IL committee scrapers

Multi Committee scraper & NH action classification updates

---

scrapers/ca/events_web.py

[issues #1160](https://github.com/openstates/issues/issues/1160)

CA: EventsWeb: date parse issue

---

scrapers/ok/events.py

[issues #1158](https://github.com/openstates/issues/issues/1158)

OK: Events: xpath issue in adding bill

---

scrapers/ia/bills.py

Increases to help decrease fragility

IA: up retry attempts & wait

---

scrapers/pr/__init__.py

They're adding more historical data

PR: add 1985 session to ignore list

---

scrapers/vt/events.py

[#1161](https://github.com/openstates/issues/issues/1161)

VT: Events: update using html

---

scrapers/ca/events_web.py

[#1148](https://github.com/openstates/issues/issues/1148)

CA: Events: Missing Bill IDs

---

scrapers/wa/events.py

Missed this, should catch the related entities

WA: check for substitute or engrossed bill

---

scrapers/ca/events_web.py

Another variation to check for

CA: Time Fix

---

scrapers/wv/events.py

...to match more 'thirty minutes after' cases

WV: Events: Widen regex in clean_date

---

scrapers/usa/__init__.py
scrapers/usa/bills.py

[#1170](https://github.com/openstates/issues/issues/1170)

USA: Roll Call

---

scrapers/al/events.py

[#1169](https://github.com/openstates/issues/issues/1169)

AL: Add Bills to Events

---

scrapers/ar/__init__.py

Prefiles are supposed to post today but 2024F bills aren't added to the csv yet so holding off on setting the session as `True`

AR: Update End Dates

---

scrapers/usa/bills.py

Skip missing house vote roll call, and add a new senate vote classification.

USA: Bills: Vote scraper fixes

---

scrapers/pr/bills.py

Been running into 404 errors on scrape runs

PR: Add Headers to GET Requests

---

scrapers/mn/events.py

[1174](https://github.com/openstates/issues/issues/1174)

MN: House Committee & Event Name Cleanup

---

scrapers/ne/bills.py

[#1168](https://github.com/openstates/issues/issues/1168)

NE: Voter & Vote Count Fix

---

scrapers/ny/bills.py

[#1172](https://github.com/openstates/issues/issues/1172)

NY: Vote Roll Call

---

scrapers/mn/events.py

Testing out better name matching for entities in MN Events

MN: committee name cleanup

---

scrapers/mn/events.py

Testing out better committee matching on Events during import

MN: add chamber to committee name

---

scrapers/mi/__init__.py
scrapers/mi/bills.py
scrapers/mi/events.py

Bill and Event scrapers for new Michigan legislature site. Vote scraper not implemented yet.

MI: New website

---

poetry.lock
pyproject.toml
scrapers/mn/events.py

Officially got it working so now `other_names` is checked & will help with org name matching on Events

MN: Chambers on Committee Event Participants

---

scrapers/ar/__init__.py

One resolution [posted](https://www.arkleg.state.ar.us/Bills/Detail?ddBienniumSession=2023%2F2024F&measureno=HR1003)! I'll take it!!

AR: 2024 Prefile Posted

---

scrapers/hi/bills.py

Just adding a chunk of the action text so I don't have to keep returning to this

HI: Vote Dedupe Again

---

scrapers/mn/bills.py

[HC 6](https://www.revisor.mn.gov/bills/bill.php?b=House&f=HC0006&ssn=0&y=2024) has a link to a "No document found" page

MN: add exception if there's no current version

---

scrapers/tn/bills.py

This information already comes in on the bill relationship

TN: remove companion bill actions/sponsors

---

scrapers/il/bills.py

Reverts openstates/openstates-scrapers#4914

Revert "IL: add votes back"

---

scrapers/tn/bills.py

Chamber doesn't actually work, so have to split up the Vote text & check that the bill id on the vote matches the bill.identifier of the current bill

TN: only scrape votes for current bill

---

scrapers/il/bills.py

[#1185](https://github.com/openstates/issues/issues/1185)

IL: Vote Scraper Fragility

---

scrapers/ne/bills.py

Reverts openstates/openstates-scrapers#4923, they already fixed the links!

Revert "NE: skip bad bills"

---

scrapers/il/bills.py

Actions haven't been updating since we added it back, gonna make sure it's not the real culprit (may be bobsled or realtime issue in aws)

IL: temp remove votes

---

scrapers/nj/bills.py

Was just pointing at the wrong url

NJ: Fix Vote URL

---

scrapers/il/bills.py

Reverts openstates/openstates-scrapers#4925

Revert "IL: temp remove votes"

---

scrapers/ga/bills.py

Caption wasn't specific enough, should pull in the chamber vote number instead.

GA: update Vote text to description

---

scrapers/ks/votes.py

Relationships aren't matching, so trying to get the bill id split up to help

KS: update bill identifiers on Votes

---

scrapers/ca/download.py

Looks like they swapped the date format on the downloads site

CA: update date format on downloads

---

scrapers/vt/events.py

Had a few duplicates failing on import that do have different urls so should fix

VT: add source url as dedupe key to Events

---

scrapers/dc/events.py

Slightly different format on some Event pages

DC: check different header for events

---

scrapers/vt/events.py

Some events have the same link

VT: dedupe key on Events attempt 2

---

scrapers/va/__init__.py
scrapers/va/common.py
scrapers/va/csv_bills.py

Session starts Monday but no bills file is on the site yet so holding off merging until that's live

VA: set special session live

---

scrapers/va/events.py

Having an issue scraping lower because there are 2 slightly different meetings on the same day

VA: add dedupe_key to lower Events

---

scrapers/ok/__init__.py
scrapers/ok/bills.py

No bills posted yet that i can see. @NewAgeAirbender feel free to merge if you catch bills before we do.

OK: 2024S4

---

scrapers/ar/__init__.py

AR: 2nd special 2024

---

scrapers/ut/__init__.py

UT: 2024 3rd special

---

scrapers/ma/bills.py

Just making sure it's clear if it's a bill or docket/proposed bill

MA: add proposed bill classification option

---

poetry.lock
pyproject.toml

Bumping up to sync with schema/model changes in latest version.

Upgrade openstates-core dependency to 6.19.3

---

scrapers/usa/votes.py

Scrape is failing since this phrase isn't in the senate options

USA: add senate vote status phrase

---

scrapers/ok/__init__.py

When they post bills & keep em there

OK: Special 4 True

---

scrapers/ar/bills.py

AR: Bills: fixes for new FTP

---

scrapers/nm/__init__.py
scrapers/nm/bills.py

Wait until they post some data to merge.

NM: 2024S1

---

scrapers/oh/__init__.py

Added a bunch of past sessions to the options

OH: ignore previous sessions

---

scrapers/ne/__init__.py

Wait for the state to post data to QA/merge.

NE: add 2024S1

---

scrapers/ma/__init__.py
scrapers/ma/votes.py

Senate votes scraper is written.
House votes scraper is somewhat built out, but most votes recorded in journals are in the Senate Journals, so that has taken priority to ensure we get most MA vote data in as soon as possible.

MA: new votes scraper

---

scrapers/fl/events.py

[issue #1212](https://github.com/openstates/issues/issues/1212)

1212: FL scrape senate event agenda pdfs for bills

---

scrapers/ny/events.py

Just need to update detail pages' `get` request

NY: get detail pages

---

scrapers/sd/events.py

- [issues 1214](https://github.com/openstates/issues/issues/1214)
- add room to the current location.
- switch the location to that, if API provides a building name

SD: Add room to location

---

scrapers/usa/bills.py

There's [a bill](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s4869.xml) with a bunch of new (or incorrect) data input so this adds more to cases to parsing actions

USA: avoid errors for 118-S4869

---

scrapers/wa/events.py

- [1223](https://github.com/openstates/issues/issues/1223)

WA: Tweak EmptyScrape Exception on Events

---

scrapers/ut/__init__.py

UT: init special session

---

scrapers/ut/__init__.py

UT: set special session live

---

scrapers/in/bills.py

Had a funky subject causing issues, also updates the urls in a few spots

IN: Shorten Long Bill Subject & Update to HTTPS

---

scrapers/ca/__init__.py

Sneaky special session, also fixes name format on previous special

CA: add special session

---

scrapers/ak/__init__.py

Got what I wanted out of this, so put the right date now

AK: fix end_date

---

scrapers/az/__init__.py

Added the session but don't think bills will be posted until later this year

AZ: set 2025 inactive so far

---

scrapers/wv/__init__.py
scrapers/wv/bills.py

WV: Skip cert verify until they update their ssl cert

---

scrapers/wy/bills.py
scrapers/wy/committees.py
scrapers/wy/events.py

[1226](https://github.com/openstates/issues/issues/1226)

WY: New Site Scraper

---

scrapers/ar/bills.py

[1231](https://github.com/openstates/issues/issues/1231)

AR: Split Sponsors by Entity Type & Chamber

---

poetry.lock
pyproject.toml

Bump openstates to 6.20.6

---

scrapers/ak/bills.py

- issue [1232](https://github.com/openstates/issues/issues/1232)
- split sponsorship by chamber
- fix the conference_committee_list_url issue

AK: Split Sponsorship by Chamber

---

scrapers/al/bills.py
scrapers/al/events.py

Gets the bills scraper working again (including back data) and events scraper.

AL: fixes for new site

---

scrapers/la/__init__.py
scrapers/la/bills.py

Don't actually have solid dates for this but it seems like it's happening:
- [Listed on website](https://www.legis.la.gov/legis/BillSearch.aspx?sid=243ES) (no bills yet)
- [Some reportage](https://www.usnews.com/news/us/articles/2024-10-01/louisiana-governor-plans-to-call-third-special-session-to-overhaul-the-states-tax-system)

LA: add third extraordinary session slated for November

---

scrapers/pa/events.py
scrapers/pa/utils.py

Updated the PA events scraper to use the new https://www.palegis.us/ website.
Addresses https://github.com/openstates/issues/issues/1239

New PA Events Scraper

---

scrapers/pa/bills.py
scrapers/pa/events.py
scrapers/pa/utils.py

Added bills and events scrapers for PA
- [1238](https://github.com/openstates/issues/issues/1238)
- [1239](https://github.com/openstates/issues/issues/1239)

PA: bills and events scraper rewrite 2025

---

scrapers/nd/bills.py

[1242](https://github.com/openstates/issues/issues/1242)

ND: add votes scraping to bills scraper

---

scrapers/pa/__init__.py
scrapers/pa/bills.py
scrapers/pa/utils.py

issue [1238](https://github.com/openstates/issues/issues/1238)

PA: Date and URL issue

---

scrapers/in/__init__.py
scrapers/in/apiclient.py
scrapers/in/bills.py
scrapers/in/committees.py
scrapers/in/events.py
scrapers/in/utils.py

- Fix the text format issue in vote pdf scraping
- [1240](https://github.com/openstates/issues/issues/1240)
- [1207](https://github.com/openstates/issues/issues/1207)

IN: bills and events scraper rewrite 2025

---

scrapers/in/bills.py
scrapers/in/events.py

- add the exhibit and minute urls
- remove the proxy-based urls

IN: fix event exhibits and minutes url

---

scrapers/tx/__init__.py

Also marks last two special sessions as inactive

TX: enable 2025 regular session 89

---

scrapers/va/bills.py

[1259](https://github.com/openstates/issues/issues/1259)

VA Bills: bill identifier is None error

---

scrapers/mn/bills.py

Scrapes consistently failing for a few days on fetching HTML text of Senate resolutions, errors like:
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1318032-www.senate.mn.senate.mn', port=443): Max retries exceeded with url: /resolutions/display_resolution.php?ls=93&bill_type=SC&bill_number=9&ss_number=0&ss_year=2024 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5de9e2400>: Failed to establish a new connection: [Errno -2] Name or service not known'))

MN: avoid Senate server weird HTTP errors by url rewrite

---

scrapers/wa/__init__.py

setting 2025 session to active now that prefiles are up

WA: enable 2025 session

---

scrapers/mt/events.py

weirdly the content from the "Other" events seemed to be actual livestream of a real hearing, so decided to keep them

MT: events: fix more duplicates and ignore test event

---

scrapers/oh/__init__.py

Looks like they updated the session listing on the search page

OH: update session name

---

scrapers/nv/bills.py

It seems new session using `Assemblymember` instead of `Assemblyman` or `Assemblywoman`.
CC @jessemortenson

NV: Add Assemblymember as possible sponsor title

---

scrapers/ar/bills.py

[1276](https://github.com/openstates/issues/issues/1276)

AR bills scraper missing bills

---

scrapers/mn/__init__.py
scrapers/mn/bills.py

NOTE: this needs more work to add pagination past 500 bills, shouldn't be too hard just in a hurry. Will file todo bug as well.

MN: 2025 prefiles

---

scrapers/mn/__init__.py
scrapers/mn/bills.py

Reverts openstates/openstates-scrapers#5158
Turns out the bills posted were test bills.

Revert "MN: 2025 prefiles"

---

scrapers/ma/__init__.py
scrapers/nm/__init__.py

MA is live, NM is live on the website but not the bulk data yet. Hopefully it will have posted by the morning.

MA, NM 2025

---

scrapers/ar/bills.py

Should fix this error I'm currently seeing:
```
[2025-01-03, 22:36:08 UTC] {pod_manager.py:472} INFO - [base] Traceback (most recent call last):
[2025-01-03, 22:36:08 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>
[2025-01-03, 22:36:08 UTC] {pod_manager.py:472} INFO - [base]     sys.exit(main())
[2025-01-03, 22:36:08 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 601, in main
[2025-01-03, 22:36:08 UTC] {pod_manager.py:472} INFO - [base]     report = do_update(args, other, juris)
[2025-01-03, 22:36:08 UTC] {pod_manager.py:472} INFO - [base]   File …
```

AR: fix another textfile decoding issue

---

scrapers/ne/__init__.py

NE: add 2025 session as inactive

---

scrapers/pr/__init__.py
scrapers/pr/bills.py

[1283](https://github.com/openstates/issues/issues/1283)

PR bill scraper rewrite

---

scrapers/pr/bills.py

PR: fix truncated alphabetical part of bill identifiers

---

scrapers/mt/bills.py
scrapers/ne/events.py

MT: Added a vote scraper 
NE: Skip event agendas that are blank
Apologies for the double unrelated items in one commit, short on time.

MT: Scrape Votes, NE: Events fix

---

scrapers/al/bills.py

Haven't found replacements for all of them, so may need to revisit vote processing later. Left those commented out within the queries so we see what was removed.

AL: fix API bug, removing changed/removed properties from GraphQL query

---

scrapers/va/bills.py

Error is
```
[2025-01-22, 08:37:59 UTC] {pod_manager.py:472} INFO - [base] Traceback (most recent call last):
[2025-01-22, 08:37:59 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>
[2025-01-22, 08:37:59 UTC] {pod_manager.py:472} INFO - [base]     sys.exit(main())
[2025-01-22, 08:37:59 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 601, in main
[2025-01-22, 08:37:59 UTC] {pod_manager.py:472} INFO - [base]     report = do_update(args, other, juris)
[2025-01-22, 08:37:59 UTC] {pod_manager.py:472} INFO - [base]   File …
```

VA: attempt to fix TypeError on unexpected votes value

---

scrapers/ms/events.py

[1290](https://github.com/openstates/issues/issues/1290)

MS Events update and improvement for 2025

---

scrapers/ca/events_web.py

[1291](https://github.com/openstates/issues/issues/1291)

CA events Senate site seems to need rewrite

---

scrapers/mt/bills.py

CC: @jessemortenson Grab committee name  where applicable in Montana actions. This will display like this in `action.description`

MT: Add committee info to actions

---

scrapers/pr/__init__.py

It looks like this values will keep changing and causing failing

Change next-action for request headers

---

scrapers/ma/__init__.py

CC: @jessemortenson  Came up with this fallback for now.

MA: Fall back to temporarily hardcore session list

---

scrapers/ca/bills.py

I am not sure if this CA fix was updated in the docker image, so making an update again

CA: updates

---

scrapers/ut/bills.py

We had some bad URLs in Utah where we were adding the the https://le.utah.gov to already absolute urls.
Running a test scrape now before merge.

UT: url fixes, and action classification

---

scrapers/usa/bills.py

See comment in code for context

USA: add flag to omit hearings/events scrape from within bills scraper

---

scrapers/ia/votes.py

CC: @jessemortenson. Dropping this for visibility. I am not sure if this change will break something else.

Line might contain "adopted" and still mean "lost"

---

scrapers/va/events.py

This should probably get fixed in core logic to not kill the scrape in this situation. But VA events scraper does also have a billion paths to add an event document, so maybe it's fine.

VA: events: fix duplicate document validation bug

---

scrapers/usa/events.py

prior xpath was getting all associated docs from all meetings, instead of just the meeting it was supposed to look at

USA: events: fix senate over-associating bills with events

---

scrapers/ut/bills.py

some bills have times and some do not
for example https://le.utah.gov/~2025/bills/static/HB0017.html has times
and https://le.utah.gov/~2025/bills/static/HB0049.html does not

UT: bills: support bill action datetimes,

---

scrapers/ct/votes.py

The example document is amusing...

CT: votes: handle unxpected PDF with error in its content

---

scrapers/dc/events.py

Example:
https://lims.dccouncil.gov/Hearings/hearings/699
https://lims.dccouncil.gov/Hearings/hearings/737
The two seem identical but there is different contextual information on each page, sigh

DC: events: handle semi-duplicate event (collision on time+title)

---

scrapers/hi/bills.py

Additional Regex to catch more use case for HI vote. It is better to have new regex handle new edge case in order to cause breaking changes.

Add regex for vote matching

---

scrapers/pr/bills.py

see https://sutra.oslpr.org/medidas/153232 "Ley 1-2025" in the Eventos list

PR: bills: handle a weird/outlier strucuture around a bill action

---

scrapers/mt/bills.py

Added "NO_BY_PROXY", "YES_BY_PROXY" to votes validation

MT: Update votes validation

---

scrapers/ms/events.py

Not sure why we would only be checking for the class to match on a specific elem, vs the elem we are examining in the loop !!!

MS: events: fix parsing issue for house events

---

scrapers/fl/events.py

Code was grab all bills for considerations for all page instead for just the event row.

Fix more bug

---

poetry.lock
pyproject.toml
scrapers/az/bills.py
scripts/log_external_ip.py

Update action classification to include a new `informal-passage` for AZ. See changes in [openstates-core](https://github.com/openstates/openstates-core/pull/172)

AZ: add informal passage

---

scrapers/ct/bills.py

For reasons that I think might be accidental, the CT scraper was yielding every bill, then going back and adding bill actions, and then yielding it again. This refactors it to scrape all the actions first then yield.

CT: only yield each bill once

---

poetry.lock
pyproject.toml

Reverts openstates/openstates-scrapers#5372. There is a validation bug I didn't account for.

Revert "Bump Openstates version"

---

scrapers/mi/bills.py

This PR is for a scraper to extract vote history for Michigan bills. It provides functionality to track voting actions and other relevant metadata for bills in Michigan, which enhances the data collection for legislative processes.

Add vote scraper for Michigan bills

---

scrapers/mt/bills.py

Ran locally, seems to produce similar distribution of upper v lower classifications

MT: bill votes: seems like API structure changed, adjusting to get chamber

---

scrapers/mn/vote_events.py

There are no votes there yet, but URL is up

MN: votes: add URL for 2025 special session 1

---

scrapers/usa/bills.py

We're seeing some weird behavior in a cloud context, so just want to temporarily have this in here to debug.

USA: bills: add some code to print XML for debugging

---

scrapers/tx/__init__.py

Session is over, should allow speedier ingestion of special session that is open

TX: deactivate regular session 89R

---

scrapers/nv/bills.py

NV: bills: support multiple URL formats for subject index page

---

scrapers/tx/votes.py

Also added logic that starts checking later in the calendar (based on session start date) instead of starting on Jan 1.

TX: votes: fix URLs for special session journal pages

---

scrapers/wa/bills.py

WA site has been mildly redesigned. Prefiles URL is not loading, even when I click through the site's nav. So I think we'll see more fluctuation. But it didn't seem super hard to get this working again for the time being.

WA: bills: adjust to site redesign

---

scrapers/ca/bills.py

apparently ALSO need to catch RuntimeError with StopIteration error

CA: bills iteration error part 2

---

scrapers/or/bills.py

Adding improvement for bill documents

OR: Imporove bill documents
