- scrapers/id/bills.py
Found that ID URLs were all redirecting to HTTPS, so wanted to make the change to match. Ran locally, seemed to work fine.
> ID: Switch URLs to HTTPS to match source website behavior

- scrapers/sd/bills.py
Treating action.Result value of 'N' as failure, previously [was not accounted for](https://bobsled.openstates.org/run/eaf8412a90a049cb92473b9a21323456). In that case, the SD website is [ambiguous](https://sdlegislature.gov/Session/Bill/22026) however the [linked committee log pdf seems to indicate failure with the text "died for lack of second"](https://mylrc.sdlegislature.gov/api/Documents/212399.pdf#page=1). 
Also turning Null into an empty string which popped up [here](https://sdlegislature.gov/api/Bills/ActionLog/22168)
> SD: Fix action parsing bugs

- scrapers/ga/bills.py
https://www.legis.ga.gov/members/senate
Sheila McNeill currently causes the API to blow up, and even her member profile page on the site is broken. 
Skip over her for now when she's a (co)sponsor, and hopefully we can fix it later.
> GA: Skip member whose profile crashes the api

- scrapers/ms/bills.py
MS published http://billstatus.ls.state.ms.us/2021/pdf/history/SN/SN0049.xml which has no title (short or long) yet, so skip it for now so the scraper doesn't bomb out.
> MS: Skip bills with no titles

- scrapers/md/events.py
An event with "10:00am to 11:00am" was breaking dateutil.parser
> MD: Events fix event with end date

- scrapers/sd/bills.py
Looks like SD changed the Votes document in the API to no longer place certain properties behind an 'x' property
> SD: Fix error on vote document properties

- scrapers/az/bills.py
Caused failed run due to validation error on empty subject string: https://bobsled.openstates.org/run/c88602285b36493499b8a9f3bbaa0a41
> AZ: fix empty subject name bug

- scrapers/sd/bills.py
Fix when SD leaves assignedcommittee null, and change 'chambers' to 'chamber' in scraper args to match other scrapers.
> SD: check for assignedcommittee in action, normalize chamber arg

- scrapers/ga/bills.py
Source URLs of the old format `http://www.legis.ga.gov/Legislation/en-US/display/{session}/{internalBillId}` are now going to 404 error pages. Fix to match the URL format used by the new GA site.
> GA: Fix source bill URL to match GA current website

- scrapers/nh/bills.py
NH was missing sponsors with 4 digit state specific person IDs, because they started zero-padding them in one data file but not in another.
> NH: Fix for missing sponsors

- scrapers/hi/bills.py
https://www.capitol.hawaii.gov/report.aspx?type=HR&year=2021
is failing on the state side due to an error, so skip HRs.
https://github.com/openstates/issues/issues/357
> HI: Disable scraping HRs for now

- scrapers/mi/bills.py
In MI, we're classifying the action chambers (actors) via a reference to the chamber's journal page, which appears next to the action on the website. (HJ vs SJ).
Lately, they've been posting actions with 'Expected Soon' as the journal cite, then adding it later. This causes us to incorrectly classify the action due to an overly loose else clause.
**edit** looks like we can fall back to using the casing, because house lowercases and senate uppercases. Yuck.
@jamesturk until they post the reference, we may not know the chamber. Will it cause the OS ingestion any problems if we save those actors as 'legislature', then it gets updated on subsequent scrapes?
Here's a screenshot of what i'm talking about, to help clarify:
https://www.dropbox.com/s/itzv7ru8s3ku3kr/Screenshot_2021-03-24-17%3A06.pn …
> MI: fix some actor classification errors

- scrapers/ar/bills.py
Seems a website update removed the screenreader class for most bill pages, which the page scraper relies on for searching for vote links. I changed the xpaths to point to the divs in the grid role instead.
> AR: fixed vote event scraper after website update removed screenreader class

- scrapers/ar/bills.py
I noticed that bill actions were only scraping dates, making it difficult to chronologically sort actions that occurred the same day. This change allows time of day to be scraped as well.
> AR: Scrape date and time of day for bill actions

- scrapers/hi/events.py
HI events were linking to individual versions instead of clean bill ids.
> HI: Events: fix links to bill versions instead of bills

- scrapers/fl/bills.py
FL was improperly parsing suffixed names into multiple sponsors, ie "Aloupis, Jr." became two sponsors -- "Aloupis",  and "Jr." 
Catch "Sr." and "Jr." and add them to the name normally.
https://openstates.org/fl/bills/2021/HB1351/
> FL: Properly replace jr/sr in bill sponsors

- scrapers/ar/people.py
Previous address scraper change based on splitting the string on commas was causing some addresses with more than two commas to break. This change will allow "AR" to be inserted near the end of the string before the zipcode.
> AR: fix address scraper

- scrapers/il/__init__.py
- scrapers/il/bills.py
- scrapers/il/events.py
- scrapers/il/people.py
Illinois is using HTTPS consistently now, so might as well update URLs.
> IL: Switch URLs to HTTPS

- scrapers/mn/vote_events.py
Looks like Minnesota didn't have vote urls for the 2020 Second Special Sesssion to the 2021-2022 Regular session. I added them, but the special sessions between 2 and 7 will need to be scraped as well.
> MN: add vote urls for 2020 special sessions and 2021 regular session

- scrapers/pr/__init__.py
- scrapers/pr/votes.py
[openstates/issues/issues/391](https://github.com/openstates/issues/issues/391)
This is currently working locally with all available data from the PR Senate at: https://www.senado.pr.gov/Pages/VotacionMedidas.aspx
All tests I ran produced the correct bill identifiers and vote totals per bill as scraped by the PR bills scraper. 
Some concerns:
- Motion Text is not included in this data; not sure if this will mess up matching
- 1 ambiguous, unhandled result at: https://www.senado.pr.gov/Planes%20de%20Reorganizacion/20210315.pdf (page 4). Unclear what "Recibido" result indicates. For now skips this one (and all future measures with this type)
- Sets "chamber" and "session" to "upper" and "2021-2024" every call; required as this is the only voting data currently available
> PR: Votes: Initial Scraper for Senate Votes

- scrapers/wa/bills.py
WA's actions API doesn't provide actors, so we had the chambers wrong on a large number of actions. This patch fixes it by pulling from the website instead.
@jessemortenson @jamesturk just a head's up this will likely invalidate the cache on many WA bills.
https://github.com/openstates/issues/issues/406
> WA: pull actions from webpage instead of API

- scrapers/or/votes.py
Looks like there was one more classifier still using this no-longer-supported classification `failure`
re: https://github.com/openstates/issues/issues/409
> OR: fix bad vote classification (failure)

- scrapers/al/people.py
- scrapers/az/bills.py
- scrapers/co/committees.py
- scrapers/ga/events.py
- scrapers/in/apiclient.py
- scrapers/mo/bills.py
- scrapers/mt/bills.py
- scrapers/nc/bills.py
- scrapers/nd/votes.py
- scrapers/nm/bills.py
- scrapers/ny/apiclient.py
- scrapers/oh/bills.py
- scrapers/pr/bills.py
- scrapers/sd/events.py
There are small typos in:
- scrapers/al/people.py
- scrapers/az/bills.py
- scrapers/co/committees.py
- scrapers/ga/events.py
- scrapers/in/apiclient.py
- scrapers/mo/bills.py
- scrapers/mt/bills.py
- scrapers/nc/bills.py
- scrapers/nd/votes.py
- scrapers/nm/bills.py
- scrapers/ny/apiclient.py
- scrapers/oh/bills.py
- scrapers/pr/bills.py
- scrapers/sd/events.py
Fixes:
- Should read `available` rather than `avaible`.
- Should read `whitespace` rather than `whitepace`.
- Should read `their` rather than `thier`.
- Should read `separately` rather than `seperately`.
- Should read `recommendations` rather than `recomendations`.
- Should read `presumably` rather than `presumanbly`.
- Should read `milliseconds` rather than `miliseconds`.
- Should read `information` rather than `informaiton`.
- …
> docs: fix a few simple typos

- scrapers/nv/bills.py
NV was missing some action classifications, because we were only looking for matches at the start of the action string, instead of anywhere in it, and doing so case sensitively.
> NV: Classify actions by search instead of match

- scrapers/ct/bills.py
The CT legislature publishes "public act" documents for bills that have passed both houses, even if they haven't become law (yet).
We were incorrectly categorizing all bills with public acts as having become law.
Quote from our researcher:
"here is the exact process from CT site: A bill becomes a public act when it passes both chambers of the General Assembly. The act is then assigned a public act number, with the first number indicating the year of enactment (e.g., PA 11-250 was enacted in 2011). Note that a public act does not actually become law until the governor has signed it, or it can become law if the governor takes no action (i.e., does not veto the public act)."
> CT: Remove errant bill classification

- scrapers/ct/bills.py
CT was missing final acts due to a too-specific selector.
> CT: widen bill version xpath

- scrapers/az/__init__.py
Re-orders sessions so regular session will be scraped again. [HR 2017](https://apps.azleg.gov/BillStatus/BillOverview/76200?SessionId=123) is missing from [Open States data](https://openstates.org/search/?query=HR+2017&state=az).
(@jamesturk is this still the preferred way to handle this - vs. changing the task definition to specify the regular session?)
> AZ: resume scraping regular session to catch missing HR 2017

- scrapers_next/ny/committees.py
this one has more try-except blocks than the others, possibly because of strange data (the strangest part is probably that House subcommittees don't have committee parents and only chair(s) but no members).
- I kind of hard-coded the "members" role and the "address", so let me know if this is not okay!
- also, when running SenateCommitteeList, there's a timeout error, but adding `--fastmode --rpm 10` has always worked
- just added homepage links!
> NY committee spatula scrape

- scrapers/ri/bills.py
We were getting the actor wrong on many RI senate actions, so mark them as "upper" instead of "legislature"
> RI: Fix some senate action classes

- scrapers/ny/apiclient.py
Fixes https://github.com/openstates/issues/issues/455
NY scrape started failing yesterday due to `ModuleNotFoundError: No module named 'OpenSSL'` - seems like this must have been an implicit dependency imported by some other package. Poked around a bit to find a recent change that would explain it but didn't find it. 
This disables retry handling on NY API calls as a quick temporary fix. Hopefully when @jamesturk is back he will know about the root issue :)
> NY: Temporary fix for missing OpenSSL library error

- scrapers_next/mn/committees.py
subcommittees have chambers and parents, while committees only have chambers
House committee list also includes 1 subcommittee, but it doesn't have a parent, so didn't make the change there ([Subcommittee on Legislative Process Reform](https://www.house.leg.state.mn.us/committees))
- This is also the case for [NY House subcommittees](https://assembly.state.ny.us/comm/)
> ScrapeCommittee update: updated parent to chamber and added chamber to subcommittees

- scrapers_next/ga/committees.py
Note that GA does not have any joint or sub committees listed. This scraper does not scrape the "House Special & Study Committees" page. @jamesturk
> updated lines that used com.parent to com.chamber as per ScrapeCommittee update

- scrapers/la/__init__.py
Ignore 2021 Veto Session since it has no bills posted.
> LA: update ignored session

- scrapers_next/il/people.py
Re-writing the IL people scraper to use spatula framework. Currently scraping 59 Senators and 118 Representatives. Skipping over "Former Senate Members". process_addrs() handles pages with varying number of capitol/district address lines.
10 senators and 5 representatives have a link to a new page with "Additional District Addresses". I tried to write a class to capture these additional addresses, but could not get it to work. 
example: https://ilga.gov/house/Rep.asp?GA=102&MemberID=2879
@jamesturk
> Il spatula people

- scrapers_next/co/people.py
Writing Colorado people scraper using spatula framework. All Senators and Representatives have 200 E Colfax RM 307 Denver, CO 80203 or 200 E Colfax RM 346 Denver, CO 80203 or 200 E Colfax RM 272 Denver, CO 80203 as their 'mailing address'. I am currently assigning this to their capitol office address (see line 33). There are no district office addresses listed. 
This clean branch has the updated il directory from the main branch.
@jamesturk
> Co people spatula clean

- scrapers_next/id/people.py
Converting ID people scraper to use spatula framework. Some things to note:
1. There are no capitol addresses listed. Only district addresses.
2. 'Home', 'Statehouse', and 'Bus' phones are listed. At the moment, I am assigning 'Home' as district_office.voice, 'Statehouse' as captiol_office.voice. I am not grabbing 'Bus' phones but can if needed.
3. Individuals to not have homepages. They have links to their district site (ex: https://legislature.idaho.gov/legislators/membership/?yr=2021&district=13).
@jamesturk
> Id people spatula

- scrapers_next/ct/people.py
- the old scraper listed the reps' home address as their district office address so I did the same, but wanted to check if this was still okay
- listed the committees each rep is on only as extra information, not as an Organization object like the old scraper
- I've never used `assert` for the scrapers but just included the line because the old version had it
- I usually do some sort of party checking, but figured that this is already done during scraper, but wanted to make sure this is the case!
- apologies for the few commits, will commit more often next time!
> CT people spatula scrape

- scrapers/ky/__init__.py
This adds the prefiles, but doesn't set them as the default session because the scraper will fail.
@jamesturk heads up if you want to grab these, add a task that scrapes with `session=2022RS prefiles=True`
> KY: Add 2022 prefiles

- scrapers/tx/bills.py
With some of the special session bills, new lines got pulled in as names since they weren't just empty strings. Done some test scrapes and the rest of the bills look okay, feel like the logic could be prettier so happy to take critiques.
> TX: check names for spaces or newlines

- scrapers/nd/__init__.py
Scraper failing from new session being listed in the general assembly page even though no bills are prefiled yet.
> ND: ignore 2023 session

- scrapers_next/mi/committees.py
I think there's only one [subcommittee list page](https://www.house.mi.gov/MHRPublic/SubCommittee.aspx?comcode=APPR), but it only sometimes loads, even from just the browser. I'm not sure how to approach scraping subcommittee list pages in general--first I tried to scrape from within HouseCommitteeDetail, and then I decided to try a separate HouseSubcommitteeList (but got stuck when the web page just seemed faulty).
Other than that, the links Iisted on each committee page (here's an [example](https://www.house.mi.gov/MHRPublic/CommitteeInfo.aspx?comcode=AGRI) for the links, "Click here to subscribe" and "All Currently Scheduled Committee Meetings") aren't super relevant to that committee in particular, but I included them in the scraper just in case.
> MI committee spatula scrape

- scrapers_next/az/committees.py
AZ committee scraper conversion to spatula!
- Unsure of where to get the session id, so that was hardcoded :(
- All the members of the committee are repeated twice, so to be extra safe, I checked each member against a list of previously added member names with their positions, before adding it as a new member in the scrape. It's not foolproof because two members can have the same name and same positions (probably "member").
- I only scraped the standing committees for House and Senate, and I think the old scraper did too. There's no documentation on the Arizona API, but there are a lot of committees listed [here](https://apps.azleg.gov/api/Committee), most of which probably are not active currently?
- I wasn't able to add a "homepage" link, I guess the closest would be this: …
> AZ committee spatula scrape

- scrapers/usa/bills.py
Scraper is [failing due to a 503 error](https://github.com/openstates/issues/issues/482), this addition just skips that bill for now and we can come back to it later.
> USA: skip S 164

- scrapers_next/id/committees.py
Writing ID committee scraper using spatula framework. Notes:
1. The following Joint Committee has broken html. Not able to grab member names/info. Just returning ScrapeCommittee() object with name, chamber, sources, and link. https://legislature.idaho.gov/sessioninfo/2021/joint/cec/
2. These links have 'Ad Hoc' in names:
https://legislature.idaho.gov/lso/bpa/eora/ (ex: "Sen. Peter Riggs – Ad Hoc")
https://legislature.idaho.gov/sessioninfo/2021/standingcommittees/HETH/
@jamesturk
> Id committee spatula

- scrapers_next/nh/people.py
Writing NH people scraper using spatula framework. Notes:
1. This scraper uses a .txt file as the source and CsvListPage for the Legislators() class. .txt file is actually tab separated instead of a comma separated file.
2. Addresses/phones from the .txt file are not labeled as capitol or district. I am assigning them to additional_offices with contact_type='Primary Office'. Could alternatively assign to district_office.address/voice.
3. The old code did a number of steps to get a detail page for representatives. It used a lookup_url to get some sort of 'seat_map'. seat_map maps 'seatno' (from.txt) to 'seat_number'. 'seat_number' is then inserted into house_profile_url. I could not get this to work for me, but maybe someone else can figure it out. Without this, we are missing detail pages …
> Nh people spatula

- scrapers/ne/__init__.py
- scrapers/ne/bills.py
NE Special is dumping all the data into the main search results, with duplicates of the same bill number. 
This changes the code to scrape specials based on intro date. If they end up filing additional bills after session start, this code may need mods to scrape the entire range of days.
> NE: Scrape special differently

- scrapers_next/ma/people.py
I’ve only run into a timeout error once, but other times --rpm 10 works.
Other things to note:
* this version doesn’t include anything from district offices (address, phone, fax), but only info from capitol offices
* state building address and image links are mostly hard-coded
* I didn’t add any additional links just because those would be mostly hard-coded as well, and couldn’t guarantee that they were on every legislator page (like “Bills” and “Committees”, etc. here)
sorry for the lack of commits, I was trying to get this done before the end of the day!!
> MA people API spatula scrape

- scrapers_next/wy/people.py
Writing WY people scraper using spatula library. Notes:
1. I assumed item["phone"] is a district office phone. There is a field 'phoneType' ('Cell', 'Home', or 'Work'). Should I assign 'Work' as district office phone and the others as extras? Only 5 out of 90 phones are labeled 'Work'.
2. Note that "https://wyoleg.gov/LsoService/api/legislator/2021/(S|H)" and "https://wyoleg.gov/LsoService/api/legislator/{item['legID']}" are being added to sources while "http://wyoleg.gov/Legislators/2021/{item['party']}/{item['legID']}" is being added to links (homepage).
3. I assumed that self.data['address'] is a district office address.
4. No capitol office information available.
@jamesturk 
We did it! 52 jurisdictions now in spatula!!
> Wy people spatula

- scrapers/wv/events.py
Catches HB1234 which was being missed before due to missing periods after H and B.
> WV: Events: Catch additional bill references

- scrapers/ar/events.py
The AR Event source URL was changing on every scrape, lock it to the real url without args.
> AR: Stabilize event source url

- scrapers/de/events.py
- scrapers/id/events.py
- scrapers/me/events.py
- scrapers/mt/events.py
- scrapers/or/events.py
Raise EmptyScrape for event scrapers when there are no events scheduled, as opposed to the scrapers emitting no results due to an error.
> Enable EmptyScrape for Events scrapers

- scrapers_next/ak/committees.py
Writing AK committee scraper using spatula library. Notes:
1. There are 6 types of committees for AK: Standing Committees, Special Committees, Other Committees, Joint Committees, Finance Subcommittees, and Conference Committees. All classifications are 'committee' except for Finance Subcommittees. Hard coding the Finance Subcommittee parent as 'FINANCE (FIN)'.
2. Some committees do not have members listed (ex: http://www.akleg.gov/basis/Committee/Details/32?code=HPFG). Just returning their com objects without members.
3. Some committees have 'Public Members'. I am skipping over these members. ex: http://www.akleg.gov/basis/Committee/Details/32?code=SASC#tab1_7
@jamesturk
> Ak committee spatula

- scrapers/al/bills.py
AL has different url structure for 2021S1 bills, so just updates the version url to not be 404
Ex: 
http://alisondb.legislature.state.al.us/ALISON/SearchableInstruments/2021s1/PrintFiles/HR1-int.pdf should actually be
http://alisondb.legislature.state.al.us/ALISON/SearchableInstruments/2021FS/PrintFiles/HR1-int.pdf
> AL: correct session for version urls

- scrapers_next/ar/committees.py
Writing AR committee scraper using spatula library. Notes:
1. Just to give you an idea of the structure/outline of this code, there are 8 classes:
- HouseJointDetail() scrapes Joint Committee, Joint Subcommittee, House Committee, and House Subcommittee details.
- SenDetail() scrapes Senate Committee and Senate Subcommittee details.
- SenSubComms() scrapes Senate Subcommittees.
- SenList() scrapes Senate Committees.
- HouseSubComms() scrapes House Subcommittees.
- HouseList() scrapes House Committees.
- JointSubComms() scrapes Joint Subcommittees.
- Joint() scrapes Joint Committees.
There may be a way to combine the following classes as they have the same sources, but different selectors. I did not do this due to time constraints:
Joint() and JointSubComms() 
HouseList() and …
> Ar committee spatula

- scrapers/fl/__init__.py
New session starting [November 15th through 19th](https://www.flgov.com/2021/10/29/governor-ron-desantis-announces-date-of-special-session-to-protect-florida-jobs/)
> FL: ignore 2021B until bills posted

- scrapers/fl/__init__.py
- scrapers/fl/bills.py
openstates/issues#491
Prefiled bills are now being introduced for the Florida 2022 session. Added the 2022 session to the Florida scraper.
Source of the FL 2022 session dates:
https://www.myfloridahouse.gov/FileStores/Web/HouseContent/Approved/ClerksOffice/ImportantLegislativeDates.pdf
> FL: Added session for 2022 prefiled bills

- scrapers/ga/__init__.py
- scrapers/ga/bills.py
- scrapers/ga/util.py
Just flagging this one -- changing the source link for bills will blow away the cache for other sessions. 
Feel free to merge when ready, bills are filed.
@NewAgeAirbender @jamesturk
> GA: Add 2021s1 meta, fix broken source links

- scrapers/ga/bills.py
Special session links have been leading to a 404 page. Takes the version url from incorrect `http://www.legis.ga.gov/Legislation/2021EX/202712.pdf` and gives correct link `https://www.legis.ga.gov/api/legislation/document/2021EX/202712`
> GA: correct pdf links

- scrapers/md/__init__.py
Special session starting [Dec 6](https://www.marylandmatters.org/2021/07/23/legislative-leaders-eye-early-december-special-session-to-draw-congressional-map/)
> MD: ignore special session until bills posted

- scrapers/ar/bills.py
This is the only state where we store microseconds, and occasionally these seem to change in the API and break cache for no reason.
> AR: Remove microseconds from bill action dates

- scrapers/az/__init__.py
- scrapers/az/session_metadata.py
FYI @jamesturk @NewAgeAirbender  leaving 2021 active for now because they have issues technical corrections recently.
> AZ: Add 2022 prefiles

- scrapers/vt/__init__.py
New special session [starts monday](https://www.wcax.com/2021/11/16/special-session-begin-monday-municipal-mask-mandates/)
> VT: ignore special session for now

- scrapers/ar/__init__.py
Bills scheduled to [prefile 1-10-22](https://www.arkleg.state.ar.us/Bureau/Document?type=pdf&source=assembly%2F2021%2F2021R%2FDocuments&filename=BLR-JBC+2022+Important+Dates)
> AR: ignore 2022 until bills posted

- scrapers/sd/__init__.py
- scrapers/sd/bills.py
Scraper was failing because of null values on the location on the ActionLog part of the api, add a check for that and throw warning.
> SD: Vote Null Check

- scrapers/ks/__init__.py
2022 prefiles are being posted ([HB 2458](http://www.kslegislature.org/li/b2021_22/measures/hb2458/) for example), so adds back the regular session and removes active from special session.
> KS: add back regular session for carryover bills

- scrapers/hi/__init__.py
- scrapers/hi/bills.py
- scrapers/hi/committees.py
- scrapers/hi/events.py
HI has updated their site, causing SSL errors. Updates the base urls on all HI scrapers, but looks like the site has fixed hrefs for bill links, so popped a replace link on those. The committee scraper is fine since the links pulled from the page aren't fixed to a "www." url.
> HI: update urls to avoid SSLErrors

- scrapers/fl/__init__.py
- scrapers/fl/bills.py
So the scraper has been failing due to SSL errors like [this one](https://bobsled.openstates.org/run/fcb1cb8f3c164324a11068fd8b698684), so figured out how to get around it for the initial session list, but still getting the error on bill scrapes trying to hit `https://flsenate.gov/Session/Bills/2022?chamber=both`. Wasn't sure how to get around it using spatula, @jamesturk any thoughts?
Error text:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='flsenate.gov', port=443): Max retries exceeded with url: /Session/Bills/2022?chamber=both (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`
Also updating current sessions.
> FL: Avoid SSL Error

- scrapers/hi/__init__.py
2021 has a bunch of bills [carrying over into 2022](https://www.capitol.hawaii.gov/session2022/bills/) that have already been posted
> HI: capture 2022 bills

- scrapers/vt/__init__.py
Handful of bills posted for [2022 release](https://legislature.vermont.gov/bill/loadBillsReleased/2022/), spot checked scrape and looks like at least have correct sponsors & versions so far.
> VT: 2022 bills posted

- scrapers/az/bills.py
The session selector wasn't working, so the scraper always collected bill numbers from the latest session. This corrects a header to fix session selection and adds an assertion to verify the session ID.
> AZ: Fix session selector for bill list

- scrapers/wv/__init__.py
- scrapers/wv/bills.py
Has a [special session](https://www.wvlegislature.gov/legisdocs/2022/proclamations/1X_SESSION-1_2022.pdf) starting before the regular session with some bills posted already
> WV: add 2022 special session

- scrapers/nj/__init__.py
- scrapers/nj/bills.py
[2022 Bills are posted](https://www.njleg.state.nj.us/bill-search), adds new session and updates error expected when there isn't a vote at the url so the scrape doesn't fail.
> NJ: 2022 Session

- scrapers/nj/bills.py
Version urls got flipped slightly. Also saw an easy way to add pdf version links
> NJ: update version urls and add pdf options

- scrapers/az/bills.py
@NewAgeAirbender -- based on https://github.com/openstates/openstates-scrapers/commit/d393b0067725c27016adf054d02b08c65904d0b5 we might be ping-ponging on this change; right now with the main branch when I scrape AZ bills I'm getting the following:
```
09:57:00 INFO scrapelib: GET - 'https://apps.azleg.gov/api/Keyword/?billStatusId=76229'
Traceback (most recent call last):
<snip unimportant stuff>
File "/home/showerst/work/ocd/openstates-scrapers/scrapers/az/bills.py", line 133, in scrape_subjects
if subject["Name"] and len(subject["Name"]) > 0:
KeyError: 'Name'
````
Do you see the same? 
The API result looks like
```
<ArrayOfgetKeywords_Result xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/AZLeg.Data.POCO">
<getKeywords_Result> …
```
> AZ: fix key check in subject logic

- scrapers/tn/bills.py
Looks like they've got the links hard coded as http when they updated to https. Updates the version and amendment links.
> TN: update version links to https

- scrapers/in/__init__.py
- scrapers/in/apiclient.py
- scrapers/in/bills.py
Indiana has a few bills in the API that take multiple minutes to load, so up the timeouts so they clear.
> IN: Up timeouts for slower bills

- scrapers/ky/bills.py
Concurrent Resolutions were being mistyped because of an issue with the bill id regex.
> KY: fix bill type regex

- scrapers/mn/events.py
Was adding description instead of regexed bill ids to event, causing scraper issue.
> MN: add bill instead of description to event

- scrapers/mn/bills.py
There's an issue with resolutions versions not getting scraped if the year on the url is incorrect. Just adds an attempt to try the new year in the url, and another warning if it is legitimately bad.
> MN: add version fix for biannual if fail initially

- scrapers/va/csv_bills.py
® was causing issues and killing the scraper.
> VA: ignore decode issues for registered mark

- scrapers/ny/bills.py
If you scrape NY using the window argument (as opposed to the defaults), the API returns bills from previous sessions if they were recently updated for some reason. We were scraping those and accidentally marking them as current session. This resolves that issue.
> NY: Make sure scraping with window arg only returns current bills

- scrapers/usa/votes.py
US Vote Scraper was blowing up due to a new voting classification.
> US: Add live pair vote code

- scrapers/tn/bills.py
We had a case where TN scraped some old data but assumed it was in the newest session, presumably due to an issue with the state site posting old info to the current bill listing page. This should avoid that in the future.
> TN: Make session explicit when pulling bill listing

- scrapers/oh/bills.py
Wasn't scraping a bill since it didn't have a title. Also cleans up in case there are more, can just add the bill id to the array to check.
> OH: add SR 259 to title-less bills

- scrapers/mn/events.py
Event scraper was failing from [SSL errors](https://bobsled.openstates.org/run/8f6ea7ac9cae4434bc38ce80c37ea04d), avoiding verification for now.
> MN: skip verify for get on upper events

- scrapers/fl/__init__.py
- scrapers/fl/bills.py
- scrapers/la/__init__.py
Ignores both new sessions. FL has a redistricting session [coming April](https://www.heraldtribune.com/story/news/politics/state/2022/03/29/florida-special-session-coming-desantis-vetoes-congressional-boundaries-redistricting/7204709001/), prepped an addition to the scraper in case & will check in, and LA added a veto session so no new bills will be introduced.
> FL & LA: New Sessions

- scrapers_next/vt/people.py
[OS-566](https://github.com/openstates/issues/issues/642)
Made the fix for scraping for Terri Lynn Williams, and also caught another error where other representatives middle names were included twice in their full name.
> fix for terri lynn and also other reps middle names

- scrapers/va/csv_bills.py
VA has pdf versions available, can just add "+pdf" to the version url to get to it so adds that as a link for the bill version
> VA: add pdf option to versions

- scrapers/nh/bills.py
NH is starting on a bill that doesn't have a bill id assigned yet and it's breaking the scrape. Adds a check for the bill id being an empty string before continuing the scrape.
> NH: check that bill id exists before continuing

- scrapers/nj/utils.py
NJ updated their data dump url from a www. site to pub.
> NJ: Update bill source url

- scrapers/al/bills.py
Ran into a page with an empty character, so strips vote string and returns if it's an empty string for the page.
> AL: return on empty vote pages

- scrapers/nd/events.py
Add start time and location to events in ND.
@jamesturk @NewAgeAirbender this scrape has an unusual situation where the easiest path was to create Event objects and then update two attributes later in the code. 
`self.events[event_url].__setattr__("start_date", date)` feels sorta hacky, let me know if there's a better way update those objects after the fact. You can't subscript them after creation so we can't just say `event['start_date'] = date`
> ND: Events Enhancements

- scrapers/hi/bills.py
There's one bill that has the same action listed twice for both chambers, so checks for that specific bill, date, and checks description for some text.
> HI: Skip Double Actions on Specific Bill

- scrapers/ok/__init__.py
- scrapers/ok/bills.py
OK has a special session that [started yesterday](https://www.oklahoman.com/story/news/2022/05/18/stimulus-fund-arpa-spending-focus-of-oklahoma-legislature-special-session/9828952002/), scheduled through the 27th
> OK: Support Second Special Session

- scrapers/ok/__init__.py
- scrapers/ok/bills.py
OK has third special session starting the [13th](https://www.koco.com/article/oklahoma-kevin-stitt-2022-legislative-session/40118674), ignore for now.
> OK: prep for 3rd special and 2023 sessions

- scrapers/usa/votes.py
House has some votes that aren't related to bills so was killing the scraper in the validation step. Avoids those for now, will need to update for new session or maybe tweak logic to check for a linked bill on the rolls paged and skip if there isn't one.
> USA: skip adjournment or quorum votes

- scrapers_next/mi/people.py
There are a few house representatives that are posted to the site, but they don't have a link so the scraper would skip them. The regex would already capture their name, party, and district from the text in the same cell that the typical link gets pulled from, so just needed to capture that text to pass in.
> MI: update to pull reps without a link yet

- scrapers/az/bills.py
Should handle errors like the following:
```
Traceback (most recent call last):
File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>
sys.exit(main())
File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 361, in main
report = do_update(args, other, juris)
File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 248, in do_update
report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 106, in do_scrape
partial_report = …
```
> handle Nones for Ayes/Nays in action object for AZ

- scrapers_next/ny/people.py
Wiki updated the style for how they display [Assembly member's party association](https://en.wikipedia.org/wiki/New_York_State_Assembly), so this fixes that.
Has to skip first row of headers, but party is either a blue or red square, so pulls the style and declares party based on that color.
> NY: Fix Assembly Party Associations

- scrapers/in/__init__.py
Looks like they've changed the name of the special session and pushed back the start date from July 6th to the 25th
> IN: ignore renamed special session but update start date

- scrapers/id/__init__.py
- scrapers/nj/__init__.py
- scrapers/or/__init__.py
Idaho:
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2022
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2021
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2020
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2019
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2018
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2017
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2015
https://legislature.idaho.gov/sessioninfo/sessiondates/?yr=2014
New Jersey:
https://njpsa.org/update-from-the-nj-statehouse-for-the-week-of-january-10-2022/
https://www.njleg.state.nj.us/legislative-calendar
Oregon:
https://www.oregonlegislature.gov/calendar
https://www.opb.org/article/2021/06/26/oregon-lawmakers-conclude-2021-legislative-sess …
> ID, NJ, OR: Fix dates for several sessions

- scrapers/ca/__init__.py
Simple change, as per ﻿﻿﻿﻿the [Legislative Calendar](https://www.assembly.ca.gov/legislativedeadlines) the adjournment of the session happens on 2022-11-30 not 2021-12-31.
If there's a technical reason this should remain the same please let me know.
> Corrected end of California 2021-2022 session

- scrapers/nh/bills.py
```
14:24:38 INFO scrapelib: GET - 'http://www.gencourt.state.nh.us/bill_status/legacy/bs2016/bill_status.aspx?lsr=2317&sy=2022&txtsessionyear=2022'
14:24:38 WARNING openstates: HR16 missing version link
14:24:38 INFO scrapelib: GET - 'http://www.gencourt.state.nh.us/bill_status/legacy/bs2016/bill_status.aspx?lsr=2454&sy=2022&txtsessionyear=2022'
14:24:39 WARNING openstates: HR15 missing version link
14:24:39 INFO scrapelib: GET - 'http://www.gencourt.state.nh.us/bill_status/legacy/bs2016/bill_status.aspx?lsr=2570&sy=2022&txtsessionyear=2022'
14:24:40 WARNING openstates: HR17 missing version link
14:24:40 INFO scrapelib: GET - 'http://www.gencourt.state.nh.us/bill_status/legacy/bs2016/bill_status.aspx?lsr=2692&sy=2022&txtsessionyear=2022' …
```
> NH: handle empty version page

- scrapers/oh/bills.py
OH websites don't accept scrapelib's `User-Agent` header any more. Changing the header from `scrapelib 2.0.6 python-requests/2.28.1` to `curl/7.82.0` seems to work.
> Add header override for OH

- scrapers/ia/votes.py
Because the vote collector for IA used an iterator object, we could get in situations where the interator ran out of results before processing logic was "done". This PR should help cover that edge case (and also clean up/document some of the code in the IA votes scraper).
> IA votes fix

- scrapers_next/oh/people.py
The OH People Scraper was failing due to only accounting for Democrats and Republicans in the party dict. I have added an option for Independents to the dict that fixes the error. The scraper was failing on Rep Shayla Davis(I) who is an Independent   https://ohiohouse.gov/members/shayla-l-davis
> OH: People Scraper Fix: Added Independent to Party Dict

- scrapers/nc/bills.py
The search page we were using to get a list of bills doesn't work how it used to, but there's an [XML page](https://www.ncleg.gov/Legislation/Bills/FiledBillsFeed/2021/H) that gives us partial bill data split by chamber. We're able to pull more important info like id, type, and title from this page more reliably than the bill detail page we are scraping. 
There's also a funky bill (SB 712) that doesn't scrape the same as the others, which is repeated in the same 2021 session as SB 655 so we do get the bill data, but it is the cause of the new try...except blocks.
> NC: Bill Scraper Fix

- scrapers_next/nm/people.py
NM changed their site. They used to list a capitol phone, district phone, and home phone for each legislator. Now it just has Office phone and Home phone on the site. Scraper's process_page() was adjusted accordingly to stop seeking capitol_phone. The listed Office phone is being store as district_phone in the JSON data now.
> NM: remove capitol_phone retrieval and fix all_info indexing

- scrapers/tx/__init__.py
Scrapes are timing out, should drop for new 2023 session prep anyway.
> TX: drop number of active sessions

- scrapers_next/ga/people.py
People scraper was failing because a legislator's details page did not have their staff member's name hyperlinked with an email address. Consequently, without `href` tags, the list `info` created within `for` loop in `process_page` for that legislator was of length = 1, resulting in `IndexError` when attempting to retrieve a staff name at `info[3]` and a staff email using `info[2]`.
Fix adds conditional statement to check the length of list `info` before retrieving staff name and email, with appropriate indexes given for each situation. Scraper now runs successfully.
> GA: index error fix for collecting staff email

- scrapers_next/nc/people.py
Scraper was failing because process_page had not converted legislator's scraped email address from match object type to string type. Method `.text_content()` was added. Scraper now runs successfully without data validation error.
> NC: data validation fix on email attribute collected in process_page

- scrapers/mi/bills.py
The source site has been updated so theres one Primary sponsor at the top of the chunk, followed by the cosponsors. This checks for that district string to denote primary or not. [Example source bill](http://legislature.mi.gov/doc.aspx?2021-HB-4412)
> MI: Fix Primary Sponsor Logic

- scrapers/il/bills.py
`official_type` rarely actually contains "primary" now, so check the `spontype` instead.
> IL: Fix Primary Logic Check

- docker-compose.yml
- scripts/init-db.sh
add a health check to the compose db and wait for the db to be healthy before initializing
This also changes to using `docker compose` vs. `docker-compose`. Which means we're relying on the _actual_ docker binaries released by docker (docker desktop on Mac, docker-ce on Linux), where the `compose` plugin is available. Not tested with `podman` (although we probably should).
> Have a cleaner start up for init-db.sh

- scrapers/fl/__init__.py
- scrapers/fl/bills.py
Prefiled bills are now being introduced for the Florida 2023 session. Added the 2023 Regular Session to the Florida scraper.
Source of the FL 2023 session dates:
https://www.flsenate.gov/Session/Calendar/2023/Session%20Dates%202022-03-17%20080110.PDF
> FL: Add session for 2023 prefiled bills

- .pre-commit-config.yaml
- scrapers/mt/actions.py
- scrapers/mt/bills.py
Improvements associated with [OS-783](https://civic-eagle.atlassian.net/browse/OS-783).
These changes update the MT scraper to:
- match bill action phrases to existing [OS classifications](https://github.com/openstates/openstates-core/blob/5b16776b1882da925e8e8d5c0a07160a7d649c69/openstates/data/common.py#L87) at a higher rate than before
- collect bill action phrases and their respective classifications in an organized way
- reorganize and simplify the way actions are being classified (not using regex if we don't have to)
> MT: bill action classification updates

- .pre-commit-config.yaml
- scrapers/vt/actions.py
- scrapers/vt/bills.py
Improvements associated with [OS-783](https://civic-eagle.atlassian.net/browse/OS-783). 
These changes update the VT scraper to:
- match bill action phrases to existing [OS classifications](https://github.com/openstates/openstates-core/blob/5b16776b1882da925e8e8d5c0a07160a7d649c69/openstates/data/common.py#L87) at a higher rate than before
- collect bill action phrases and their respective classifications in an organized way
- perform bill action classification in a separate function (outside of the main bill scraping function)
> VT: improving bill action classification

- .pre-commit-config.yaml
- scrapers/ak/actions.py
- scrapers/ak/bills.py
Improvements associated with [OS-782](https://civic-eagle.atlassian.net/browse/OS-782).
These changes update the AK scraper to:
- match bill action phrases to existing [OS classifications](https://github.com/openstates/openstates-core/blob/5b16776b1882da925e8e8d5c0a07160a7d649c69/openstates/data/common.py#L87) at a higher rate than before
- collect bill action phrases and their respective classifications in an organized way
> AK: improving bill action classification

- scrapers_next/ms/people.py
This PR was undertaken to fix an issue that was causing the MS people scraper to fail, receiving a 403 error in response to certain requests of member details page URLs.
- This was due to the fact that invalid URLs were being assembled for those requests whenever the scraper encountered a cell in the table of member names that did not contain a link. As of 11/24/22, this happens when vacant seats are encountered on the House members page (i.e. "Vacancy - District 23" instead of a hyperlinked Member name), but would presumably happen whenever hyperlinked text is not present in a cell.
- Solution to this issue in most recent file commit: a cell is skipped whenever there are absent XML page links.
In addition to fixing the above issue, two additional changes were added to improve upon the …
> MS: people scraper fixes

- scrapers/hi/__init__.py
- scrapers/hi/bills.py
Looks like they've updated the site, but most of the common structure still works. The versions have a different selector now, and just pulls the html link & tweaks it for the pdf link since the structure of the second link on the row isn't always definite.
> HI: Fix Version Parsing

- scrapers/la/actions.py
- scrapers/la/bills.py
- scrapers/me/actions.py
- scrapers/wa/actions.py
PR for action classification updates. These updates aim to increase action classification coverage as well as standardize the classification code so that it utilizes the BaseCategorizer class defined [here](https://github.com/openstates/openstates-scrapers/blob/3e5b5b1eec50f71a7b15b8be1c409a8be483694d/scrapers/utils/actions.py#L62). 
Currently working on:
> [LA, ME, WA]: action classification updates 

- scrapers/tn/bills.py
We still want to scrape bills that lack a title since they seem to have versions and other data available, this adds the same string we have for [AL bills](https://github.com/openstates/openstates-scrapers/blob/a50f83c37d06f2cd2e9185ccaa20ce32879581ec/scrapers/al/bills.py#L277) lacking a title and skips trying to pull a subject from a non-title.
> TN: Titleless Bills

- scrapers/ca/download.py
> CA: Bills: Skip cert validation when downloading bulk data

- scrapers/ct/actions.py
- scrapers/ct/bills.py
- scrapers/id/actions.py
- scrapers/id/bills.py
- scrapers/nh/actions.py
- scrapers/nh/bills.py
PR for action classification updates. These updates aim to increase action classification coverage as well as standardize the classification code so that it utilizes the BaseCategorizer class defined [here](https://github.com/openstates/openstates-scrapers/blob/3e5b5b1eec50f71a7b15b8be1c409a8be483694d/scrapers/utils/actions.py#L62).
> [NH,CT,ID]: action classification updates

- scrapers_next/tn/people.py
The TN people scraper's HtmlListPage object was failing on its top-level SelectorError. This was due to the url for both the Senate and House members having changed. The list page, however, remained unchanged. Correct urls were added, and the scraper was able to begin running through the member list page.
Once HtmlListPage was able to run, it was still failing on one member's page due to missing `extra_content` that an XPath selector was trying to access. After addition of a try-except clause to handle this missing page content, both House and Senate people scrapers were able to run successfully and completely. Data looks good.
> TN: people, urls fix, try-except add for missing content

- scrapers_next/wa/people.py
WA people scraper was failing on the House because the top-level CSS selector for the list page had `min_items=97` but selector was only getting 93 items. The number of members in the WA House is 98.
The discrepancy was due to five House members being recently removed from the House list because they were all elected to WA Senate seats (Matt Boehnke, Noel Frame, Drew MacEwen, Sharon Shewmake, Javier Valdez).
While the members pages for both chambers will presumably be fully updated when new session starts, this PR brings the `min_items` and `max_items` settings for the House selector into equal proportion with Senate selector counterparts set previously (the Senate is half the size of the house, at 49 members).
Do we feel good about those settings?
(Side note: Should we look at adding …
> WA: people RepList CSS selector min+max items adjust

- poetry.lock
Updating the openstates version to 6.12 which has the realtime flag feature.
> chore: update to openstates6.12

- scrapers_next/nm/people.py
NM people scraper was failing due to missing page content for vacant member seat.
- Error: `IndexError: list index out of range`
- Problem line: `party = name_party[1].strip()`
- Solution: conditional to skip that seat if alphabetic characters aren't found in the name text, or if name text contains "vacant"
> NM people: skip add for vacant seats

- scrapers_next/hi/people.py
- scrapers_next/in/people.py
Issue that sparked this investigation was fixed by an edit to a member's page on the legislative site.
However, two unrelated `AttributeError: 'NoneType' object has no attribute 'groups'` issues were discovered to be causing failures in running DemocraticSenate.
1. First on `phone1, phone2 = re.search(r"Phone:\s(\d{3}-\d{3}-\d{4})\s\|\s(.+)", phones).groups()`
- Cause: One or more dem senate members have less than two phone numbers
- Solution: Restructured how the scraper was ingesting the "Phone" data field and all other information in that section of the page (at this point that also includes "Legislative Assistant", "Email", and "Media Contact"), including addition of a custom exemption to be raised (and named accordingly) when `NewDetailFieldEncountered` because the legislative site …
> IN people: missing phone handling add, BlueSen social fix

- scrapers/usa/bills.py
occasionally bills have 'number' and 'type' instead of 'billNumber' and 'billType'
> fix USA bill ingest

- scrapers_next/ia/people.py
IA people scraper was failing because the XPath selector was encountering zero items when a member detail page had no content in the "Other Information" section.
- Error: `spatula.selectors.SelectorError: XPath(//div[@class='legisIndent divideVert']//tr) on <html lang='en'> @ line 2 got 0 results, expected at least 1`
- Solution: Changed XPath selector to target the parent `<table>` which exists in section even when devoid of display content. If table contains more than just a `<style>` tag, code now iterates through the rows with details fields, and uses conditionals to store details in the person object according to the field name / label on the site.
- Also added custom exception to be raised (NewDetailFieldEncountered(BaseException)). If the legislative site adds any other detail …
> IA people: new process for parsing/storing extra details

- scrapers_next/nd/people.py
The scraper was set to the 2021-2022 session and the 2023-2024 members are now available
> Updated ND People Scraper for 2023 Session

- scrapers/sc/bills.py
Got a response from an admin, they're using a new system this year and won't be posting Doc versions any longer so will remove that logic entirely.
> SC: Remove .docx Versions

- scrapers_next/ak/people.py
- scrapers_next/ks/people.py
Updated the session values for KS and AK. The AK value is correct but AK has not finished updating the page. Currently the page only includes Senators. They are still adding House of Representatives, there is missing data on one Senator, looks like they are making updates now. We may need to open a Jira ticket for AK if there are fixes needed in the scraper.
> Updated Hardcoded Session Values for AK and KS

- scrapers_next/fl/people.py
Scraper was failing with data validation error for `ScrapePerson` object when encountering an empty seat that is awaiting special election to be filled.
- Cause: scraper was only skipping if seat was labelled with "Pending, Election" and not in cases when label was "Pending, Special Election"
- Solution: conditional statement that initiates `self.skip()` executes simply if "pending" is in lowercase name label.
*Note* - additional commits were made to handle unlikely but possible cases when a hypothetical member's last name could contain the string "pending" at its end (i.e. "Spending, Marsha P.). The conditional now handles when either "pending, special" or "pending, election" are in the lowercase name label.
> FL people: fix to skip empty chairs awaiting special election

- scrapers_next/oh/people.py
Scraper was failing on multiple CSS selectors when running for either House or Senate. This was due to several class name changes of divs on the list pages of members.
Given the identical nature of the list pages, this commit consolidated the two different object types being used to handle each chamber's list page into one. The `House` and `Senate` class each now extend the `LegList` object.
Within `LegList`, this solution fixes the class names targeted by the CSS selectors.
- Additional improvements:
- tweak to conditional skipping of vacant seats
- addition of `list_page_url` as attribute of `LegPartial` object passed to `LegDetail`. Prior code was twice storing the member detail page in the ScrapePerson object, while failing to store the member list page url. This allowed that to be …
> OH people: fixes for changes on member lists, senate details pages

- scrapers_next/ri/people.py
Scraper was failing with 404 error when retrieving bio page urls for one senator and one assemblyman (both newly elected).
**Issue**
- the bad urls posted on the respective mailing list pages ([Senate](http://webserver.rilin.state.ri.us/Email/SenEmailListDistrict.asp) and [Assembly](http://webserver.rilin.state.ri.us/Email/RepEmailListDistrict.asp)) for these two members had only the last name (i.e. "ujifusa" for Senator Linda Ujifusa, and "finkelman" for Representative Alex Finkelman) while the good url path needed their first initial appended at the end of that substring (i.e. "ujifusal" and "finkelmana", respectively).
**Solution**
- given that there is not a consistent pattern to the good urls, this commit used ad hoc regex substitutions for those two members
- a `TODO` comment was …
> RI people: regex sub fixes for bad member bio urls

- scrapers_next/ma/people.py
Scraper was failing with SSLError on HTTPS request of member list url.
Error:
- `SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`
Solution:
- `verify=False` added to `URL` object for `list_url()`
Additional change to storing member email:
- Scraper was still failing with data validation error on `email` attribute of `ScrapePerson` object
- Solution: added `or ""` to store empty string when `self.data["EmailAddress"]` is none-type when processing member detail data.
> MA people: list_url request verify=False add to avoid SSLError

- scrapers_next/ne/people.py
Scraper was failing with HTTPError due to requests of member district page urls that are inconsistently maintained by host site. This commit replaced inconsistent url format with consistent one.
Error example:
- `scrapelib.HTTPError: 410 while retrieving http://news.legislature.ne.gov/dist04/`
Solution:
- Retrieves member landing pages (i.e. http://nebraskalegislature.gov/senators/landing-pages/index.php?District=04) instead
Additional:
- the url for the member list page was not being stored in each person object
- this commit stores list page in person object's `"sources"` collection, with note added indicating which source is the list page of members and which is member detail page
> NE people: new url format for detail pages, new list url storage

- scrapers/de/bills.py
Delaware has added new sites for individual caucuses and is using those links to indicate sponsorship on bills. This change makes it possible to handle those new links.
> Fix DE bill sponsorship links

- scrapers/pa/__init__.py
- scrapers/pa/bills.py
First special of the biennium!
I changed the code here to allow specials to be named "yearS1" in addition to "year#1" because I'm not confident that there's nowhere on os.org that we're not passing around session identifiers in the URL where a hash symbol could wreak havoc.
> PA: 2023 First Special

- scrapers/wa/bills.py
Scraper updated to include text of links for each action in the `action_text` stored as value of `description` attribute in bill object's `add_action()` method.
**Example using prior session bill:**
- Before this commit, [HB 1841 (from the 2021-22 session)](https://app.leg.wa.gov/billsummary?BillNumber=1841&Initiative=false&Year=2021) had it's second `action_text` stored as:
- "First reading, referred to Finance."
- With this commit, that `action_text` will include the text of the link associated with it and be stored as:
- "First reading, referred to Finance. (View Original Bill)"
*Note*: the scope of this commit was limited to grabbing the text. A future commit will get the `href` for the links, so that they can be also stored during the execution of bill object's `add_action()` method.
> WA bills: update to action_text to include text of action links

- scrapers_next/ar/people.py
Scraper was initial failing with `SelectorError` due to some new members' photos not being updated, but AR site resolved that issue itself.
However, scraper still failed with `SelectorError` on some detail pages due to absence of `<p>` for member's district address.
- resolved, for now, with an exception for those pages
A few minor changes were made elsewhere, a couple to achieve PEP8 line length, and the other to make a conditional check of a string's contents [more inclusive of case variations](https://github.com/openstates/openstates-scrapers/pull/4345/files#diff-5dd67280e0d5c1364f841b983d2f2865cc4d55fe4e52020ef4fed0c78fe70cfdL116-R122).
> AR people: selector error fix for missing detail page data

- scrapers_next/co/people.py
Scraper was failing because CSS selector for `LegList` had its `min_items` attribute set one number too high.
This commit reduces `min_items` from 101 to 100 (as there are 100 total members of CO legislature, with 35 Senators and 65 Representatives).
> CO people: reduce min_items for member list selector

- scrapers_next/nh/people.py
NH people scraper lacked any scraper of House member detail pages. This PR resolves that issue.
Primary contributions of this PR include:
1. Creation of `HouseDetail` class
2. Creation of helper function `scrape_house_vals()`
- returns a dictionary of values needed to construct the url for each House member detail page
- is called in `Legislators` class to provide the source attribute for `HouseDetail` object initializations
3. Removal of unnecessary, redundant, or incorrect scraping and text processing
- especially seen in `SenateDetail` class, as contact details that class was getting had already been collected from the CSV list page in `Legislators` class
- also identified the type of addresses being stored for each chamber's members, and added comment with explanation
4. Editing of …
> NH people: HouseDetail class creation, cleaning up old code

- scrapers_next/or/people.py
Scraper was failing with `AttributeError` when attempting to strip whitespace from member emails that were stored as `None` in the source JSON data.
- Solution: `p.email = email.strip() if email else ""`
Additionally, one request of member detail page was resulting in 404 error.
- Cause: bad url from JSON data
- Solution: replaced with correct string
> OR people: fixes 'email' validation and one bad member url

- scrapers/tx/events.py
@johnseekins @NewAgeAirbender right now all the TX agenda links are 404ing, so this at least gets us to an emptyscrape.
If they don't fix these in the coming days, we should probably bug the state / look for another source.
> TX: Skip event agenda links that 404

- scrapers_next/ga/people.py
Scraper was failing with `AttributeError` when attempting to call `strip()` string method on member's `city` value when value was `None`.
Solution:
- one-line conditional to save empty string instead, when city value is `None`
Additional modification:
- `add_source()` now called only for API paths that are used to scrape list of members and member detail data
- `add_link()` now used to save the HTML page paths for both chamber-specific member list page and member detail page
> GA people: add extras['city'] None handle, API/HTML source+link w notes

- scrapers_next/wi/people.py
Scraper was originally failing for both Senate and House with the same `SelectorError`. Eventually resolved for the Senate scraper by updates to the Wisconsin site, but this PR was needed to resolve for House scraper.
Solutions:
- `XPath()` selector for getting `detail_link` was modified to have broader arguments to allow for differences in content/formatting.
- Conditional for getting `img` was modified to include case when no member photo provided.
Additional change:
- `source` additions include notes specifying either `"members list page"` or `"member detail page"`.
> WI people: fixes for missing photo, inconsistent formatting

- scrapers_next/nv/people.py
Scraper was failing with `IndexError` during member name parsing, triggered by vacant seats.
Additionally, in analyzing the data, it was discovered that name suffixes (i.e. "III", "Jr.", "Esq.", etc.) were not being stored in the correct position within a name string.
This PR rewrote the code block for name parsing to (1) use regular expressions (instead of prior approach which relied on splitting and concatenating the name parts by index) and (2) have a conditional regex check -- and separate handling for parsing and reconstructing -- names with suffixes.
> NV people: add regex handling for member name parsing

- scrapers/sc/bills.py
They added back docx versions to Filed bills but not all bill versions, so adding it as an option
> SC: add docx version to Filed bills

- scrapers/mn/events.py
Bill names can't have periods in them when inserting them, so we strip periods.
> Mn event house fix (part 3)

- scrapers_next/co/committees.py
Committee scraper was failing with `SelectorError` on `CSS(.member)`.
- This was happening for just one committee that lacked membership: the "Task Force for the Consideration of Facial Recognition Services"
This PR solves this by changing to a standard `xpath` selector, and logging a `logging.warning` when a committee does not have a `<div>` with `class='member'`.
> CO comm: selector change to handle task force w/o members

- scrapers_next/ak/committees.py
Committee scraper was failing with error `spatula.selectors.SelectorError: CSS(div.area-frame ul.list li) on <html> @ line 3 got 110 results, expected 112`
This PR simply adjusts `num_items` attribute of the CSS selector down to match the number of items actually appearing on the page.
> AK comm: adjusted num_items down on CSS selector

- scrapers/ny/events.py
NY senate bills might be versioned by a suffix. So `S123` becomes `S123A`. This breaks matching in OpenStates. We'll use a little regex to catch this suffix and remove it.
> handle (and lightly document) bill versioning in senate

- scrapers_next/mo/committees.py
Committee scraper was failing for Senate due to changes to the CSS on the site.
- This PR addresses this issue with new selector paths.
Additional changes:
- Regex implementation for simple and reliable member name/role extraction
- Updated `note` attributes for added sources
- Removed `SkipItem()` on committees without membership, opting instead for `logging.warning`
- the prior code was not skipping and not writing committees that didn't have members listed
- Other various small modifications to conditional statements parsing strings
> MO comm: senate css changes, add member improvements

- scrapers_next/ca/committees.py
Scraper was failing for both Assembly and Senate, due to a variety of formatting changes and variations across pages on the site.
This PR provides a rewritten/reformatted committee scraper that can handle the substantial amount of HTML inconsistencies across CA's committee pages, while also being simpler and more class-based.
> CA committees: rewrite of scraper after site changes

- scrapers/ks/events.py
- scrapers/oh/bills.py
This rewrite switches the source of KS events significantly, but does actually discover bills being worked on in committees again.
> re-write KS event scraper to mostly pull bills

- scrapers/mn/bills.py
- scrapers_next/az/committees.py
- scrapers_next/ga/committees.py
Fixes a typo in MN, mostly updates sessions on Committee scrapers & adds a check for existing address in GA
> Multi: update committee sessions, fix typo

- jurisdiction_configs.json
- scrapers_next/mi/people.py
This PR was undertaken to address URL and page modifications that caused Senate scraper to break for MI people.
It addresses those issues. It also:
- adds ingestion of member image paths for all Senate members, and for GOP members of House
- creates one new object class, one new helper function, and two custom exceptions to this end 
- adds documentation for prior-created helper function
- includes documentation of work done to eventually also get Dem members of House
- various other small modifications
> MI people: senate fix, senate both and house gop images add

- scrapers/ms/bills.py
We've been missing ~86 senate bills & resolutions for a few days because the scrape returned instead of continuing on if there wasn't a title. There'll probably be one posted eventually, but following the example from [TN](https://github.com/openstates/openstates-scrapers/blob/c4762c1ea89267343abb6b7c219ae19d6531d700/scrapers/tn/bills.py#L338) where we just set the title to something noticeable for us & users
> MS: continue instead of return in case of no title

- scrapers_next/nj/committees.py
New committee scraper for New Jersey written in spatula.
Makes calls to four different APIs for Joint, Senate, Assembly, and Other Committees, respectively. Parses the JSON responses using `JsonPage` class to yield committee objects.
> Added NJ committee scraper

- scrapers/ne/bills.py
Grabbing cosponsors from actions, as detailed in [OS-1021](https://civic-eagle.atlassian.net/browse/OS-1021).
> NE: parsing actions to grab cosponsors

- scrapers_next/la/people.py
LA legislature updated the CSS for their House (but not the Senate). This fix decouples scraping for House and Senate, along with updating CSS selectors for the House to reflect the updated CSS on the page. Pertains to [OS-898](https://civic-eagle.atlassian.net/browse/OS-898).
> LA: people scraper CSS fix for house

- scrapers_next/fl/people.py
Since (non-empty) strings are always resolved as "true" in Python, there was an `if` statement that was always being entered, causing a bug. Made a minor change to the `if` statement so that this does not happen. Pertains to [OS-1009](https://civic-eagle.atlassian.net/browse/OS-1009).
> FL: minor fix to House scraping

- scrapers_next/mt/committees.py
Two modifications:
- Concatenated substring to `parent` value for the appropriations subcommittees to match full name of parent committee
- Added the chamber-specific names to the `other_names` collection for the "Joint Appropriations and Finance and Claims" (which is comprised of the membership of "House Appropriations" and "Senate Finance and Claims", but acts as a unified body and has its own detail page, while there are no chamber-specific detail pages for appropriations committees or subcommittees)
> MT comm: minor fix for joint approps comm + subcomms

- scrapers/mn/bills.py
This PR fixes a gap in data ingestion, wherein versions were only being retrieved for bills and not for resolutions (normal or concurrent).
Cause
- The formatting on resolution detail pages do not have the "Version List" table we were targeting for this data.
Solution
- This PR added a backup target in the case when the versions table isn't found.
- A request is made for the html page containing the "Current Bill Text", on which is found:
- the html text of the that version
- a link to the pdf page for that version
- a list of links to the html pages of any other versions that may exist
- in the case that those version links do exist, additional requests are made of each link's href in order to retrieve the pdf page urls for each version
MN resolutions and concurrent resolutions are now …
> MN bills: fix gets bill versions for resolutions

- scrapers_next/md/committees.py
Created MD committee scraper.
This ( https://mgaleg.maryland.gov/mgawebsite/Committees/Details?cmte=pos ) committee's title implies that it is a subcommittee, but I don't see any more info about what the parent committee is. Currently handling this by removing the "Joint Subcommittee on" part of the name and adding it as a regular committee - should I change how this is handled?
> MD committee scraper

- scrapers/ms/__init__.py
So MS removed the 'First' from the 2022 First Extraordinary Session just on the [session list page](http://billstatus.ls.state.ms.us/sessions.htm), but the [interior pages](http://billstatus.ls.state.ms.us/20221E/pdf/mainmenu.htm) of that session still say the full '2022 First Extraordinary Session'. The links to the bill versions also all still work ([HB1](https://openstates.org/ms/bills/20221E/HB1/) for example), so opting to just add it to the ignore list rather than changing the metadata for that session. cc: @chrisyamas
> MS: ignore 2022 Extraordinary Session

- scrapers/co/bills.py
For now, if there turn out to be a bunch of these and they don't backfill, we'll set some default data.
> CO: Bills: Skip fiscal notes with no meta data

- scrapers/hi/actions.py
- scrapers/hi/bills.py
Hawaii action classification updates, related to [OS-1077](https://civic-eagle.atlassian.net/browse/OS-1079). These updates aim to increase action classification coverage as well as standardize the classification code so that it utilizes the BaseCategorizer class defined [here](https://github.com/openstates/openstates-scrapers/blob/3e5b5b1eec50f71a7b15b8be1c409a8be483694d/scrapers/utils/actions.py#L62).
> HI: action classification update

- scrapers_next/nc/committees.py
Partial rewrite of North Carolina committee scraper to get all current standing, select, and non-standing committees.
**Major modifications include, but are not limited to:**
- Consolidation into one single scraper `CommitteeList` (rather than limiting to only house and senate standing committees, as before)
- Subcommittee handling (including custom exception for when new subcommittee's with unknown parents are encountered)
- Improved committee name formatting for legislature-classification committees
- Improved member name formatting (including getting full names for committee members)
> NC comm: rewrite gets all comms, accurate names

- scrapers_next/az/committees.py
- scrapers_next/ca/committees.py
- scrapers_next/ct/committees.py
- scrapers_next/fl/committees.py
- scrapers_next/in/committees.py
- scrapers_next/ks/committees.py
- scrapers_next/ky/committees.py
- scrapers_next/ma/committees.py
- scrapers_next/me/committees.py
- scrapers_next/ms/committees.py
- scrapers_next/ne/committees.py
- scrapers_next/nh/committees.py
- scrapers_next/oh/committees.py
- scrapers_next/vt/committees.py
- scrapers_next/wi/committees.py
This updates the committees scrapers of the following jurisdictions to ensure they all utilize required `add_link()` method for each committee scraped, with the method including a `note="homepage"` argument. *Note: ME also had its committee scraper file renamed due to a typo --> `committies.py` became `committees.py`.*
Jurisdictions updated:
- MA
- FL
- AZ
- CA
- CT
- IN
- KS
- KY
- ME
- MS
- NE
- NH
- OH
- VT
- WI
> Comm add_link updates

- scrapers_next/mt/committees.py
Need to set other names as a listed dictionary of `OtherName` based on the model [here](https://github.com/openstates/openstates-core/blob/f086a88b9e5cf861e9d4d674da30bce22bc99f7a/openstates/models/common.py#L108) FYI @chrisyamas
> MT: other_names fix

- scrapers/ma/bills.py
@NewAgeAirbender @johnseekins @jessemortenson  -- Flagging y'all while this is still a WIP to get your feedback.
MA has a system where they file a bill with one number "docket number", "HD123", then once it hits committee they list it under a normal bill number, unrelated to the docket number. "H345". 
Traditionally Openstates has just duped them, so the docket version stops updating after intro and we have a ton of dupes under the different bill numbers.
I've updated the scraper to do two things:
1. Now when we pull an intro-d bill, we add the docket version as a companion, using the "replaces" relationship. This is in the database but I don't think it's ever been used.
2. I updated the scraper to use the API for the bill list, instead of a big, slow paginated search. I think someone on …
> MA: Bills: Better handling of changing bill ids

- scrapers/tn/bills.py
Scrapers failing cuz of a lack of action text on [HB 243](https://wapp.capitol.tn.gov/apps/BillInfo/Default.aspx?BillNumber=HB0243&GA=113) so just adds a check
> TN: empty action description check

- scrapers_next/tn/committees.py
Minor modification to fix a parent committee names, and to remove "Committee" and "Subcommittee" strings from committee names.
> TN comm: parent name fix

- scrapers_next/la/committees.py
Fix for Louisiana committee scraper for proper formatting of names containing comma-separated suffixes like "Jr." and "III"
> LA comm: member name suffix fixes

- scrapers_next/ia/committees.py
Committees in upper and lower chamber were missing the `add_link()` method, and this showed up during imports. This PR updates accordingly.
> IA comm: detail page link add for lower, upper

- scrapers/wa/actions.py
Fixing classification for a rule from "passage" to "committee passage favorable". Relates to [DATA-2444](https://civic-eagle.atlassian.net/browse/DATA-2444).
> WA: fixing inaccurate action classification Rule

- scrapers_next/ia/people.py
Capitol office addresses are listed as "business address"es on legislators' pages. We were scraping this as an extra_field and I changed it to map back to capitol office address. Also accounted for inconsistencies in the way "capitol phone number" is written on legislators' pages. ~~Why won't they standardize~~
Relates to [OS-1123](https://civic-eagle.atlassian.net/browse/OS-1123)
> IA: updating people scraper to grab capitol addresses and phone numbers

- scrapers/ut/events.py
Changes made:
- Modified regex to only match these prefixes ['SJR', 'HCR', 'HB', 'HR', 'SCR', 'SB', 'HJR', 'SR'] and not others
- Adjusted bill id format to "HB 123" rather than "HB0123"
> bugfix for UT events.py bills

- scrapers/nd/events.py
Only one bill was being added per event. This was caused by using the event time as the item_key for each bill. Bills were stored in a set so duplicate keys caused previous bills to be deleted.
I fixed this by adding the bill name to the key.
I also updated bill description to use the agenda time instead of the meeting start time since I was changing that area of the code. If this isn't correct I can change it back.
> Bugfix for ND events

- scrapers/ri/events.py
The first bill was being skipped because the header was being interpreted as part of the bill text. There was a check to skip any bills that included "SCHEDULED FOR", which is always part of the header.
This fix checks the html tags so it doesn't bundle the header text into the bill name.
While I was working on this, I noticed that there were also some bill names being scraped that I think are incorrect, like "50", "18", "S0115". Should I try to fix these also?
> Bugfix for RI events missing first bill

- scrapers_next/wi/committees.py
Updates year from 2021 to 2023 in sources. Also changes `source` and `input` to `example_source` and `example_input` in `CommitteeDetails` class.
> WI comm: fix to update to 2023 committees

- scrapers/ga/events.py
The event scraper bug fix in this most recent prior PR did not allow for additional variance in formatting of bill references on committee agendas. The below code block includes such variance into the regex:
```
matches = re.findall(
r"((SB|HB|SR|HR|House Bill|Senate Bill|House Resolution"
r"|Senate Resolution|H\.B\.|S\.B\.|H\.R\.|S\.R\.)\s+\d+)",
self.text,
)
```
Additional formatting method `format_match()` was added to `Agenda()` class to ensure bill_id is yielding in format that will allow for bill association.
> GA events: increase acceptable variance of bill ids

- scrapers_next/ut/people.py
Fixes for [OS-1144](https://civic-eagle.atlassian.net/browse/OS-1144)
- updating address portion to better distinguish between capitol and district addresses
- updating phone number portion to capture data more thoroughly and distinguish between capitol and district
> UT: updating people scraper 

- scrapers/ia/bills.py
They changed the page layout of the bill detail page so we weren't catching titles or sponsors. There's also a better [list page available](https://www.legis.iowa.gov/legislation/findLegislation/allbills?ga=90) so we don't have to scrape by chamber that we can get the title & list of sponsors from instead.
> IA: Fix Bill Titles & Sponsors

- scrapers/nj/__init__.py
Bumping up the end date so it's a little more accurate cc: @chrisyamas
> NJ: update 2022-2023 end date

- scrapers/nd/votes.py
There's two vote events that were causing problems since they were recorded [so close together](https://www.ndlegis.gov/lcn/assembly/legss/public/rollcall.htm?legislativeDate=2%2F21%2F2023) (Consideration Of Amendments - Division A for HB 1015 multiple times that day), so adding the time the vote happened to try to avoid the scraper failing due to duplicate events just based on the date of the vote. Also cleaned up some whitespace in the status.
> ND: add vote time to avoid duplicates

- scrapers/ia/bills.py
The IA scraper is continually failing and making the following two changes allows the scraper to run faster and for us to get the bills we are missing. This will be a temporary hack. We have also reached out to the IA Webmaster and are working on other solutions.
> ia-scrape-fix

- scrapers/hi/actions.py
Fixing incorrect classification (classifying an action as `passed` instead of `passage`). Thanks for catching @johnseekins!
> HI: fixing incorrect classification

- scrapers/ma/bills.py
[HD 4162](https://malegislature.gov/Bills/193/HD4162) was causing [issues on import](https://bobsled.openstates.org/run/bc2dadecf20342eca0951d9711b19d6e#bottom) since the Abstract was an empty string, so adds a check for that.
> MA: check abstract for empty value

- scrapers/ny/bills.py
[This vote](https://nyassembly.gov/leg/?default_fld=&leg_video=&bn=S00823&term=2023&Floor%26nbspVotes=Y) was causing issues on the scraper since there's text at the bottom that was getting flagged as a vote. The members' votes are recorded as usual, but they wanted to note who was voting but not physically present.
> NY: add check for extra non-vote text

- scrapers/ia/bills.py
Chamber was not getting set correctly for Study bills so this fixes it. Also adds the bill type as proposed bill to Study bills since they get renumbered & reintroduced as HF or SF bills.
> IA: fix chamber assignments & H/SSB classification

- scrapers/md/events.py
Events were being added with " - Bill Hearing" at the end of the string. This PR removes that substring.
> MD events: remove Bill Hearing substring from name

- scrapers/nc/events.py
Bills were not being added to an event's agenda with a proper bill id. This PR fixes the formatting, and provides custom errors to encounter unexpected values / changes to page in future scrapes.
**Further detail**
- Proper bill ids for NC have prefixes included in this set: `{'SJR', 'HB', 'HR', 'SB', 'HJR', 'SR'}`
- Example in tested output:
- bills that were being added to event agenda as 'H250', 'S54', 'H175', and 'S100' are now being added with proper prefix and formatting to be, respectively, 'HB 250', 'SJR 54', 'HJR 175', and 'SB 100'
> NC events: bill id reformatting

- scrapers/nj/events.py
PR adds conditional statement to skip full-chamber events (Meeting of the Senate or House "on the Whole") to help limit the scope of the scraper only to committee events on the calendar.
> NJ events: skip full chamber events

- scrapers/al/bills.py
There's one bill (HB142) that's added as a duplicate but without most of the important information (including sponsor), so adding a check to sponsorship & returning if it doesn't exist.
> AL: check for sponsor existing

- scrapers/nv/bills.py
Function created to shorten bill title in case when it's length is longer than the acceptable 300 characters.
Only known case in with SJR7-2021, where bill title from source is:
- "Proposes to amend the Nevada Constitution to remove the constitutional provisions governing the election and duties of the Board of Regents of the State University and to authorize the Legislature to provide by statute for the governance of the State University and for the auditing of public institutions of higher education in this State. (BDR C-944)"
- this solution shortens it to:
- "Proposes to amend the Nevada Constitution to remove the constitutional provisions governing the election and duties of the Board of Regents of the State University and to authorize the Legislature to provide by statute for the …
> NV bills: shortener for too long bill title

- scrapers/la/__init__.py
Adjournment of special session was Friday, 2/3/23 according to [source site](https://legis.la.gov/legis/home.aspx).
> LA: set extraordinary session to false

- scrapers/al/bills.py
This PR implements a conditional check for duplicate bills, and skips cases where they are encountered. Duplicates were resulting from being listed multiple times on the [source site](https://alison.legislature.state.al.us/bill-search).
The duplicates that are being prevented:
- SB123
- SB124
- SB125
- SB126
- SB127
- HB142 (although this was already prevented by [a different check](https://github.com/openstates/openstates-scrapers/pull/4569) added by @NewAgeAirbender earlier this week)
> AL bills: prevent duplicate bills

- scrapers/ct/events.py
Simple fix for error that was resulting:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='www.cga.ct.gov', port=443): Max retries exceeded with url: /2023/AGEdata/ca/pdf/2023ca-00124-R001230AGE-ca.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`
Solution adds `verify=False` argument to `URL()` object for `Agenda()` scrapes.
> CT events: agenda url verify set to false

- scrapers/ri/events.py
Adds the event `name` as `dedupe_key` to prevent `DuplicateItemError` during import.
> RI events: dedupe key add

- scrapers/sc/__init__.py
The SC events scraper has been failing with `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` which typically indicates that we're scraping their site too fast so it cuts us off. 
This PR replicates what has been done in other jurisdictions and adds `settings = {"SCRAPELIB_RPM": 30}` to the `__init__.py` for SC. The solution works after several local tests
Just wanted to confirm that this RPM is agreeable, as it might slow down the SC bill scrapes, given that it is in the `scrapers/sc/__init__.py` file. However, that is also where this setting is made for every other jurisdiction where `SCRAPELIB_RPM` is set.
> SC: setting scrapelib_rpm to 30

- scrapers/oh/events.py
Adds the event `name` as `dedupe_key` to prevent `DuplicateItemError` during import.
> OH events: dedupe key add

- scrapers/de/__init__.py
- scrapers/de/bills.py
This PR adds `verify=False` argument to three different methods that are making HTTP requests of DE site, to avoid `SSLCertVerificationError`.
> DE: set SSL verification to false

- scrapers/ri/events.py
This PR makes each event's `dedupe_key` more unique, which allows for it to function as intended in preventing `DuplicateItemError` during events import.
> RI events: dedupe key made unique

- scrapers/de/events.py
Removes the need for the machine on our end to download the correct intermediate certificate
> DE: Events: Skip cert verify

- scrapers/al/bills.py
AL bills scraper was failing when validating a bill, due to one of the bills having its title value set to multiple whitespace string `"   "` in the JSON data. There is a conditional in the code for handling when titles are just an empty string (which triggers a different value assignment), but not when there is whitespace contained.
By stripping whitespace from `title` value that is initially extracted from the JSON data, the conditional can be triggered for all appropriate cases, thereby ensuring reassignment of `title` to a valid string value, such that every bill object now passes validation with this fix in place.
> AL bills: strip title whitespace, validation fix

- scrapers/pr/bills.py
Puerto Rico bills scraper was not paginating properly, due to a change in the names of most parameters for the POST request on the site. We were only getting 50 bills per scrape.
This commit updates those parameters in the file, and resulting in successful POST requests when updated scraper was tested locally.
> PR bills: params update to paginate, get all bills

- scrapers/mt/bills.py
Montana bills scraper has been failing, likely due to `ConnectionError` which could be rectified by increasing the maximum allowed setting values for the attributes of `Scraper` object corresponding to `scrapelib` settings: `retry_attempts` and `retry_wait_seconds`.
This PR increases each of those respective attribute values by a factor of (approximately) three. If scraper runs are successful after this, we can try adjusting the setting back down slightly to lower the overall runtime.
> MT bills: increase max retry attempts + wait time

- scrapers/sc/events.py
This PR addresses two issues: one with event times, the other with duplication.
Event times
------------
South Carolina events scraper was failing on a `ValueError` when a string like `"Immediately after EOC Full Committee"` was being passed to `datetime.strptime()` method instead of a time string like `"1:00 pm"`.
This would occur in cases when the time for an event is determined by the start or end time of a prior event. This solution stores a reference to the immediately-prior-event's start time, and has the aforementioned dependent cases simply default to the prior event's start time (as that is the best estimate that can be provided, and we do not want to provide a time that could be later than the dependent event's actual start time).
Duplication
-----------
Dedupe key added to …
> SC events: event time fix, dedupe key add

- scrapers/mt/bills.py
This PR comments out all calls for vote scraping and parsing in the Montana bills scraper, and refactors the scraper to run without those lines (only getting bills and actions).
*Note: Vote functionality will be added back in soon. This PR is simply meant to get MT bills scraper successfully running again for now.*
> MT bills: (temporary) disable ~all~ vote processing

- scrapers_next/va/people.py
People scraper updates to scrape address and contact info more thoroughly. Relates to [DATA-2348](https://civic-eagle.atlassian.net/browse/DATA-2348).
New additions to scraper:
- scraping both blocks of contact information (capital and district)
- better identification for which information belongs to capital and which to district
- sanity check to make sure we aren't adding the same phone number to both capital and district offices
> VA: people scraper update

- scrapers/al/bills.py
- scrapers/al/events.py
The PR modifies both Alabama's events and bills scrapers for duplication/deduplication adds:
- Events: completes [earlier implemented](https://github.com/openstates/openstates-scrapers/commit/ff201fd13994c745dfdee41e4fe1d4418dd2b526#diff-606b539e25ba4c7bd78bde8129df17b5a3e6f94076ebced16333f4a6547aa5e1R66-R67) deduplication by adding a `set()` for unique event keys, along with a conditional check, to prevent actual duplicates.
- Bills (specifically votes): adds `VoteEvent` dedupe key with `set()` for duplicate checks and prevention.
> AL: event and bill vote deduplication adds

- scrapers/ar/bills.py
Adds `yield bill` command that was missing from `scrape_bill_page()` method, and necessary for scraper to run successfully.
> AR bills: fix yield statements in refactoring

- scrapers/ca/bills.py
Subjects are listed separated by colons on the source, so this breaks them up in a way that makes that clear. There are 2 special cases, one has a super long one so gets trimmed a bit and the other has a colon at the end instead of a period so fixes for those cases.
> CA: break up subjects

- scrapers_next/or/people.py
Representative Charlie Conrad's [page](https://www.oregonlegislature.gov/conrad) does not have the representative's image in the selector specified in the scraper. 
This commit manually specifies his image.
> Fix image scrape for Rep. Charlie Conrad in OR

- scrapers/fl/__init__.py
We don't need to be scraping the special session since it ended in February.
> FL: update past special session

- scrapers/nv/bills.py
This PR adds an additional known case to the conditional clause that handles the shortening of bill titles in cases when the title exceeds 300 characters.
> NV: case added for title shortening

- scrapers/sc/bills.py
The PR updates the South Carolina bill scraper to get the shorter version of the Summary for the bill title, and adds the longer version (which was previously being stored as the bill title) as an abstract.
This was undertaken to prevent overly-long bill titles.
> SC bills: updates for summary and abstract selection

- scrapers/mo/__init__.py
This PR updates the URL and xpath used to get the list of sessions from the Missouri legislature. This was done because there were frequent failures with the prior URL used.
> MO: update to more reliable session list src

- scrapers/utils/lxmlize.py
This PR adds an exception clause to the `url_xpath()` method in `scrapers/utils/lxmlize.py`. The purpose is to provide more detailed and useful logging, particularly to debug errors that occur with this method when a scraper is run virtually but do not occur when it is run locally (i.e. s in AWS but not on developer's local machine).
> Scrapers Utils: url_xpath exception add

- scrapers/ut/__init__.py
This PR updates the end date of UT’s First Special Session to be 5/18/23.
The session began on 5/17/23 and [ended that same day](https://le.utah.gov/asp/schedule/journal.asp?Session=2023S1).
> UT: 1st special session enddate add

- scrapers/mo/__init__.py
This PR updates the `__init__.py` file for Missouri to include a list of all current and past sessions listed on their legislative site.
Including the array in the file eliminates the risk of the `403: Forbidden` errors that were resulting during AWS runs of the MO scrapers, when attempting to retrieve the list via a HTTP request in the `__init__` file's `get_session_list()` method.
> MO: get_session_list() update to use in-file list

- scrapers/utils/__init__.py
- scrapers/utils/events.py
This PR creates a new utility function that can be utilized in event scrapers to create a unique hashed identifier for the event's `dedupe_key`, to help facilitate duplication prevention which also eliminates risk of a `dedupe_key` exceeding allowable length.
The modification made in this PR was undertaken based on [this code suggestion](https://github.com/openstates/openstates-scrapers/pull/4639#discussion_r1201294079) from @johnseekins.
> Scraper Utils: event key hash add

- scrapers/ok/__init__.py
Note: There are bills on the site but they're marked as test bills to ignore.
> OK: ignore 2024 for now

- scrapers/sc/__init__.py
- scrapers/sc/bills.py
Adds functionality to scraper to ingest past session bill data.
This was undertaken to update Open States database after improvements were made to `name` and `abstract` collection for SC bills in [previous PR](https://github.com/openstates/openstates-scrapers/pull/4629).
Note: web archived pages were used to get the past session bill index pages, which allows for this past-session ingestion with minimal changes to the scraper. `TODO` comments have been included in the code as reminders to maintainers that an archive id will need to be manually added in the lead up to every new session start (i.e. every two years) to ensure full past-session-scrape functionality.
> SC: temporary changes to scrape past 2 sessions

- scrapers/ks/ksapi.py
KS changed the meaning of some of their API response codes, resulting in a bunch of veto override attempts getting misclassified.
> KS: Fix for errant veto classifications

- scrapers/nv/events.py
Adds a line to strip extra whitespace from date string, which can otherwise cause failure when `strptime()` method is called on the string.
> NV: strip extra whitespace from date

- scrapers/nv/bills.py
NV sometimes combines multiple actions into one listing, so allow multiple classification matches. See https://www.leg.state.nv.us/App/NELIS/REL/82nd2023/Bill/10207/Overview -- where we're missing a chamber passage right now.
Requesting review because that python for merging lists or strings and deduping feels kinda hacky, open to better ways.
> NV: Bills: Allow multiple action classifications on the same action

- scrapers/nc/bills.py
Running into validation issues with some vote events, we already capture the roll call number to check the chamber voting, so just adds it as the `dedupe_key`
> NC: Dedupe VoteEvent by Roll Call Number

- scrapers/fl/__init__.py
Adds 2024 session to `legislative_sessions` list in the `init` file, in response to the Florida legislature adding it to their site.
Start and end dates are estimates using 2022 as basis for prediction, with comment to update later when that information is announced.
> FL: add 2024 session with estimated dates

- scrapers/in/bills.py
We're missing actions on indiana bills with > 50 actions, because they were maxing out and paginating.
> Indiana: Unpaginate actions

- scrapers/wa/__init__.py
- scrapers/wa/bills.py
- scrapers/wa/events.py
WA doesn't have the subject page anymore, temporarily disabling while we find another solution before the next session starts. Also adds `EmptyScrape` to the event scraper
> WA: update end date, add empty to events, skip subjects

- scrapers/al/events.py
- scrapers/fl/events.py
- scrapers/ga/events.py
- scrapers/mt/events.py
- scrapers/nd/events.py
- scrapers/nh/events.py
- scrapers/tx/events.py
Also a few other misc fixes, add start date and agendas/media where available.
> Events: Add more committee participants

- scrapers/mp/__init__.py
- scrapers/mp/bills.py
> Marianas Islands Scraper

- scrapers/fl/__init__.py
- scrapers/fl/bills.py
> FL: add 2023C to active sessions

- scrapers/ga/__init__.py
- scrapers/ga/bills.py
- scrapers/ga/util.py
> DO NOT MERGE YET GA: 2023 first special

- scrapers/ok/__init__.py
The 2023 sessions have past so dropping them from `active` status, also updates the dates for 2023S2 & 2024
> OK: update active sessions & metadata

- scrapers/usa/bills.py
We were incorrectly linking HJRes and SJRes to the non-joint equivalents on congress.gov
> USA: Bills: Fix congress.gov source links for joint bills

- scrapers/mn/bills.py
MN SSL is capital B Broken. Should fix [Issue 1132](https://github.com/openstates/issues/issues/1132)
> MN: unverify the two other requests

- scrapers/mo/bills.py
We're getting 403 errors hitting the [House Bill Subject](https://house.mo.gov/LegislationSP.aspx?code=R&category=subjectindex&year=2024) page with either Bobsled or Airflow so this temporarily skips it so that we can at least get most of the bill data in for prefiles. I have a contact with the team of House Developers, so I sent an email asking if they'll have that information available on the Bill Detail XML page & will update the scraper based on his information.
> MO: comment out subjects temporarily

- scrapers/pa/events.py
Related bills were adding python list items instead of proper strings, this fixes the bill names.
> PA: Events: Fix related bill names

- scrapers/nv/bills.py
I've updated NV bill scraper in order to get votes.
> NV: update bills scraper to find votes

- scrapers/ri/bills.py
This scraper is doing a POST request for every 2023 subject, despite none of them being assigned. I'm disabling subjects for now which speeds it way up.
Once there's data here, we will want to restore them. FYI @jessemortenson @NewAgeAirbender 
Also if anyone needs to train a newbie, this scraper has some gnarly old code that could benefit from a rewrite.
> RI: Better logging, disable subjects for now

- scrapers/me/__init__.py
Date from https://legislature.maine.gov/
Currently, no ME event related entities (specifically related bills) are matching to actual bill entities, because the `resolve_bill()` logic [only looks for bills that are in a session with dates that bracket around the event's date](https://github.com/openstates/openstates-core/blob/db7af4d314fa5dd6b5ce3864627c38799d46db78/openstates/importers/base.py#L171). Since ME's session 131 was coded as ending in 2023, none of the bill entities are being resolved on event related entity records.
> ME: change session 131 to end in 2024 so events match current bills

- scrapers/nj/__init__.py
Only merge when bills can be scraped successfully
> NJ: add 2024-2025 metadata

- scrapers/la/bills.py
LA doesn't provide the year in action dates. The scraper was previously assuming actions happened in the year of the most recent session, but right now we're scraping 2023 while the most recent session is an upcoming 2024, so all action dates are wrong.
This fixes it.
> LA: Bills: Fix for assumed year in action dates

- scrapers/ak/events.py
- scrapers/mi/events.py
In many cases we're skipping cancelled events; instead mark the status as cancelled and yield them normally.
> Event Cancellations

- scrapers/ny/apiclient.py
/agendas/meetings/ now seems to require an undocumented 'limit' query parameter, or else it throws a bad input error
> NY: fix events API call

- scrapers/usa/events.py
There's a title that got submitted [incorrectly](https://docs.house.gov/Committee/Calendar/ByEvent.aspx?EventID=116690) on the site, just shortens it so bobsled scrapes don't error on validation
> US: drop characters on event titles

- scrapers/hi/__init__.py
- scrapers/hi/bills.py
- scrapers/hi/events.py
- scrapers/hi/utils.py
@jessemortenson @NewAgeAirbender this is a patch for HI that will work w/ any transparent proxy, to minimize code changes and requiring a specific vendor.
Using zenrows, my test command was:
```shell
HTTPS_PROXY="http://API_KEY_HERE:premium_proxy=true&proxy_country=us@proxy.zenrows.com:8001" HTTP_PROXY="http://API_KEY_HERE:premium_proxy=true&proxy_country=us@proxy.zenrows.com:8001" PYTHONPATH=scrapers poetry run os-update hi bills --scrape
```
The same also works for events.
You might also want to set  ```PYTHONWARNINGS="ignore:Unverified HTTPS request"``` to shut up the insecure request warnings.
If we decide to go this route, i'll update the documentation too.
> HI: disable SSL verify, update for some site HTML changes, add 2024

- scrapers/ok/__init__.py
- scrapers/ok/bills.py
There's a [special session on taxation](https://www.news9.com/story/65a6ed12b1b013065b2bccc3/stitt-calls-for-special-session-on-tax-cuts) called for the 29th, setting as inactive for now until bills are posted
> OK: add 2024 3rd special

- scrapers/ms/__init__.py
Looks like they swapped out the numerical for spelled out
> MS: update scraped_name for 20241E

- scrapers/sc/events.py
Tweaks to clean up SC events:
- Better description (dropping the dangling " on " in "Senate Education Subcommittee on ")
- Catch a few events at the bottom of Senate page that were being skipped (they break the pattern of UL > SPAN, LI)
> SC: improve Events scraper re: event names, catch more events

- scrapers/ri/bills.py
Rhode Island's bill listing includes the bill title and a summary of the bill in parentheses. I believe that summary is not strictly part of the bill title, per the bill document. For example: [H 7046 PDF](https://webserver.rilegislature.gov/BillText/BillText24/HouseText24/H7046.pdf) vs the output in bill search/listing:
```
House Bill No. [7046](http://webserver.rilegislature.gov/BillText/BillText24/HouseText24/H7046.pdf)
BY  Speakman, Cortvriend, Carson, Kislak, Potter, Boylan, Ajello, Tanzi, Henries
ENTITLED, AN ACT RELATING TO EDUCATION -- STUDENT COMPUTER DEVICE PRIVACY (Prohibits an educational institution or school district from accessing or using location data for tracking a student's institutional device or personal device, except in limited circumstances.)
```
So I think this …
> RI: split bill title into title and abstract

- scrapers/hi/bills.py
I found a listing page on HI's site that includes all the bills with last update date.
This allows you to do a scrape with a 'days ago' argument, scrape_since=N and only scrape bills with updates in the last N days.
This drastically cuts down on the volume of proxied requests needed to keep up in HI. You should set it to at least two though, as they do sometimes sneak bills super late their time.
I'm open to renaming or better documenting that argument flag, just passing this for feedback.
> HI: Add option to scrape subset of days

- scrapers/mn/bills.py
Scrapes have been failing with bad vote links, removing so can get the bill data online while I work on a real fix
> MN: temp remove senate votes

- scrapers/ks/bills.py
- scrapers/ks/ksapi.py
The old KS scraper would sometimes start dying at the end of session because the state's API listing endpoint would begin to time out.
This scraper is based on the RSS listing page (which seems to be fast), and then the individual bill API pages, which have enough info to scrape w/out loading the HTML pages and getting banned.
NOTE: This removes the votes scraper, whose data isn't available in the API. I'm hoping we can create a new one and get that data somehow without scraping the HTML pages.
> WIP: KS: new RSS/API based scraper

- scrapers/de/bills.py
[HB 282](https://legis.delaware.gov/BillDetail?LegislationId=140826) takes over a full minute to load so bumps up the timeout & retries on DE Bill scraper
> DE: Increase Timeout

- scrapers/wa/events.py
Missing events because Senate isn't returning any meetings so it's raising EmptyScrape too early
> WA: update urls & move EmptyScrape to later to catch properly

- scrapers/oh/bills.py
I found that the number of bills in a local scrape far exceeded the number of total bills we had in the DB, so took a closer look. The `https://search-prod.lis.state.oh.us/solarapi/v1/general_assembly_{session}/resolutions` endpoint is currently returning a significant number of duplicate resolutions, seemingly with no substantive difference. This change filters those out before doing into detailed bill processing.
> OH: filter out duplicate bills coming back from source API

- scrapers/usa/events.py
I'm sick of the Atomic Block warnings on scrape, so cutting down the length of event names in both chambers & adding the full text as a description.
> USA: Cleanup Event Titles

- scrapers/in/bills.py
Looks like the `_process_votes` function still works if it got called. The API also looks like it changed the formatting on the Bill Detail JSON to just list all the `rollcalls` together so can just pass that in.
> IN: add Votes back

- scrapers/wy/events.py
WY Events scraper was adding agenda items with name/identifier that looked like `SF0013`, these do not match bill numbers in this jurisdiction, which cause later pipeline steps matching events to bills to fail. The fix presented here is to separate out the numerical part of the "bill number" and strip leading zeros before adding the agenda item.
> WY Events: Strip leading zeros from bill number

- scrapers/wv/bills.py
Had a sentence catching as an absent vote since it started with "A ", checks that the `name` is uppercase before counting votes to avoid this.
> WV: Name Check on Senate Votes

- scrapers/il/bills.py
Removing `(Re-r|R)eferred to` since it only captures on assignments/rules when we really want to catch the committee assignment that uses `(Re-a|A)ssigned to` and also updates the `reading-3` to not catch actions like `RULE 2-10(A) THIRD READING DEADLINE ESTABLISHED AS APRIL 28, 2023`
> IL: Action Classification Tweaks

- scrapers/tn/events.py
Adds a dedupe key based on the meeting id listed on the agenda urls since we've been failing validation with two Senate Government Operations Committee meetings 3-13 at 8:30 am but they do have different agendas ([first](https://wapp.capitol.tn.gov/apps/videocalendars/VideoCalendarOrders.aspx?CalendarID=31469&GA=113) & [second](https://wapp.capitol.tn.gov/apps/videocalendars/VideoCalendarOrders.aspx?CalendarID=31524&GA=113))
> TN: Add Event Dedupe Key 

- scrapers/mn/events.py
Testing that the committee names aren't just the chamber names, but removing the "Senate " before for now to test since there are so many more Events coming in with special forces & councils.
> MN: Event Name Checks

- scrapers/nj/events.py
Was failing import because the Senate Judiciary Committee had a hearing & meeting scheduled the same day so adds a `dedupe_key` that includes the committee name, `record['type']` that would be `Hearing` or `Meeting`, and date.
> NJ: Add Event Dedupe Key

- scrapers/hi/bills.py
Scrape is failing on validating [HB 2029](https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=HB&billnumber=2029&year=2024) since there are 2 actions on 3-19 that are "PASSED, WITH AMENDMENTS" but there are different yes/no vote counts, so adding a `dedupe_key` that includes those so validation/import passes
> HI: add dedupe_key to vote events

- scrapers/mo/bills.py
There's a [House bill](https://documents.house.mo.gov/xml/241-HCB1.xml) without a LongTitle so setting one on an `IndexError` exception
> MO: add exception if no LongTitle

- scrapers/ks/__init__.py
- scrapers/ks/votes.py
I reached out to the API team at KS to ask if they had any plans to add Vote data to the API or would be open to adding a link to Votes in with Bill Actions on the Detail page, but for now just pulled back the Vote logic from the old Bill scraper since we have users anxious to get that data. Did add the RSS list page logic to get the Bill Ids since that's way faster & less on their systems, but it is hitting the html site. Planning on running ~once a day, so shouldn't be too much & hoping they get back to me with a different solution.
> KS: Vote Scraper

- scrapers/tn/bills.py
Only pull votes for the current bill, not the related one in the other chamber. Making duplicate votes.
> TN: don't pull votes on related bill

- scrapers/ct/votes.py
Currently failing vailidation with SB 126 having 2 votes ([57](https://www.cga.ct.gov/2024/vote/s/pdf/2024SV-00057-R00SB00126-SV.PDF) & [58](https://www.cga.ct.gov/2024/vote/s/pdf/2024SV-00058-R00SB00126-SV.PDF)) on the same day a few minutes apart. Should work since the pdf links are different.
> CT: add dedupe key to vote with url

- scrapers/nd/bills.py
North Dakota bills scraper was rewritten to access bill data from [their new API](https://ndlegis.gov/legislative-api-documentation).
- new scraper extracts from JSON rather than from HTML, as before.
- still written using `spatula` library
> ND bills: new scraper from API

- scrapers/ga/bills.py
- setup.cfg
Parsing of the vote listings array on Georgia bills data was only accessing the first vote event.
These changes address this by going another level down into the nested data before iterating to retrieve the vote data and create each vote event object.
> GA: fix parsing of nested vote listings

- scrapers/ga/bills.py
Some of the Votes are on the same bills/day from the bill text, so adding which bill the vote came in on to dedupe key
> GA: add dedupe to Votes

- scrapers/ok/events.py
Looks like they're implementing a [new website format](https://oksenate.gov/committees/meeting-notices/joint-committee-pandemic-relief-funding-health-and-human-services-10) (& maybe internal api looking at the network requests?) for OK Senate site. Getting that new scraper scoped out but commenting it out for now so we don't miss House Events
> OK: Temp Remove Senate Event Scrape

- scrapers/ok/events.py
[1192](https://github.com/openstates/issues/issues/1192)
- Just changed URL to new website URL. The old scraper works for new website.
> OK: New Senate Events Scraper

- scrapers/ok/events.py
There are [some events](https://accessible.oksenate.gov/committees/meeting-notices/senate-legslative-session) that don't have a link to a specific location & just say "Senate" so adding that as a default for when `IndexErrors` come up on that xpath
> OK: add IndexError default on Senate Events

- scrapers/va/events.py
Recently, at least one VA event had a location name greater than 200 characters. Cases like this leads to ingestion failure due to the [max length limit on this attribute of the event location](https://github.com/openstates/openstates-core/blob/98d6d1030cb7c81280a725ba6e0760dfb55c3a95/openstates/data/models/event.py#L35).
This PR ensures event location name is shortened, when necessary, to below the limit.
> VA: location name limit < 200 chars

- scrapers/mo/events.py
This PR modifies the regex pattern used to capture additional formats of multiple bills on committee hearing agendas.
> MO: events multi bills regex string captures more formats

- scrapers/fl/bills.py
Primary change is a modification of the url that is constructed from input in the `HouseSearchPage()` object.
- The HTTP request of the source did not have appropriate headers, and consequently was not getting the page data which would include the target bill page link, leading the `XPath()` selector to fail.
- This PR utilizes a `URL()` object to add the appropriate headers for the `GET` request to get the full page data necessary.
Secondary change adds the `media_type` for bill analysis documents, which was discovered to be missing while doing spot checks on the bill JSON data.
> FL: add headers for bill page request

- scrapers/nj/bills.py
Scraper is failing out because `Not rep./Acs` is not an option on Votes
> NJ: add another committee vote motion option

- scrapers/il/bills.py
Just checking if lint is weird on the other branch or all of em
Now that session is over, I'm experimenting because some Bills still have Actions missing. Skipping votes for run time cut down (will add it back after this tests right), but adding the committees as actors is causing a bunch of Import errors (below) locally & commenting it out makes it work. Think it should be reworked to be add committees as a related_entity to those actions instead.
> IL: temp remove committee parsing & votes

- scrapers/usa/events.py
This is currently causing an import error for USA events
> USA: truncate event document note, which can exceed column length

- scrapers/de/bills.py
Makes it a bit easier to debug & import is failing right now because there's some votes with the same id & chamber but different bills so hoping this clears up that issue
> DE: vote dedupe key more specific

- scrapers/de/bills.py
[SB 15](https://legis.delaware.gov/BillDetail?LegislationId=141235) has a really long string instead of an effective date
> DE: check for long string instead of date on eff_date

- scrapers/ne/__init__.py
Having issues importing bills since there are bills with the same number in each session ex: LB 6 in [regular](https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=50032) vs [special](https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=58102), so just not scraping regular session that's inactive
> NE: set regular session inactive

- scrapers/il/bills.py
- [#1213 Sponsorship Cleanup](https://github.com/openstates/issues/issues/1213)
- I've checked the current scraper and found that we don't need refine_sponsor_list function because the sponsor list in the source website is the last list after happened all actions. so the first sponsor is the Chief Sponsor and others are Co-sponsors. Please let me know if you have opinion for my thought.
> IL: Sponsorship Cleanup

- Dockerfile
- docker_entrypoint.sh
- poetry.lock
- pyproject.toml
This change allows passing GOOGLE_APPLICATION_CREDENTIALS to the openstates-scraper container as the secret itself, rather than only a filepath to the secret (the latter requires mounting the secret on the container, which is trickier). 
This makes it easier to use the full-scrape archive (`--archive`) flag
> Fix usage of --archive in container by using entrypoint to handle GCP credentials

- scrapers_next/va/people.py
This PR updates the Virginia people scraper to:
- get the new session data
- update handling for phone and address retrieval, as prior code was not getting capitol office phone numbers
> VA people: new session id, fix phone and address handling

- scrapers/wy/__init__.py
@NewAgeAirbender we usually don't do this but I don't see a good source for session years right now so i vote we hotfix it until the API stabilizes.
The website itself is pulling the values from a minified javascript bundle whose URL changes.
> WY: hotfix for dates, until api stablizes

- scrapers/de/__init__.py
https://legis.delaware.gov/docs/default-source/default-document-library/legislativecalendar-2024.pdf?sfvrsn=76ff8938_2
https://legis.delaware.gov/SessionCalendar
https://ballotpedia.org/2024_Delaware_legislative_session
> DE: Fix end date on 2023-2024 session to improve legislator matching

- scrapers/ca/events_web.py
It's splitting up "october" & failing validation
> CA: check for actual 'to' instead of splitting 'October'

- scrapers/az/__init__.py
- scrapers/id/__init__.py
- scrapers/mo/__init__.py
- scrapers/va/__init__.py
- scrapers/vt/__init__.py
Just getting rid of some `ignored_sessions` that are scraped & swapped the `classification` for a regular session in VA
> Multi: metadata cleanup

- scrapers/dc/events.py
They've updated how they post related bills on events. 
Heads up @showerst, I think it may also be worth moving over to the API for Events soon, looks like we're missing a bunch of them because the calendar on the site vs the file is different. Can access the same data with the API key with an event list & detail page.
`POST https://lims.dccouncil.gov/Hearings/API/Public/GetUpcomingHearings`
`GET https://lims.dccouncil.gov/Hearings/API/Public/GetHearingDetailsForPublic/503`
> DC: update bill check on events

- scrapers/ak/bills.py
We've already got it as a committee above in the check, so just need to set it as an "organization" instead of "person" in `add_sponsorship`
> AK: fix sponsorship type

- scrapers/wa/bills.py
WA snuck a couple of test bills into their production site. They've since been deleted from the WA site, but just avoid scraping them in the future.
> WA: Skip their test bills

- scrapers/ca/events_web.py
I see this scraper issue in CA events. Soria and Papan are 2 chairs for "Agriculture"  and "Water, Parks and Wildlife" committees. But the scraper returns them are 1 participants 'Soria, Papan'. Can we create a ticket for a fix.
> Update CA event scraper

- scrapers_next/va/committees.py
This PR refactors the Virginia committees scraper to bypass the frequent source errors that were occurring due to a confluence of how the page was structured and how spatula seeks sources.
Note: while the `CommitteeList()` class will get all the committees, the `FindSubcommittees()` class gets all the subcommittees. They are not linked in one action, and the job runner will need to execute those separately (i.e. include a `scrapers_next.va.subcommittees` execution for the ` FindSubcommittees()` class.
> VA committees refactoring, bypassing source errors

- scrapers/il/bills.py
We found some examples where the `reading-3` classification was being applied to actions related to scheduling/postponing the 3rd reading (but did not amount to the bill actually having a 3rd reading).
> IL: Narrow 3rd reading classification to exclude scheduling changes

- scrapers/va/__init__.py
This is a temp fix until we get the new site scraping.
> VA: pull session listing from legacy site

- scrapers/nj/bills.py
Some real bills have been blocked from being saved to the DB by "phony bill" detection logic that appears it was added like a decade ago :) I spot checked a bunch and none of the missing bills seem to be "phony."
> NJ: Remove ancient 'phony bill' logic that is blocking real bills

- scrapers/usa/bills.py
cc @showerst  in case you are doing event collation and this might impact you
The USA bill scraper has been yielding hearing events related to bills since April. However recently I have noticed a number of `DuplicateItemError` in our data processing pipeline, I believe because these events have sparse information and generic titles often, thus yielding more frequently detected duplicates.
My goal here is to reduce these duplicates, but also provide a more helpful title to the event.
> USA: reduce duplicate 'Subcommittee Hearings Held' events

- scrapers/wa/bills.py
We were getting string repeats concatenated into bill version notes field, like `Second Substitute Substitute Substitute Substitute Substitute Second Substitute Joint Resolution` because the loop didn't reliably initialize a variable. Some bill versions failed to import because the notes got so long, which is how I noticed.
A default of "Passed Legislature" is a little weird for passed bill versions ... but to fix we'd need to scrape each bill version page and hunt around for the right text. Which I don't think is really worth it but could be a good improvement in the future.
> WA: fix bug where bill version notes are long repeated strings

- scrapers/md/bills.py
- scrapers/wy/bills.py
In Maryland House bills can only be sponsored by House Members and the same applies to Senate bills. [Example - HB0901](https://mgaleg.maryland.gov/mgawebsite/Legislation/Details/hb0901?ys=2024RS).
* Adding chamber will help improve matching, especially in Maryland where several legislators share last name.
> MD & WY: add chamber to bill scrapers add_sponsorships()

- scrapers/ga/events.py
Addresses issue:
- https://github.com/openstates/issues/issues/1241
> Fixing GA Events Scraper

- scrapers/mo/bills.py
MO: House and Senate source website are quite different. House Sponsors mostly have full name as seen [here](https://documents.house.mo.gov/xml/241-HB2.xml) while senate can sometimes be just the last name [for example](https://www.senate.mo.gov/24info/BTS_Web/Bill.aspx?SessionType=R&BillID=11). So the change only apply to Senate Sponsor scrape.
> MO: Improve Senate sponsor psuedo_person_id

- scrapers/tx/events.py
Title in legislators name causes event participants mismatch for TX.
> TX: strip title from event participants name

- scrapers/ny/events.py
* Strip resulting committee names of leading and trailing white spaces
* Remove the trailing single character from bill_id
There might be a better place to make this change like in [core](https://github.com/openstates/openstates-core/blob/main/openstates/utils/transformers.py) but not sure.
CC: @jessemortenson
> Update NY event organization names

- scrapers/va/bills.py
VA vote events were failing to import with errors like:
```
INFO - [base] openstates.exceptions.DuplicateItemError: attempt to import data that would conflict with data already in the import: {'identifier': '', 'motion_text': 'Reported with amendments', 'motion_classification': [], 'start_date': '2024-01-31', 'result': 'pass', 'extras': {}, 'dedupe_key': 'H092024-01-311', 'legislative_session_id': UUID('27766658-dae9-4950-8565-ca0a88ea931e'), 'organization_id': 'ocd-organization/0c3daf42-2835-49cf-8f58-b1d771dae687', 'bill_id': 'ocd-bill/61eb4a36-d3f6-4855-a913-7f45613910e2', 'bill_action_id': UUID('37298987-68ef-4d79-99d8-6a8dec9fa5e2')} (already imported as Reported with amendments on HB 582 in Virginia 2025 Regular Session)
INFO - [base] obj1 sources: …
```
> VA: Fix duplicate vote bug with votes import

- scrapers/pa/bills.py
All Committee Vote URLs that look like https://www.palegis.us/senate/committees/roll-call-votes/vote-summary?committeecode=21&rollcallid=60 are returning HTTP 500 for a while.
> PA: temporarily disable committee vote ingestion due to site errors

- scrapers/nv/bills.py
- scrapers/usa/bills.py
USA: bill document note can be over 300 characters, causing DB VARCHAR length error
NV: at least one bill has two votes on the same day with the same motion text (https://www.leg.state.nv.us/App/NELIS/REL/82nd2023/Bill/9667/Votes), so add a suffix when this is encountered.
> USA/NV: fix small bugs affecting bill import

- scrapers/ar/bills.py
- scrapers/fl/bills.py
- scrapers/ia/bills.py
- scrapers/id/bills.py
- scrapers/ks/bills.py
- scrapers/ma/bills.py
- scrapers/nc/bills.py
- scrapers/ne/bills.py
- scrapers/nv/bills.py
- scrapers/sc/bills.py
- scrapers/sd/bills.py
- scrapers/vt/bills.py
- scrapers/wi/bills.py
- scrapers/wy/bills.py
Added `entity_type="organization"` option across multiple jurisdictions
> Add entity types multi jurisdictions

- scrapers/in/events.py
Import was failing due to events with same name/date/location. These were all-day events (no start time) with a "customstarttime" that narrative-describes when the event will start ('after X adjourns' etc.)
> IN: fix import duplicates by using unique meeting link as dedupe key

- scrapers/hi/bills.py
HI HTMl is weirdly variable, found a couple cases where the selector was failing to grab versions. Also the "header version" URL is no longer accurate, was creating duplicates in my test scrapes.
> HI: fix bugs in bill version selection, correct header version URL

- scrapers/usa/bills.py
Implementing a suggestion that was in the scraper as a TODO: use requests library directly to avoid long retry cycles on a fraction of URLs. The scrape for 118 sometimes is taking longer than 24 hours, my theory is that the long retry/backoff sequences are contributing in those cases.
Also gets rid of hack for shortening bill doc note strings, which should now be handled at import time by os-core.
> USA: eliminate retrying on HTTP error to speed up scrape

- scrapers/wa/__init__.py
`get_session_list()` for WA uses https://leg.wa.gov/bills-meetings-and-session/bills/ as source data, and the selector for the element AND the value/label pairs on that page have changed. 
Also adds the 2025-26 session to the list, setting as inactive for now. Expect to activate Dec 2 (https://app.leg.wa.gov/billinfo/prefiled.aspx?year=2024)
> WA: adjust session list selector, add 2025 session (inactive)

- scrapers/ok/events.py
At least one OK event has an associated PDF that 404s, and this is causing the scraper to fail. Fix by swallowing HTTP error on PDF downloads, warning in log instead.
> OK events: swallow exceptions for 404s on agenda PDFs

- scrapers/pa/bills.py
Hey there this is my first PR on this project so lmk if I'm doing something wrong here!
I noticed during running scraping for PA that it seems there can be times where the roll call votes include "sessYr" but it looks like we are looking for "sessyr", and thus we don't see it and attempt to add it, leading to a 404.
Example of log output from the scraper:
```
00:04:35 INFO scrapelib: GET - 'https://www.palegis.us/senate/committees/roll-call-votes/vote-list/vote-summary?committeecode=17&rollcallid=1378&sessYr=2023&sessInd=0&sessyr=2023'
00:04:37 WARNING openstates: There was an error in scraping https://www.palegis.us/legislation/bills/2023/sr359: Retry 1: Error: 404 while retrieving https://www.palegis.us/404
```
Seems like we attempted to work around this with a recent PR here: …
> Catch param case sensitivity on PA vote parsing

- scrapers/ga/__init__.py
- scrapers/ga/util.py
There are no bills posted on https://www.legis.ga.gov/search?s=1033&p=1 yet, and the SOAP service returns an empty string if the scraper is run on 2025 data. So keeping the new session Inactive for now.
> GA: prep 2025 session, inactive for now

- scrapers/me/__init__.py
Session has been added to https://www.mainelegislature.org/LawMakerWeb/advancedsearch.asp
No bills yet, but session starts Dec 4, so setting as active
> ME: add 2025-2026 session

- scrapers/ca/__init__.py
Weirdly CA has a special session overlapping with the start of regular session https://www.gov.ca.gov/2024/11/07/special-session-ca-values/
> CA: add 2025 special session 1

- scrapers/mt/events.py
MT events scraper hits API URLs that can list an event more than once. The duplicates provide alternate media URL (video vs. audio, for example). Code change here combines those into existing events before yielding out.
> MT: fix import error due to duplicate events

- scrapers/mt/events.py
... so changing logic to match os-core def of duplicate. This is to handle a case in the source where there are duplicate of the same event title/time, with no other info that could be used to discriminate which is the "true" and which the "duplicate" instance.
> MT: events: os-core does not consider location for duplicates

- scrapers/mt/__init__.py
- scrapers/mt/bills.py
It looks like the Montana legislature API has two sets of endpoints:
- Ones with `archive` in the endpoint URL, which were used by previous versions of the scraper, such as `https://api.legmt.gov/archive/v1/sessions`
- Ones without, which seem to be what the current Montana website uses for fetching content for end users, such as `https://api.legmt.gov/legislators/v1/sessions`
It's a bit messy from the outside, not sure if there is an insider concept i'm missing. But for example the 2025 session does not show up in the list at the first URL above, and ONLY the 2025 session shows up at the second URL. Which smells to me like the `archive` endpoints are deprecated moving forward.
Made an attempt to split the scraper logic so that it can still be used to scrape old sessions. There is a …
> MT: enable 2025 session prefiles, implement new API endpoints

- scrapers/mt/bills.py
Grabs the LC draft bill version document, if available.
> MT: add bill versions for LC draft versions

- scrapers/il/__init__.py
- scrapers/il/bills.py
- scrapers/il/events.py
[1271](https://github.com/openstates/issues/issues/1271)
- rewrite bill scraper for new website
- rewrite event scraper for new website
- update __init__.py
> IL: Bill scraper rewrite to new beta site

- scrapers/ut/__init__.py
- scrapers/ut/bills.py
Looks like UT webmaster has had some fun implementing a new API. Appears to me that 2025 session is using that API to dynamically render bill detail pages, which otherwise look identical to older sessions. But older sessions are still rendering static-ish HTML.
This scraper is going to need more work as we get more UT data in here:
- Actions: I don't have much base data to work with, so not sure how much of the existing actor classification logic will work or need to be re-implemented. Classifications may also need a look.
- Votes: I don't have any vote data here yet, so no Vote logic is implemented
> UT: partial rewrite to support 2025

- scrapers/in/__init__.py
- scrapers/in/apiclient.py
- scrapers/in/bills.py
- scrapers/in/committees.py
- scrapers/in/events.py
IN API "launched" and changed URL to no longer have "beta" in it. 
- Changes API URLs in scrapers
- Also fixes an issue where vote journal pages are convoluted to fetch
- Take advantage of the API providing vote counts on roll call votes, checking against the numbers we parses out of PDF
> IN: change IN API URL due to launch, fix vote PDF fetching

- scrapers/fl/bills.py
FL started to throw TLS validation errors on another URL, so disabling again.
> FL: disable TLS/SSL verification on another URL

- scrapers/in/bills.py
- Removes a few cases where we were catching some text after the committee name
- Gets the committee name as spelled in the description (ie with case) rather than all lowercase
> IN: bills improve committee recognition around actions

- scrapers/in/bills.py
Fixes a discrepancy between the IN API and the IN Website in how concurrent resolutions are identified. This prefers the website, assuming that is more canonical re: how real people talk about these.
IN API:
- HC 1
- SC 1
to match website:
- HCR 1
- SCR  1
> IN: correct concurrent resolution bill identifiers to match website

- scrapers/ct/__init__.py
- scrapers/dc/__init__.py
- scrapers/ma/__init__.py
- scrapers/ny/__init__.py
- scrapers/ri/__init__.py
Adds prefiles for NY, some historical MA sessions, and placeholder sessions for CT, DC, and RI.
> Jan 1 Session Additions

- scrapers/tx/votes.py
We were still getting some vote events from 88 that were marked incorrectly as failed votes. In those cases the regex did not find the text that explicitly says passed/failed. But the counts were there and clearly indicated passage. So using the vote counts as a fallback.
> TX: Votes: use vote counts to determine passage as fallback

- scrapers/usa/__init__.py
- scrapers/usa/bills.py
Moved chamber check higher to avoid a committee action that was blowing up the actions parser. TODO: sometimes those committee actions apparently do contain unique information, how do we parse the chamber out of them correctly and avoid dupes? See 
https://www.govinfo.gov/bulkdata/BILLSTATUS/119/hres/BILLSTATUS-119hres10.xml
https://www.congress.gov/bill/119th-congress/house-resolution/10/all-actions
> USA: 119th congress

- scrapers/ma/__init__.py
Massachusetts: The 194th session end date had an invalid date of 2025-11-31. This was changed to the correct end date of 2026-07-31. Here's the source of that information:
https://malegislature.gov/ClerksOffice/Senate/Deadlines
> MA: Fix invalid 194th session end date

- scrapers/nh/bills.py
NH scraper was failing on HTTP errors trying to reach URLs such as https://www.gencourt.state.nh.us/bill_status/legacy/bs2016/bill_status.aspx?lsr=0174&sy=2025&txtsessionyear=2025
Server would display "Server Error in '/bill_status/Legacy/BS2016' Application."
Seems like adding another query param fixes it (following example from clicking Bill Status link on https://www.gencourt.state.nh.us/bill_status/legacy/bs2016/)
> NH: bills: fix broken request for resolution details page

- scrapers/tx/votes.py
@showerst well I broke the session naming convention in TX for this year (`89R` instead of `89`). Was that a dumb decision? I'd like to blame it on late night coding or something but the commit log says otherwise. 
Think I should revert the session identifier to `89` or do this fix (and any other likely following ones to adjust other assumptions about the session identifier string)?
> TX: votes: fix session year selection bug

- scrapers/hi/__init__.py
- scrapers/hi/bills.py
- scrapers/hi/events.py
- scrapers/hi/utils.py
I spoke to the Hawaii capitol webmaster, and it turns out they maintain a separate mirror of the website that's not behind cloudflare. https://data.capitol.hawaii.gov/
I swapped in that url for the scrapers, but left the source URLs pointing to the originals. I was a little torn with what to do with versions, but since I figure they'll usually need downstream processing I went ahead and linked to the cloudflare free version.
This also activates 2025, because they've got some prefiles up.
@jessemortenson tag FYI.
> HI: Set 2025 to live, and update scraper to use data site

- scrapers/nd/bills.py
Submitted this as a bug to the ND webmaster, seems they are double-displaying "Final Passage" roll calls when one of the votes should actually be a committee report (looking at journal text)
> ND: Fix duplicate votes being scraped

- scrapers/va/events.py
Adds a number of sub-page parsers to the VA event scraper, so that we can pull full agendas and link bills.
> VA: event scraper overhaul

- scrapers/id/events.py
Apparently events don't validate that attachment urls are not relative?
> ID: events: make links absolute

- scrapers/va/events.py
Quick fix for current error in VA events. This doesn't fix the missing or/and invalid event bill IDs.
> VA event: Fix date parse error

- scrapers/va/events.py
It seems like the 2 cases with invalid `when_time` the `when_date` actually had a reasonable datetime object. `'2025-01-30T16:30:00'` So I decide to modify it like this.
Note: In line 160 above we were already doing this. `when_date = row["ScheduleDate"].replace("T12:00:00", "")`
Let me know if I should just stick to the default.
> VA: event add all_day flag

- scrapers/mi/events.py
Name format changes in some cases for Chair. Just going to drop `Sen. ` or `Rep. `
> MI Events: Update participants name cleanup

- scrapers/sc/events.py
If there are multiple event locations like this  `Blatt Room 112 And Breakout Rooms: Blatt 108, Blatt 305 Blatt 317, Blatt 318, Blatt 321,` lets just replace only one Blatt with the full address.
> SC Events: Update Event location

- scrapers/wv/events.py
There is a test event [page](http://www.wvlegislature.gov/committees/senate/senate_com_agendas.cfm?input=test&Chart=enb) we should be ignoring
> WV Event: Ignore test event page

- scrapers/nh/bills.py
Bill Status link doesn't work for current session. So I am adding the Bill Docket link.
> NH: Add a second source link for bills

- scrapers/me/events.py
Also some refactor into a couple methods to make this code a bit more organized and legible.
Main change here is setting url param `OnlyPHWS` to `false` instead of `true` in the main events request. Added logic to deal with the additional fraction of events, trying to match those to committees, and excluding some events that def are not official public hearings.
> ME: events: attempt to get more committee events

- scrapers/al/bills.py
CC: @jessemortenson . It looks like "birs" data does not have `url` in it. `description` also changed to `matter`. We will probably see as things develop.
> Some 'birs' might not have url

- scrapers/fl/__init__.py
Added FL 2025 Special Session C. [Started Noon today ](https://www.flsenate.gov/PublishedContent/Offices/2024-2026/President/Documents/Special_Session_C_Combined_Files.pdf)
> Add FL 2025 special session C

- Dockerfile.california
Seem Dockerfile.california is failing `Error: The current project could not be installed: No file/folder found for package openstates-scrapers`. Adding `--no-root`. CC: @jessemortenson
> CA: Update Dockerfile

- scrapers/in/bills.py
I think this was intermittent, but seems like a good case for a warning instead of halting scrape.
> IN: bills: do not fail entire scrape when one vote doc is not parsed

- scrapers/nv/__init__.py
- scrapers/nv/bills.py
We have been seeing intermittent failures on bill scrapes due to HTTP 5XX errors on random-ish requests, trying to reduce those
> Nv attempt to reduce scraper fails

- scrapers/mo/bills.py
https://documents.house.mo.gov/xml/251-HB2.xml for example just has empty `<Witness />` tag in its XML
> MO: bills: handle case where no witness doc found (indexerror)

- scrapers/utils/lxmlize.py
The shortcut methods for grabbing urls (self.lxmlize and url_xpath) weren't checking for a `VERIFY_CERTS` env var, so you couldn't globally set verify to false using the env var in the scrapers that used these methods. This should fix that that.
@jessemortenson courtesy ping, i'm changing the default function args for lxmlize and url_xpath from True to None, but then defaulting the `verify` keyword to `True` lower down in the code, so behavior shouldn't change.
> xlmlize utilities should respect VERIFY_CERTS

- scrapers/fl/bills.py
- scrapers/fl/utils.py
This PR enhances the Florida scraper to handle connection issues that occur when the state website blocks our scraping attempts. After about 15 minutes of continuous scraping, the FL website starts abruptly closing connections without responses, effectively blocking our data collection.
Key improvements:
- Added retry logic with exponential backoff to gracefully handle connection failures
- Implemented user agent rotation to make our requests appear to come from different browsers
- Added random delays between requests to mimic human browsing patterns
- Created a circuit breaker pattern that pauses scraping after consecutive failures
- Added periodic connection pool resets to establish fresh connections every 10 minutes
- Specifically targeted the "Remote end closed connection without …
> chore: handle blockages from fl website

- docker_entrypoint.sh
- scripts/log_external_ip.py
In this age of more states adding anti-bot measures to their web services, it seems like it could be useful to just have the external IP address used by the scraper logged out on every run. Florida just responded by asking for an IP address re: their blocking behavior this week, for example. 
I added two checks here, one using `curl` and one using python `requests` since there might be a difference if `HTTP_PROXY`/`HTTPS_PROXY` is set. 
I don't 100% love using a third party service (https://ipecho.net) but also that's a lot easier than having infra for our own. I tried to double check bash recommendations for securely operating on unknown content.
Making you as a reviewer here @showerst in case this would introduce any wrinkle/concerns for you.
> Log external IP of each scraper run to assist with debug

- scrapers/ia/bills.py
IA bill scraper still intermittently fails on HTTP disconnects. Seemed worth a hacky attempt to add in the countermeasures that Sogo implemented in FL bills here and see how that works.
Sogo - how incompetently did I adapt here? :)
If this improves in both cases, then probably a good candidate to refactor to a lower level in scraping.
> IA: bills: improve countermeasures vs HTTP disconnect

- scrapers/nm/bills.py
This code is not in https://www.nmlegis.gov/Legislation/Action_Abbreviations yet. So I improvised here.
> NM bills: add 7672 action code.

- scrapers/ks/bills.py
We've been seeing persistent 500 errors from this one API path over the last day, temporarily working around it
```
scrapelib.HTTPError: 500 while retrieving https://www.kslegislature.gov/li/api/v12/rev-1/bill_status/HCR5011/
```
> KS: workaround for persistent 500 error on HCR 5011 from KS API

- scrapers/fl/bills.py
This is for a bill filed in error: https://flsenate.gov/Session/Bill/2025/7023/ByCategory/?Tab=BillHistory
Could try to omit this ... but it is listed in search results, and has an action, so I'm inclined to just ingest it. Would need a little bit of a refactor to omit it entirely.
> FL: bills: fix bug when there are no sponsors

- scrapers/mt/bills.py
MT scrapes are getting longer, so more painful to catch and restart when these random new vote codes pop up. At this point rather mistakenly categorize some into `other` than have scrapes fail.
> MT: add abstain vote type, stop throwing exception on new types

- poetry.lock
- pyproject.toml
With this bump in `openstates` version, scraper output will now have metadata `jurisdiction` and `scraped_at` keys like;
```
...
"jurisdiction": {"id": "ocd-jurisdiction/country:us/state:al/government", "name": "Alabama", "classification": "state", "division_id": "ocd-division/country:us/state:al"},
"scraped_at": "2025-04-14T19:59:48+00:00",
...
```
See related [version](https://github.com/openstates/openstates-core/pull/171).
> Bump Openstates version

- scrapers/in/bills.py
IN scraper was failing with `AssertionError: Missing bill passage type` due to vote PDF having text `Rejected` that was not yet in expected types.
> IN: bills: fix vote processing bug on 'rejected' status

- .dockerignore
- scrapers/ca/bills.py
- scrapers/ca/ca-entrypoint.sh
GRP is not a chamber-specific bill type, so I have it associated with upper only so that it is not ingested twice. But that is a little arbitrary.
> CA: support GRP bill, make CA docker entrypoint more flexible

- scrapers/ut/__init__.py
2026 session popped up on source page's session list, adding as inactive for now
> UT: add 2026 session (inactive)

- scrapers/il/bills.py
Pretty significant bugs in IL vote events:
1. The "actor" on the vote event was being recognized and defaulting to lower/House in all cases
2. At least a thousand false "fail" results were recorded, because vote counts were not getting recognized
> IL: votes: fix incorrect actor, incorrect result and missing counts

- scrapers/usa/events.py
The US events scraper now pulls additional hearing testimonies, witness lists, and (where available) video links, if passed a congress.gov api key.
@jessemortenson ping. `CONGRESS_GOV_API_KEY` is the ENV var to trigger the new behavior.
> USA: Upgrade events with congress.gov data

- scrapers/dc/__init__.py
- scrapers/dc/utils.py
Apparently the source of those 523 errors was hitting the API at `http` !!!!
> DC: fix API url from http to https

- scrapers/va/bills.py
Without this flag, our scrapes have been returning a set of bills that omits the "unsuccessful" ones. THis probably wasn't a huge deal because I presume not many of those bills got new activity after becoming unsuccessful, but still we should be getting full data here.
> VA: bills: include 'unsuccessful' bills in all scrapes

- Dockerfile.california
Starting seeing `Unable to locate package libgdal32` in Docker build for the California dockerfile
> CA: dockerfile failing to build, update libgdal version

- scrapers/sd/events.py
Events scraper failing because no regular session is marked as current in API response now that their special session is mostly prepped on their side. Seems like logic could be improved to still be able to grab correct session ID when a non-active reg session is selected.
> SD events: fix fetching API session ID

- scrapers/nm/bills.py
Status quo code would yield, for some bills, an "introduced version" that only had an HTML link (no PDF link to the same version). Code was skipping PDFs in `scrape_documents()`, but it's not clear to me why. 
Running the scraper without that skip-PDF logic goes fine, and yields both the PDF + HTML source links for each version.
> NM: bills: stop skipping PDF links for introduced bill versions
