openstates/openstates-scrapers

openstates/dc/bills.py, openstates/hi/__init__.py, openstates/hi/bills.py, openstates/me/__init__.py, openstates/me/bills.py, openstates/me/legislators.py, openstates/mt/bills.py
No bills or events posted yet, so they may need to be checked in on in January, but their interfaces don't appear to have changed since 2014's session.
=> HI: 2015 session ready

openstates/dc/bills.py, openstates/de/__init__.py, openstates/de/committees.py, openstates/hi/bills.py, openstates/mt/bills.py
There're some pre-filed Senate bills and one committee that are already up, and they seem to be working fine with our scrapers (and follow the same structure as the previous sessions). The legislators for the upcoming session are correct, per Ballotpedia's defeated incumbents.
=> DE: 148th session is up and scrapers are working

openstates/dc/bills.py, openstates/hi/bills.py, openstates/mt/bills.py, openstates/sc/__init__.py, openstates/sc/events.py
Legislators on website are updated, dealt with minor events scraper issue. Votes aren't up yet, but the system seems to have not changed; that scraper currently runs without issue.
=> SC: 121st session is a-go

openstates/me/actions.py, openstates/me/committees.py, openstates/me/legislators.py
Pull this in tomorrow, and then I'll do another quick verification of the production data (I've already spot-checked my local data with this new branch). And then we can check the Maine box!
=> ME: Edits made when verifying the production data for the new session

openstates/nh/__init__.py, openstates/nh/legislators.py
Bills scraper will throw an error since 2015 session bill status tables file is not yet available (gencourt.state.nh.us/downloads)
=> NH: 2015 session (legislators, not bills) ready for production

openstates/ne/__init__.py, openstates/ne/legislators.py
Bills (and thus votes) aren't up, and committee appointments haven't been updated.
=> NE: 104th Session is working for legislators

openstates/ct/__init__.py, openstates/ct/bills.py, openstates/ct/legislators.py
Legislators (and with them committees) updated, bills ready, _but_ events probably needs a rewrite
=> CT: 2015 Session cleared for takeoff

openstates/oh/__init__.py, openstates/oh/legislators.py
Bills not up yet in full (see spreadsheet note), committees not yet posted
=> OH: 131st Session can be run

openstates/sd/__init__.py, openstates/sd/legislators.py
Cleared for all (ie, both) scrapers to run
=> SD: 90th Session grrrrrrrrrr-eat!

openstates/ar/bills.py
added error handling to deal with links for votes that haven't been posted yet
=> AR: bills can now run

openstates/wv/legislators.py
Turn off bills for now though? no bills or votes yet
Also some committees don't yet have members, but most do
=> WV: legislators and some committees available

openstates/mn/legislators.py
Added 40, removed 40 #chaotic_neutral
=> MN: Rewrote House member scraping

openstates/md/__init__.py, openstates/md/legislators.py
Don't merge me
Waiting until forehand/minnick are out of the scraped data
=> MD: 2015 update

openstates/ut/__init__.py, openstates/ut/bills.py, openstates/ut/committees.py, openstates/ut/events.py
The bills scraper still needs some serious work, but I'm out for the rest of the week and the session begins tomorrow. If it's still unfinished when I get back I can wrap it up. Otherwise, thank you guys for the help!
=> UT: 2015 Session clear EXCEPT FOR BILLS

openstates/ma/legislators.py
The three missing legislators are now being scraped
=> MA: Special-cased new legislators who have barren member pages

openstates/ut/bills.py
=> UT: Bill scraping for new session is functional

openstates/vt/bills.py
Also constitutional amendments.
=> VT: Added resolutions to bill scraper

openstates/ak/__init__.py, openstates/ak/bills.py, openstates/ak/events.py, openstates/ak/legislators.py
No votes or documents have been created yet so the scraper might choke on those in the next week or two. However, the bill page hasn't changed since last session so we're probably all good!
=> AK: 29th Session cleared for departure

openstates/oh/legislators.py
House seems to have finished with subcommittees, Senate not, so this might crash again when the senate gets their subcommittees up.
Bills don't seem to be up yet.
=> OH: added new subcommittees

openstates/oh/legislators.py, openstates/vt/bills.py
to deal with legislators who have the characters "of" in their name.
=> VT: fixed bills scraper 

openstates/ky/__init__.py, openstates/ky/committees.py
Events not working because of Billy bug where committees don't resolve correctly when chamber is not passed. @paultag is filing that bug.
Also we're not currently parsing votes - I think the vote PDFs are terrible scans (example: http://www.lrc.ky.gov/record/15RS/SB1/vote_history.pdf)
=> KY: everything but events

openstates/il/__init__.py
session ids are not consecutive; fixed
=> IL: Session id fixed, everything should run

openstates/in/bills.py
bill scraper resistant to actions without date
NOTE: I have not fully run it from scratch locally because that takes like 5 hours. But it's definitely not *worse* than it was before
=> IN: bug fixed, should run for everything

openstates/nv/legislators.py
The old code was getting placeholder (fake) data. The legislator pages are now dynamic and fetch the details using AJAX. Updating.
=> NV: fix for legislator details

openstates/wy/__init__.py, openstates/wy/bills.py, openstates/wy/events.py, openstates/wy/legislators.py
One representative's name will have changed (I removed the "(SD02)" from the end of his name); will this require manual reconciliation?
=> WY: Bills and events back on-line

openstates/ak/bills.py, openstates/ak/committees.py
everything should be able to run. the more times I type "committee" the less able I become to spell it.
=> AK: added committee alias

openstates/de/legislators.py
now skips empty/blank legislators
=> DE: legislators no longer fails

openstates/tx/events.py, openstates/tx/votes.py
seems that TX has stopped adding new data to their FTP. These are the same reports, scraped off the web.
=> TX: bills/events can be turned on

openstates/nv/bills.py, openstates/nv/committees.py
Fix for [DATA-387](https://sunlight.atlassian.net/browse/DATA-387). Updated bills and committees. Looks like they're still upgrading and some info might not be available, added workarounds.
=> NV: scraper rewrite after site upgrade

openstates/mn/__init__.py, openstates/mn/bills.py, openstates/mn/votes.py
senate votes...not so much. they're buried in journals.
=> MN: house votes scraping

openstates/ri/bills.py, openstates/ri/committees.py
also fixed some name stuff for committee members.
=> RI bills should work

openstates/wv/bills.py, openstates/wv/legislators.py
=> WV: 2015 bill scraper now functioning correctly

openstates/nh/bills.py
I don't think there are any votes available yet so was unable to check them.
=> NH: bills should now work

openstates/ut/bills.py, openstates/ut/events.py
Related bills was an easy lift while I was in there, @paultag assume this is something we want?
=> UT: scraper should run, added related bills to events

openstates/md/committees.py
Also included committees labelled as "other" as joint committees bc most seem to have members from both parties.
Also also, this will cause us to create a bunch of duplicate committees that will presumably have to be removed.
=> MD: committee spacing issue fixed

requirements.txt
=> added chardet to requirements.txt

openstates/il/bills.py
Scraper can now run again. Senate committee vote PDFs were new and differently formatted, and were breaking the Bill scrape.
=> IL: Fixed bill datetime and vote column parsing

openstates/mo/legislators.py
=> MO: address/email cleanup

openstates/ny/committees.py
used to be pulling in "Twitter", "Facebook", "Contact", "RSS"
There was no obvious way to do this without hard-coding the bad ones, so if a rep comes up with some other service they want to link to, we'll have to add that.
=> NY: random links as comm members fixed

openstates/ks/legislators.py
Per SB ticket https://sunlightfoundation.supportbee.com/tickets/4412772
=> KS: Tweaked legislator photo collection to handle nicknames

openstates/wa/events.py
I'm NOT scraping related bills that are considered in the executive session, only in the public hearing. It is not the same set of bills. This is an easy fix/addition to line 87 though if we want to change.
=> WA: events working

openstates/id/committees.py
ID put some awesome extra lines in random places.
=> ID: won't fail

openstates/pa/legislators.py
Addresses in PA are kind of messy. Simplified the code and fixed some issues. I spot-checked a bunch of legislators, but it's possible that some different address-formatting issues will crop up.
(We're relying on a few words not being used in addresses, but I tried to be careful. If anyone moves their office to "Office Hours Rd." we're screwed.)
=> PA: fixed some address stuff, added social media

openstates/mo/committees.py
slight rewrite of senate comm scraper
=> MO: senate committees now scraping

openstates/ia/__init__.py
https://sunlight.atlassian.net/browse/DATA-422
=> IA: Fixing session start and end year

openstates/hi/events.py
event featuring a special temp committee was causing some trouble.
=> HI: events no longer crashing

openstates/mi/events.py
events happening at noon were throwing off strptime
=> MI: events no longer crashing

openstates/de/legislators.py
some weird stuff with phone numbers, also pulling in blank lines for vacant districts
=> DE: leg should stop crashing

openstates/or/__init__.py
Scrape bills from older sessions, beginning with 2007 Regular Session.
Also added scraping for more recent special sessions.
=> OR: Scrape historical sessions

openstates/ar/legislators.py
=> AR: legislators with no party now being saved

openstates/al/__init__.py, openstates/al/legislators.py
data should probably be double checked. this one was ugly.
also I'm stuck on e-mail addresses for reps.
=> AL: leg rewritten

openstates/ny/legislators.py
Upper parties now correct, per SB ticket, and lower members now have addresses, phones, and faxes again
=> NY: Cleaned party assignment, fixed address scraping

openstates/dc/bills.py, openstates/dc/committees.py
it's messy. If someone has time to kick the tires hard, that'd be really great.
=> DC: complete rewrite of bills scraper

openstates/dc/__init__.py, openstates/dc/events.py
=> DC event scraper

openstates/ia/votes.py
journal parsing makes me a little nervous because if they change one word we're in trouble, but I've put in an assertion and a warning which will hopefully help us figure it out quickly if that happens.
=> IA: pulling vote result from journal instead of count

openstates/nd/legislators.py, openstates/nd/votes.py
Warn instead of error when the count of names does not equal the total number provided
=> ND: Fix failure on odd vote counts

openstates/al/bills.py, openstates/al/legislators.py
Do not pull in without doing some spot-checking. I'll be doing this today as well, but my mind's a little melted from working on this site for this entire week.
=> AL: Rewrite for 2015 session finally complete

openstates/id/legislators.py
=> ID: leg scraper correctly pulls addresses

openstates/ut/bills.py
=> UT: Allow multiple primary sponsors

openstates/oh/bills.py
now using their undocumented api, here:
http://search-prod.lis.state.oh.us/solarapi/v1/
=> OH: bill scraper rewritten for 131st session

openstates/la/__init__.py
Please check code to ensure it is proper.
=> fixed Events.py for Louisiana 2015 legislative session

openstates/oh/bills.py
not erroring on things we don't really care about any more.
=> OH: bills scraper more robust to things that don't really matter

openstates/dc/committees.py
Gets rid of some weird naming, and hopefully will skip bad committees? None seem to be up there now, so can't be 100% sure on that.
=> DC: rewrote committees to hopefully skip bad committees

openstates/oh/bills.py
I feel a little ownership of Ohio now and can't help myself.
O-H
I-O
=> OH: added some bill types

openstates/la/events.py
If we want to run, we should turn off everything else. This was just a super easy fix - no actual formatting changes, just a few bad dates - so seemed worth it!
=> LA: event scraper now run-able

openstates/al/bills.py
This should fix some of the intermittent errors we've seen with Alabama.
=> AL: Improve testing for empty bill index pages

openstates/nv/bills.py
@mileswwatkins will have a field day that I willingly used a regex
=> NV: deals with petition bills and a few other tweaks

openstates/al/bills.py
B-b-b-b-baaaad, bad to the bone.
=> AL: Defend against bad BIR actions from the LIS itself

openstates/oh/bills.py
previously unseen bill passage status now added.
=> OH: bills should stop failing

openstates/al/bills.py
A non-breaking space was causing some issues in production, so hopefully this'll help it out. Was also able to remove some of our server requests.
=> AL: Improve unicode handling

openstates/la/legislators.py
Trivial change; @rshorey, could you run locally and then merge in?
=> LA: Remove dependency on BackoffScraper

openstates/ut/legislators.py
Was not scraping senators; now is using json to scrape both houses (except for a few details needed from rep pages)
=> UT: fixed leg scraper

openstates/la/committees.py
Amateur hour over here; can't believe I missed this other import on my other PR.
=> LA: Remove BackoffScraper dependency in committee scraper as well

openstates/tn/committees.py
I still had so much to learn about XPath back in January.
Fixes Jira bug 447:
https://sunlight.atlassian.net/browse/DATA-447
=> TN: Correct Joint Government Ops Committee member names

openstates/de/__init__.py, openstates/de/actions.py, openstates/de/bills.py, openstates/de/committees.py, openstates/de/legislators.py
=> DE everything but events working

openstates/in/bills.py
looks like it was confined to one page, can't access it in the browser either.
While I was in there, threw a .lower() on the governor check just in case.
=> IN: working around bad API response

openstates/ut/legislators.py
causing OCD conversion issues. also just bad json.
=> UT: fixed list nesting in links

openstates/ut/legislators.py
I think this will prevent repeated duplication post-momming.
=> UT: removed _scraped_name to avoid duplicating everyone again

openstates/me/bills.py
=> ME: Correct bill type classification

openstates/in/legislators.py
i am terrible at underscores.
also these weren't really needed. now they are gone.
=> bad name fields in IN

openstates/tn/events.py
=> removes extra spaces in TN dates

openstates/ok/bills.py
this fixes the error, but we're currently missing committee votes entirely. I'm going to file a bug about that because it looks nontrivial to start doing so and this scraper's beend own fr a while.
=> OK: skip malformated votes

openstates/oh/bills.py
I think that we've been hitting a timeout issue on big API calls, so I decreased the `per_page` from 300 to the default (50(?)).
=> OH: Quicken API calls

openstates/pr/committees.py
Also, skips joint committees, which are listed with only Senate members
=> PR: Adapt to new Senate committee PDF style

openstates/ok/legislators.py
moved the check for a bad district earlier so we don't try to do stuff with an empty dist!
=> OK: empty districts and whitespace issues

openstates/ma/legislators.py
seem to have updated his data on the site.
=> MA: removed special casing for Keenan

manual_data/districts/vt.csv
=> VT division_id added for everyone's favorite district

openstates/in/legislators.py
either we missed this before or something changed but the sources were bad.
=> IN: fixed legislator urls with extra sessions

openstates/de/bills.py
my new favorite vote passage status is "Neither passed nor defeated by Senate". Thanks Delaware.
=> de: throw warning instead of failing on missing vote docs

openstates/ma/bills.py
As reported on [Open States Google Group](https://groups.google.com/d/msg/fifty-state-project/hI1CwlNLsWA/1NDpBUcLxccJ). Thanks!
=> MA: Fix bill text scraping

openstates/id/legislators.py
Also deleted some outdated, nonstandard JSON fields that belong elsewhere in the schema.
=> ID: Restore contact information for all legislators

openstates/ga/bills.py
I think this solves it. untested.
=> GA: Order bills

openstates/in/legislators.py
getting a SSL error on production but not locally. Indiana works with http and https when visiting through the browser, so figured I'd try http to see if that fixes it.
=> IN: switched from https to http to (hopefully) fix SSL error

openstates/ia/votes.py
Even though it says `On the question of`!!
=> IA: Allow motion names without question marks

README.rst
Changed 'Open State' to 'Open States'
=> Changed 'Open State' to 'Open States'

openstates/vt/bills.py
Hopefully this'll put the issue to rest. Sorry for the plethora of PRs on this state.
=> VT: Switch to a more robust and consistent indicator of chamber passage

openstates/sd/__init__.py
@paultag, let's talk about this on Monday.
=> SD: Switch to 2016 session, per change in the website

openstates/mn/__init__.py
note that the session doesn't have any bills yet.
Also we should rerun 2015-2016 one more time, because they appear to have added a few more actions after they put this special session in the session list.
=> MN: added 2015 special session

openstates/fl/__init__.py, openstates/fl/bills.py
Also clean up titles from sponsor names.
=> FL: Added new session, which is currently in progress

openstates/tx/events.py
Dang tootin' datetime event text has annoyed us for the last time. I just took @rshorey's advice and removed our explicit handling, as it was doing far more harm than good; we were just removing all the text anyways. :fire: #offwithitshead :fire:
=> TX: Refactor to just remove all text after datetime

openstates/de/legislators.py
=> DE: dealing with minor changes in the legislators page

openstates/ri/legislators.py
Not sure if this is the cleanest way, but all the other information is being pull from a spreadsheet that didn't contain phone numbers, and individual bio pages weren't guaranteed to contain phone numbers.
=> RI: Updated xpath for phone number collection

openstates/de/bills.py
one bad link. surprisingly painful to fix. delaware.
=> DE: bad de link

openstates/ny/bills.py
http://open.nysenate.gov/legislation/bill/C620-2015
=> NY: Add the C type (C620-2015)

openstates/wv/__init__.py
2016 has no bills yet. Should we pull this in anyway? should we turn it off?
=> WV: added 2016 session

openstates/md/committees.py
Side note: I think this might have added all "House Delegation" committees to 'Joint'. If that's wrong, I'll fix it.
=> MD: Fixed indent so scraper saved joint committees as well

openstates/in/apiclient.py, requirements.txt
I have never reproduced this error locally, but this ought to work?
=> IN: fixed packet error crashing, maybe?

openstates/oh/bills.py
Closing https://sunlight.atlassian.net/browse/DATA-474 and https://sunlightfoundation.supportbee.com/tickets/5399875
=> OH: Correct order of actions

openstates/ri/legislators.py
Accounts for one of the issues in this SB email:
https://sunlightfoundation.supportbee.com/tickets/5338250
=> RI: Handle names that are missing space after Senator or Representative title

openstates/in/apiclient.py
can't replicate locally (also takes forever to run...) so just adding more tries and crossing my fingers.
=> IN: hopefully fixing IN bad packet problem w more retries?

openstates/or/__init__.py
we seem to be ignoring past years' interim sessions, so I put this one in ignored, too.
=> OR: added 2015-2016 interim to ignored

openstates/ky/committees.py
this maybe isn't the purest way to do this, but it works.
=> KY: getting budget subcommittees for both chambers

openstates/ar/legislators.py
He didn't have a party tag next to his name. Created an exception that would break if he added one later.
=> AR: inserted David Johnson exception

openstates/ca/__init__.py
this replaces @mileswwatkins' PR, which I will close.
=> CA: fix special sessions

openstates/vt/legislators.py
@linzjax, want to code review this to get some practice?
=> VT: Correct legislator emails, and add their state office

openstates/wa/legislators.py
=> WA: Major rewrite of the legislator scraper, finally able to reliably get contact info

openstates/mo/legislators.py
they added some crud to the vacant seat. if we ever get a legislator named Vacant, we're in trouble (probably everywhere, though).
=> MO: deal with vacant seat

openstates/ut/bills.py
I honestly have no idea how this ever worked. but OK.
=> UT: fixed session-finding xpath to be robust to specials

Dockerfile
Some scrapers need specific packages
=> Add Dockerfile installs

openstates/mi/events.py
=> MI: event date formatting

openstates/ct/legislators.py
=> CT: Scrape committee roles so that they show up as such on the frontend

openstates/ct/bills.py
[Example log with this problem.](http://moxie.sunlightlabs.com/run/10665/)
=> CT: Turn off problem-causing SSL for bills

openstates/ar/legislators.py, openstates/az/legislators.py, openstates/co/legislators.py, openstates/dc/legislators.py, openstates/hi/legislators.py, openstates/il/legislators.py, openstates/ks/legislators.py, openstates/ma/legislators.py, openstates/md/legislators.py, openstates/me/legislators.py, openstates/mn/legislators.py, openstates/mt/legislators.py, openstates/ne/legislators.py, openstates/nj/legislators.py, openstates/ny/legislators.py, openstates/pa/legislators.py, openstates/ri/legislators.py, openstates/tn/legislators.py, openstates/wy/legislators.py
@mileswwatkins I guess perhaps you ought to take at least a quick look at this one given the extent of the changes
=> Emails to offices

openstates/ct/bills.py
yay guess and check.
@mileswwatkins can you check this one to make sure it doesn't look like a terrible idea please?
=> CT: attempt to fix ssl problem that only occurs on prod

openstates/wv/legislators.py
I also removed an extraneous e-mail parsing statement that by all means looks to be useless.  I tested the scraper and it's still pulling e-mails properly.
=> Added handling missing office phone numbers for WV legislators.

openstates/ca/committees.py
Handling for special case (http://emergencymanagement.senate.ca.gov/) where members aren't listed as a list of links, but are published in an unformatted text blob.
=> Added special case handling for committee membership.

openstates/wa/legislators.py
Added scraping for WA emails based on DATA-512.
=> WA: Added scraper for legislator emails

openstates/az/__init__.py, openstates/az/bills.py
The AZ 52nd Legislature 1st Special Session has no bill activity yet.  Also implemented skipping over amendment bill documents that are missing their source URL.
=> AZ Bill Scraper Fixes

openstates/wa/legislators.py
Should now skip over legislator e-mails not being found.
=> Improved e-mail handling.

openstates/ny/legislators.py
Moved writing the e-mail field for senators from the office data to the actual legislator.
=> Updated e-mail field handling.

openstates/nm/legislators.py
Also expanded vacant seat handling.
=> NM: Refactored legislator scraper.

openstates/mn/legislators.py
Moved from scraping Excel spreadsheet to member list page.  This is
because the spreadsheet was not being kept up-to-date.
=> MN: Refactored scraping House legislators.

openstates/in/apiclient.py
doesn't fix the issue finding bill text, but will hopefully make it easier for people to figure out how to debug IN in the future.
=> added comment about how to use the api in the browser

openstates/ma/bills.py
session was blank in prod previously.
=> fixed ma bill issue 186th session

openstates/ne/bills.py
Also fixed scraping for transcript documents.
=> NE: Fixed bill scrapers for changed markup.

openstates/ri/legislators.py
=> ri legislators hotfix

openstates/va/__init__.py
Run this to remove the duplicate special sessions
```
js
db.bills.remove({ 'state': 'va', 'session': '2015specialI'})
```
Run this to get the right bills after committing the fix
```
bash
billy-update --session=2015specialI --bills --fast va
```
=> added the right session number for the 2015 special session

openstates/ia/bills.py, openstates/ia/votes.py
IA recently modified the structure of their website, includes several changed to handle this. 
Subject mapping not working -- seems like they got rid of the html page with all bills for each subject and replaced with a pdf. 
Also handles one minor unicode bug with votes.
=> handles slightly changed structure of website

openstates/me/legislators.py
- The full senate roster is fetched only once instead of repeatedly for each senate seat
- Seats absent from the senate roster are skipped, preventing the scraper from crashing. Currently, district 32 is vacant.
=> ME: Fetch senate roster only once, skip vacant senate seat.

openstates/ky/legislators.py
- When a capturing the phone number, the scraper would grab the fax number (if present) instead. See, e.g., http://openstates.org/api/v1/legislators/?state=ky&last_name=Buford
- Added capturing of fax number and email address
=> KY: Fixed capturing of phone, added capturing of fax and email

openstates/ar/committees.py
Chair is being skipped for every committee!
=> Don't skip first entry anymore.

openstates/ky/bills.py
Implemented separating actions on the same line for better
discrimination. Certain following actions on a line would be skipped
because an ignored action was initially detected.
=> KY: Fixed bill action parsing.

openstates/ne/legislators.py
This resembles the circumstance of the WA patch: The API appears to have mostly current data, but the scraper is no longer capturing it.
=> NE: Updated capture of email addresses

openstates/oh/legislators.py
=> OH: Generate legislators' email addresses

openstates/ne/bills.py
ex: http://nebraskalegislature.gov/bills/view_bill.php?DocumentID=28140
=> NE: added exception for committee sponsors (not included within a tags)

openstates/la/events.py
http://house.louisiana.gov/H_Sched/Hse_MeetingSchedule.aspx
=> LA: events scraper exclude 'Not Meeting'

openstates/in/bills.py
Vote validation error being caused by a resolution being adopted without recorded votes on a roll call: http://in.proxy.openstates.org/2016/rollcalls/MTE5LzIwMTYvY2FiaW5ldC9yZXNvbHV0aW9ucy9ob3VzZS9jb25jdXJyZW50L0hDMDA2Ni9yb2xsY2FsbC9IQzAwNjYuMC5wZGYuaHRtbA==.  Reached out to the Indiana General Assembly to confirm the procedure behind it.
=> IN: Refactored for resolutions without votes.

openstates/fl/legislators.py
Fresh commit fixing previous error
=> FL: Update detection of vacant seats

openstates/ga/legislators.py
=> GA: Skip legislators who have vacated

openstates/la/events.py
1. Handles TBA as a time (http://www.legis.la.gov/legis/Agenda.aspx?m=17196)
2. Handles missing comma between date and time (http://house.louisiana.gov/H_Sched/Hse_MeetingSchedule.aspx)
=> LA: handles problems with event scraper

openstates/nm/legislators.py
This is an update to retrieve NM legislator data from the [new NM legislature site](http://www.nmlegis.gov:8080/).
=> NM: scrape legislators from new NM legislature site

openstates/md/bills.py
http://mgaleg.maryland.gov/webmga/frmMain.aspx?pid=flrvotepage&tab=subject3&id=hb0172,s-1162&stab=02&ys=2016RS
=> MD: add handler for overridden motion

openstates/tx/legislators.py, openstates/tx/utils.py
Will gladly resubmit this PR if any changes are recommended.
=> TX: Full rewrite due to previous data sources going dead

openstates/fl/bills.py
FL was skipping all actions without an actor listed, so it was missing all governor/executive actions.
=> Updated FL bills scraper to catch actions without a chamber

openstates/nm/legislators.py
Handles slightly changed path to legislator links.
=> NM: legislator path change

openstates/va/bills.py
Based on @drobertsus changset: https://github.com/sunlightlabs/openstates/pull/1116
=> VA: Fixed recognition of votes with absentions.

openstates/wv/__init__.py, openstates/wv/bills.py
Added 2016 WV special session and bill scraper changes to accommodate future special sessions.
=> Added 2016 WV special session

openstates/va/bills.py
This changeset should largely prevent duplicate vote processing.
=> VA: Implemented more complex parsing for bill histories.

openstates/va/__init__.py
VA has started prefiling for 2017 and has bills up on the site.
=> Added VA 2017 session metadata

openstates/sd/__init__.py, openstates/sd/bills.py, openstates/sd/legislators.py
This is to fulfill the request made in [DATA-509](https://sunlight.atlassian.net/browse/DATA-509). It builds on some changes made in [Pull Request #1151](https://github.com/sunlightlabs/openstates/pull/1151).
I suggest merging that PR first. If you prefer, I can make a new PR after the other one has been merged.
=> SD: Add legislator emails (DATA-509)

openstates/tx/__init__.py, openstates/tx/legislators.py
Refactoring of TX legislator scraper to use a new source for legislator party data (http://www.lrl.state.tx.us/legeLeaders/members/membersearch.cfm).
=> TX Legislator Scraper Refactor

openstates/va/legislators.py
They had Patrick Henry as their placeholder legislator, for district 0 :|
=> Update VA for 2017 session

openstates/oh/bills.py
=> OH: Stub out new action types

openstates/wa/__init__.py, openstates/wa/actions.py, openstates/wa/bills.py, openstates/wa/legislators.py
=> WA: Overhaul section of bill processing

openstates/ut/__init__.py, openstates/ut/bills.py
=> UT: Add 2017 and special sessions, improve document capturing

README.rst
This includes information on how to
* build and run the Docker development environment
* run any tests (just `il` for now)
It also explains how the project relates to `billy`, and that the Dockerfile entry-point  is the `billy-update` command.
=> Added "Getting Started" instructions to the README

openstates/dc/bills.py
Cherry-pick by state, as part of https://github.com/openstates/openstates/issues/1170
=> DC: Add bill introducers, bills without sponsor

openstates/al/__init__.py, openstates/al/bills.py, openstates/al/legislators.py
Subsumes https://github.com/openstates/openstates/pull/1147, which I couldn't add a commit to myself.
=> AL: Add 2017 session, handle empty seats

openstates/ny/bills.py, openstates/ny/models.py
=> NY: Remove reliance on Mongo

openstates/sc/__init__.py, openstates/sc/bills.py
=> SC: Add prefiled bills to scraping

openstates/tn/__init__.py, openstates/tn/bills.py
=> TN: Allow special-session bill scraping

openstates/nj/bills.py
=> NJ: Skip errors adding bills

openstates/mo/__init__.py, openstates/mo/bills.py
=> MO: Adapt for 2017 session

openstates/vt/__init__.py, openstates/vt/bills.py
Scraper doesn't finish since there are no 2017-2018 bills, but should be good to go.
=> [WIP] Update Vermont to new session

openstates/ca/__init__.py, openstates/ca/download.py
Fixes the CA mysql download script for the new server location and listing format, and adds the 2017 session to the __init__ metadata.
=> CA: Update for 2017, and new download system

openstates/ms/__init__.py
Adding 2017 regular and 2016 2nd Extraordinary sessions in MS.
=> MS: Add 20162E and 2017 sessions

openstates/id/__init__.py, openstates/id/bills.py
@jamesturk @mileswwatkins  New bills scraper is working so far, but there's only one bill, so I'd probably say merge it but we'll keep an eye on it.
=> ID: Update metadata file for new website and add 2017 session

openstates/ks/__init__.py, openstates/ks/bills.py, openstates/ks/legislators.py
=> KS: 2017 bills scraper

openstates/nh/__init__.py, openstates/nh/bills.py, openstates/nh/legislators.py
NH: 2017 Scraper Update
WARNING: There's some low quality code in here (mostly a cut and paste from the legacy scraper, as they've returned to a similar system going forward), but I have to catch a plane so I figured it's better than nothing. Not all the bill URLs work, I'll email NH next week and figure out why some bill urls use the LSR and some don't.
If nobody else gets to it I'll refactor/clean it up in January.
The new NH files come from http://gencourt.state.nh.us/dynamicdatafiles/ instead of a ZIP file.
=> [WIP] NH: First pass at 2017 scraper

openstates/mo/bills.py
We were missing House bill texts, amendments, and supporting documents in the MO bill scraper.
=> MO: scrape house bill text, amendments, and summaries

openstates/az/__init__.py, openstates/az/action_utils.py, openstates/az/bills.py
New Arizona Bill Scraper.
They seem to have gone backwards in some ways with their new site, I can't a real list of actions, or votes. This at least scrapes the bills, including 2017 prefiles.
A good project for someone new/TODO will be to check into action_utils.py -- I'm trying to map from the dates provided in the JSON to proper actions, but have a number of blanks for items I haven't researched yet.
=> [WIP] First pass at new AZ scraper

openstates/il/bills.py
=> IL: Real error checking and skip messages for bad PDFs

openstates/de/__init__.py, openstates/de/bills.py, openstates/de/legislators.py
Cherry-picked for the state, as part of https://github.com/openstates/openstates/issues/1170
=> [WIP] DE: Add 2017 session, rewrite for new site

openstates/nm/__init__.py, openstates/nm/bills.py, openstates/nm/committees.py, openstates/nm/legislators.py
=> NM: Get 2017 working

openstates/wa/legislators.py
closes https://github.com/openstates/openstates/issues/1279
=> WA: Strip spaces from email addresses

openstates/md/bills.py
Alternate to https://github.com/openstates/openstates/pull/1278
=> MD: Handle cases where motion text is missing vote counts

openstates/nh/bills.py
=> NH: Match Version IDs to bills, fixing bad bill version links.

openstates/ny/events.py
Resolves #1288 -- At least until we have a bigger sample size.
=> NY: fix event scraper, better split event participants

openstates/fl/__init__.py
and added 2016 organizational session to ignore list
=> FL: Moved 2017 session to correct term

openstates/ut/bills.py
Fixes some of the xpath strings that do not work with the new UT vote page.  The old xpath string code was left in place since the old page is still used randomly and the new page is using some malformed HTML that will (hopefully)change.
=> Fixing bills parser exception on vote page #1310

openstates/co/committees.py
#1326  CO committee memberships out of date 
Rewrote committee scraper for the new Colorado website.
=> CO committee scraper rewrite for their new website #1326

openstates/vi/__init__.py, openstates/vi/bills.py, openstates/vi/committees.py, openstates/vi/legislators.py
Adding this so we can pick it up later.
=> [WIP] VI: Bill support for US Virgin Islands, placeholders for others

openstates/vi/bills.py
Since we merged this into the main repo, I at least got the bill scraper working.
=> VI: Add source so bills scraper works

openstates/de/legislators.py
#1348 Handling vacant district 10, also fixed the json lookups due to the format and fields changing.  Linted the file to flake8 as well.
=> Fixed json keys, DE changed them up 1348

openstates/wv/committees.py
Added subcommittee handling for joint committees.
This will almost certainly require some manual data cleaning after being run to resolve subcommittees already recorded as regular committees.
=> WV: Fixes #1199.

openstates/nh/bills.py, openstates/nh/committees.py, openstates/nh/legacy_committees.py
Starting on #1248.
Like @showerst said, it looks like we'll need to parse membership from committee pages. Will take a look at that this week.
=> Parse NH committees from dynamic data.

openstates/la/legislators.py
#1369 The new house member pages are almost identical as the old ones.  Minor URL changes and some div/span ID changes were needed.
Also made the file flake8 compliant and removed some unused variable assignments.
=> LA house member new page #1369

requirements.txt
So that I can use the `--ipdb` flag.
=> Add ipdb to docker image.

openstates/nh/bills.py
Capture Amendments in NH by checking the docket.
=> NH: Add amendments to bill scraper

openstates/tx/bills.py
I opted to parse companion bills from the site rather than the xml exports because it was easier to figure out the session--wdyt?
=> Scrape texas companion bills.

Dockerfile, docker-compose.yml
* Use current pip version
* Check in missing mysql envvar
* Use latest docker-compose version
Sorry I broke the build 😓
=> Fix pip version and mysql environment.

openstates/il/tests/test_bill_metadata.py, openstates/nm/tests/test_vote_parsing.py
So that the testing instructions in the readme work. Also, wdyt about standardizing on pytest as we switch to pupa and hopefully write more and better tests?
=> Fix or skip breaking tests.

openstates/nh/legislators.py
issue https://github.com/openstates/openstates/issues/1402
NH Legislators: add phone to legislator records
=> NH Legislators: add phone

openstates/id/legislators.py
=> Fix ID phone numbers.

openstates/nh/legislators.py
This makes the scraper take longer to run, since we're pulling every house member page to figure out their seat number. Anybody have a better idea? Also, I'm wondering if we can ask the folks who provide the NH data to restore the employee ID to the table so that we can avoid this step eventually.
=> Restore NH photos.

openstates/sd/legislators.py
=> Fix Issue 1425 - SD moved email addresses into Javascript.

openstates/ri/legislators.py
=> Fix name parsing for First M. Last format names in RI data.

docker-compose.yml
Depends on https://github.com/openstates/openstates.org/pull/45.
=> Run openstates.org with compose.

openstates/tx/tests/fixtures/roll_call_vote.html, openstates/tx/tests/test_vote_parsing.py, openstates/tx/votes.py
As described in #1363, the Texas vote scraper currently uses regular expressions that are too specific to match many real votes. This is a first pass at a parser that's more accurate and IMO easier to read. I would love to get a second opinion on the approach before I continue with this.
=> Initial Texas vote refactor.

openstates/ma/committees.py
=> MA: Update committee xpaths.

openstates/me/committees.py
=> ME: Rewrite senate committee scraper.

README.rst
=> Update 'writing scrapers guide' link

openstates/nm/bills.py
Handles the bottom row in:
From https://www.nmlegis.gov/Sessions/17%20Regular/votes/HB0442HVOTE.PDF.
Resolves #1461.
=> NM: Handle non-voting rows.

openstates/mt/committees.py
hey,
this is for issue #1451 
following are urls for montana house and senate committees which i added in scraper in this url please have a look at it
http://leg.mt.gov/content/Committees/Session/2017-house-committees.pdf
http://leg.mt.gov/content/Committees/Session/2017-senate-committees.pdf
=> #1451 mt updated for 2017

openstates/co/bills.py
CO Includes their bill amendments as PDF links buried in their hearing summaries. This is a first attempt at parsing them out.
=> CO: Parse bill amendments

openstates/mo/votes.py
this is for issue #1450 
please have a look at it
=> #1450 MO bug solved

openstates/id/committees.py
=> #1447 ID: file changed issue solved

Dockerfile, Dockerfile-pupa
Also removed an extraneous `mkdir`, since `ADD` will do that part itself.
=> Delete all PYC files in Docker, closes #1478

openstates/ar/bills.py
Fixes #1493
I'm not sure if this is the right way to fix this sort of issue or not. Seems like a problem on AR's side. They had the sponsor there just a little while ago. I'm very new to this project so let me know if this is a good fix or not. Tested locally.
=> AR do not add sponsor if they are not listed

Dockerfile-pupa, docker-compose.yml, pupa-scrape.sh
* Install ipdb
* Expose pupa cli args
Usage: `PUPA_ARGS="--debug" docker-compose run scrape va`
Note--this could also be simplified if we could pass the `--debug` flag to pupa subcommands.
=> Allow debugging with pupa.

openstates/id/bills.py
hey this is patch for issue #1510 and #1511
=> issue #1510 and #1511 solved

openstates/nm/committees.py
=> NM: include 'Ranking Member' for committees.

openstates/me/legislators.py
Fix ME xpaths such that we scrape representatives instead of not scraping them.
=> ME: Scrape representatives.

openstates/hi/bills.py
=> HI: "carried over" bills bug solved

openstates/de/__init__.py, openstates/de/committees.py, openstates/de/legislators.py
#1445
Bug fixed for `None` named legislators.
Re: #1499
=> DE: Committees Scraper Updated

scripts/build-thumbdrive.sh
I haven't gotten to run it on Linux or Windows (which might affect the paths or escaping), but the rest has been checked and confirmed working, as far as writing to the thumb drives.
=> Add tool to populate USB drives with Open States quickstart material

openstates/tn/committees.py
This updates the xpath to look for all links under a section whose header has certain text.
Event though the joint committee xpath was still working, this updates it to use this idea as well, for consistency.
The scrape now gets the correct number of committees for each chamber:
* upper - 12
* lower - 31
* joint - 4
**Total** 47
Closes #1544
=> TN: Fix upper and lower committee links xpath

openstates/nm/bills.py
Added a new action code to the current NM bills scraper so it doesn't choke. I also left a note on the Pupa WIP PR for that maintainer.
=> NM: Added new bill action code

openstates/ok/legislators.py
Fix for #1545
Few Office data, found to be empty on the url, so I have added checks if there is no data of office, no add the office.
=> Fix for #1545

openstates/il/bills.py
#1517  Solved 
For Example:-
-    Davis, William 
-   Burke, Kelly 
-  Harris, Gregory
- Mitchell, Christian
=> IL: Vote names saved as Last,First fixed to Last, First

openstates/tn/bills.py
This fixes the TN scraper to pull votes from the bill page "Votes" section. See examples in #1559.
This contains a small refactor that splits out the function for scraping each house's votes. This actually minimizes whitespace changes in the diff.  Instead of adding votes within the vote scrape method, it returns a list of votes, each of which are added to the bill.
=> TN: Fix vote scraping to pull from "Votes" section

openstates/va/people.py
=> VA: Restore photos.

openstates/va/people.py
=> VA: Restore contact details.

openstates/mt/bills.py
Fixed #1515
For Example:-
"Moore, Frederick (Eric)" to name = "Moore, Frederick" and note="short name: "Eric"
=> MT:Vote names saved with a trailing (<name>) fixed

openstates/ca/legislators.py
CA assemblymembers and senators have working emails but they're not shown on public pages anymore.
=> CA: Add code to compute email from name

openstates/mi/legislators.py
=> MI: legislator scraper URL fixed

openstates/md/bills.py
MD Added a few new [document types](http://mgaleg.maryland.gov/webmga/frmMain.aspx?pid=billpage&stab=02&id=HB152&tab=subject3&ys=2017rs). 
This adds support for them to fix the scraper, and also cleans up the names of amendments, which were being truncated.
=> MD: Fixed bill parser

openstates/co/bills.py
CO Published a vote with no associated vote page, which broke the parser. Do a hard check for vote URL now.
=> CO: Fix broken bill parser due to missing vote page

openstates/nd/votes.py
When multiple bill numbers are detected in the closing text (very rare), a vote object is added for each of them.  Fixes #1516.
=> fixes multiple line description bug, allows creation of multiple vote objects

openstates/fl/__init__.py, openstates/fl/common.py, openstates/utils/__init__.py, openstates/utils/lxmlize.py
So that I can stop copying and pasting this while converting states to pupa.
=> Move url_xpath to utils.

openstates/pa/people.py
Looks like this only gets us 37 email addresses, all senate, but it's better than none.
=> Add code to find emails on the PA contact-your-rep page

openstates/va/people.py
Code was putting phone into the email field.
=> VA: Fix missing emails

billy_metadata/de.py, openstates/de/__init__.py, openstates/de/bills.py, openstates/de/committees.py, openstates/de/events.py, openstates/de/people.py, openstates/utils/__init__.py, openstates/utils/lxmlize.py
Related to #1442
Re: #1507 
-  [x] people.py
-  [x] bills.py
-  [x] events.py
-  [x] committees.py
=> Converted DE to pupa

billy_metadata/ky.py, openstates/ky/__init__.py, openstates/ky/bills.py, openstates/ky/committees.py, openstates/ky/people.py, openstates/ky/votes.py
ky now works with pupa.
Important note: this retains feature parity, new issue probably needs to be created for vote scraper, as it currently is commented out.
=> Convert Kentucky to pupa

billy_metadata/az.py, flake8.sh, openstates/az/__init__.py, openstates/az/action_utils.py, openstates/az/bills.py, openstates/az/build_metadata.py, openstates/az/committees.py, openstates/az/events.py, openstates/az/people.py, openstates/az/session_metadata.py, openstates/az/utils.py
=> Converted AZ to pupa

openstates/ks/bills.py
=> KS: Missing Bill Votes fixed

Dockerfile-pupa, requirements-new.txt
=> Move IPDB from Dockerfile to Requirements file

openstates/mt/__init__.py, openstates/nc/__init__.py
=> Replace URL TODOs.

openstates/nc/committees.py
=> NC: Update logging.

openstates/mi/committees.py
=> MI: Fix senate committees.

openstates/tn/bills.py
Fixed #1682
Both of commented problems are now solved.
=> TN: Bills: actor field & action_taken corrected

billy_metadata/wy.py, flake8.sh, openstates/utils/__init__.py, openstates/utils/lxmlize.py, openstates/wy/__init__.py, openstates/wy/bills.py, openstates/wy/committees.py, openstates/wy/people.py, setup.cfg
=> Convert WY to pupa

billy_metadata/ky.py, openstates/ky/__init__.py, openstates/ky/committees.py, openstates/ky/people.py
=> KY: Delete unused code.

billy_metadata/ne.py, flake8.sh, openstates/ne/__init__.py, openstates/ne/bills.py, openstates/ne/committees.py, openstates/ne/people.py, openstates/ne/votes.py
=> Convert NE to pupa

openstates/nh/bills.py
=> NH: Roll call legislator names with extra space

openstates/co/bills.py
=> CO: Fix for blank vote summary page

pupa2billy/committees.py, pupa2billy/events.py, pupa2billy/votes.py
This should fix some of the issues raised in #1722.
=> Add extras to miscellaneous billy models.

openstates/ca/legislators.py
=> CA: Email address fixed

openstates/al/people.py
Explicitly emit committees, and add people to committees instead of the other way around (else members aren't correctly added by `pupa2billy`).
See #1713
=> AL: Fix missing committee memberships.

billy_metadata/va.py, openstates/va/__init__.py, openstates/va/people.py
=> VA: Emit committees after adding all memberships.

openstates/nj/legislators.py
It seems they've been removed from the Access DBs on the FTP site, but they still work and appear on many reps personal sites (although not in a form we could easily scrape).  The formula is simple enough - just AsmLAST@njleg.org and SenLAST@njleg.org.
=> Deal with missing NJ emails

billy_metadata/wv.py, flake8.sh, openstates/wv/__init__.py, openstates/wv/actions.py, openstates/wv/bills.py, openstates/wv/committees.py, openstates/wv/people.py
=> Pupa Conversion of WV

openstates/tn/people.py
Alternatively, we could ask TN to fill in the missing email address.
=> TN: Handle missing email addresses.

billy_metadata/dc.py, billy_metadata/in.py, billy_metadata/ma.py, billy_metadata/pa.py, billy_metadata/tn.py, openstates/dc/__init__.py, openstates/in/__init__.py, openstates/ma/__init__.py, openstates/md/__init__.py, openstates/mn/__init__.py, openstates/mn/common.py, openstates/pa/__init__.py, openstates/ri/__init__.py, openstates/tn/__init__.py, openstates/tn/common.py, openstates/tn/events.py, openstates/ut/__init__.py, openstates/va/__init__.py, openstates/va/common.py
* Add missing `get_session_list` methods
* Delete duplicate or unused utilities
* Fix TODO
=> Fix miscellaneous lint.

billy_metadata/nh.py, flake8.sh, openstates/nh/__init__.py, openstates/nh/bills.py, openstates/nh/committees.py, openstates/nh/legacyBills.py, openstates/nh/legacy_committees.py, openstates/nh/people.py, openstates/nh/utils.py, requirements-new.txt
=> Pupa conversion of NH

openstates/az/bills.py
#1769
Invalid Action Time `True` for `RequestforEnactment` on [Link](https://apps.azleg.gov/api/Bill/?billNumber=SB1368&sessionId=117&legislativeBody=S)
=> AZ: TypeError included for Invalid action time

billy_metadata/tx.py, flake8.sh, openstates/tx/__init__.py, openstates/tx/bills.py, openstates/tx/committees.py, openstates/tx/events.py, openstates/tx/people.py, openstates/tx/tests/fixtures/roll_call_vote.html, openstates/tx/tests/test_vote_parsing.py, openstates/tx/votes.py
Ready for review:
- Person
- Committees
- Bills
- Votes
- Events
=> [WIP] Convert TX to pupa

openstates/il/committees.py
=> IL: Committees Scraper Fixed

openstates/wv/bills.py
=> WV: decoding error solved

billy_metadata/tx.py, openstates/mi/__init__.py
=> MI: Fix session list method name.

openstates/ca/people.py
Hi there, I am new to open source. I observed an issue explained by dnoble #1784
I edited the last_name variable by adding an additional if condition to make sure that the last_name variable doesn't take in suffix as last name. Please  review it and add it to main code if it makes sense :)
=> people_email-lastname-issue.py #1784

openstates/nd/people.py
#1798
Looks like some of the legislator's pages don't have `political party` info. so fetching this info from [Link](http://www.legis.nd.gov/assembly/65-2017/members)
=> ND: people.py party KeyError

openstates/co/committees.py
=> CO: header index_error solved

openstates/ma/people.py
=> MA: handle missing address info contactGroup

openstates/dc/bills.py, openstates/sc/people.py
=> Dc: argument of type 'NoneType' error solved and SC: photo_url error solved

openstates/il/_committees.py
=> document  _committees in IL

openstates/tx/__init__.py
The end date is the statutory max but they could come in under that, if so I'll amend w/ the correct end date.
=> TX: Add 2017 first special session

openstates/ok/people.py
=> OK: fixed people Members url

openstates/fl/__init__.py, openstates/fl/bills.py
FL started prefiling this week.
=> FL: added 2018 session for prefiles

openstates/co/__init__.py, openstates/co/bills.py
=> CO: Add 2017 First Special Session

openstates/ne/votes.py
This is in reference to: #1853
=> Fixed abstentions counting in NE roll call count.

openstates/ma/bills.py
Small fix for MA bills, adjusting str.split. Fixes #1921
=> MA: fix for #1921

openstates/me/committees.py
=> Fixed bad link in ME committees.py

openstates/id/committees.py
=> Fixed XPath query and tweaked code for committee members.

openstates/wv/__init__.py, openstates/wv/bills.py
State: WV
New special session.
=> WV: Add 2017 Second Special

openstates/nv/__init__.py, openstates/nv/events.py
Scraping the meetings calendar at https://www.leg.state.nv.us/MeetingDisplay/CalendarOfMeetings/
=> NV: Add event scraper

openstates/nh/people.py
=> NH: Fix district for Casey Conley

openstates/mo/__init__.py, openstates/mo/bills.py, openstates/mo/committees.py
These are causing Travis fails on unrelated PRs (#1994, #1995, #1997, #1998, #2003, #2004, #2005).
=> MO: fix flake8 issues

openstates/ny/people.py
=> NY: Hack Al Taylor's party (missing from scraped data)

openstates/ms/people.py
=> MS: hack in party for Shane Barnett

openstates/ms/people.py
No party is provided in the scraped data.
=> Set party for Cheikh Taylor, Kevin Ford

openstates/mi/bills.py
State: MI 
Classifiers for vetos
=> MI: Add veto action classifiers

openstates/tn/bills.py
state: TN
Add additional classifier for alternate "Passed Senate" action text.
=> TN: Passed Senate classifier

openstates/nm/__init__.py
NM: add metadata for 2018 session, currently prefiling.
=> NM: add 2018 session

README.rst
No doubt someone more experienced can doc this better; please review carefully.
=> readme: command options, acquiring/using state API keys.

billy_metadata/ky.py, openstates/ky/__init__.py
=> KY: add 2018 session

billy_metadata/ri.py, openstates/ri/__init__.py
=> RI: add 2018 session

billy_metadata/ms.py, openstates/ms/__init__.py
Fixes #2050.  
Ready to merge.
=> MS: add 2018 session.

openstates/de/bills.py
=> DE: Fix fiscal note scraping.

openstates/ms/people.py
... for Cheikh Taylor, Missy McGee, Kevin Ford.
Fixes #2050.
=> MS: remove manually-applied party affiliations.

billy_metadata/wv.py, openstates/wv/__init__.py
Fixes failure from last night's run (no issue yet).
Update: fixes #2001
=> WV: Add 2018 session (READY to merge)

openstates/ut/committees.py
@jamesturk, which is preferable:
- cleaning up the committee names so that they're within Open States norms (ie, removing trailing " Committee" or " Subcommittee" text)
- maintaining consistency with committee names already in the DB (which, for UT, did not remove trailing " Committee" or " Subcommittee" text)
In this PR I assume the former.
=> UT: Switch to much cleaner JSON for committee scraping

openstates/id/people.py
Fixes #2082.
Ignores substitutes, as discussed.
=> ID: ignore substitute legislators

openstates/mi/committees.py
The pseudo ID has been failing, and I tried mirroring different practices I see in production scrapers, but most of them failed until I tried this one, borrowed from one of your recent PRs @jamesturk. Let me know if this is proper practice!
=> MI: Fix subcommittee parent ID for senate appropriations

billy_metadata/sd.py, openstates/sd/__init__.py, openstates/sd/bills.py, openstates/sd/people.py
Site is largely the same, but some significant tweaks that were breaking the scrapers in major ways.
After this PR is merged, the state must be re-activated in Bobsled's Task Definitions.
=> SD: Get running for 2018

openstates/mt/committees.py, openstates/nj/bills.py
Had lots of trouble cloning the prod DB to my local machine, in a way that works with a local scrape. But this should help to resolve the ambiguities that Pupa was hitting on-`--import`, and runs successfully locally.
=> NJ: Help Pupa clarify which bill a VoteEvent is pointing at

openstates/nm/votes.py
Right now, [one](https://www.nmlegis.gov/Sessions/18%20Regular/votes/HB0001HVOTE.PDF) of the six vote PDFs for the state is failing. I've created [an issue](https://github.com/openstates/openstates/issues/2102) to address this down the line. Look like a good enough solution for now?
=> NM: Handle failure of PDF vote scraping for individual House members

billy_metadata/la.py, openstates/la/__init__.py, openstates/la/bills.py
Session has no bills yet; I'll monitor.
Fixes #2051.
=> LA: add 2018 session (READY to merge)

openstates/va/__init__.py, openstates/va/bills.py
Let me know if this is the right way to handle logging in the `va` module, or if I'm off the path. Thanks for the pointers!
=> VA: Handle empty actions, add logging

openstates/me/people.py, openstates/mt/committees.py
=> ME: Added support for deceased members #2154

openstates/ms/bills.py, openstates/ms/people.py
Issue MS: poorly-formatted district addresses #1872 fixed and bad formatting of auther's link(was giving 404 error) corrected.
=>  Fixed MS: poorly-formatted district addresses #1872 

openstates/ia/people.py
They changed the label on the table cell.
=> Fix IA scraper to find emails.

openstates/ny/committees.py
NY: Committees missing, for lower chamber #2067 fixed. for upper chamber it's already working fine.
=> Fixed NY: Committees missing, for lower chamber #2067 

openstates/wa/actions.py
WA added two new \<head of chamber\> signed this session.
=> WA Action classifier additions

openstates/ma/bills.py
Hopefully fixes #2183. I'm new to this project, so I don't know how to quickly test my patch. I tried testing it with `docker-compose run --rm scrape ma --fastmode` but it was taking a lot of time (and disk)! Is there a way for more rapid scraper test iterations?
=> MA: Fix action name split

openstates/mi/people.py
This solves #2187.
This PR, skips the email data for broken links, and lets the scraper continue.
I have created #2189, for the broken link, if we want to get the info in any case.
=> Email extraction omitted for broken contact links

openstates/md/bills.py
solves issues close #2093 and #2188, I am running few more tests and then I will fix lint errors.
=> New Vote Scraper for MD

openstates/md/bills.py
=> MD: New Motion keyword added votes

openstates/wi/bills.py
resolves #1909
Will check for assembly votes too.
=> WI senate vote adding function re-written

openstates/nh/__init__.py
@jamesturk, no rush on this. Just curious as to whether there're any special steps we need to take when making changes/corrections to post/role metadata like this.
=> NH: Fix lower-house role title

openstates/la/bills.py
=> LA: fix amendment xpath being too broad

openstates/va/people.py
=> VA 2018 special session: No end_date returns empty string rather than None

openstates/md/bills.py
resolves #2215
I have added a dictionary of the relative number of lines, for extracting motion from pdf.
=> MD: votes motion, extracted from more lines

openstates/me/bills.py
Fixes #2235.
See https://github.com/openstates/openstates/issues/2235#issuecomment-381244014 for details.
=> ME: hand-filter duplicate bill page

openstates/va/bills.py
Additional action classifiers in Virginia
=> VA: Classify vetos and veto override failures

openstates/id/bills.py
ID: Add a few wordings for passed committee, and identify chamber in which it passed committee based on legislative process.
=> ID: classify committee passage and identify chamber correctly

openstates/ok/__init__.py
=> OK: Add empty 2019 session to ignore list

openstates/ia/votes.py
=> IA: Fix motion regexes when trailing quote is missing (but question-mark is present)

openstates/id/bills.py, openstates/il/bills.py, openstates/ky/bills.py, openstates/me/actions.py, openstates/nc/bills.py, openstates/ri/bills.py, openstates/va/bills.py, openstates/wa/actions.py
Beginning of an attempt to classify when bills become law, beyond just executive-signature which doesn't occur in every state.
=> Add 'became-law' actions to multiple states

openstates/az/bills.py
fixes #2268
It should fix the error, although I have not able to check it. But the fix was very intuitive.
=> AZ: Bills syntax error fixed

openstates/oh/people.py
=> OH - fix people scraper: don't double-scrape Senate President, Minority Leader

openstates/mn/__init__.py
Bobsled's failing from no governor, no issue yet.
=> MN - add governor

openstates/ny/people.py
Failing in bobcat, no issue yet.
=> NY - force party for Chris Tague

billy_metadata/mo.py
Failing in bobcat, no issue yet.
=> MO - fix billy special session ID

billy_metadata/mo.py
=> MO: fix billy metadata for 2018 special session

billy_metadata/la.py
=> LA: fix billy import data

openstates/co/bills.py
resolves #2318 
Motion not available for the http://leg.colorado.gov/content/sb18-033vote563ce6.
=> Co vote scraper revamped.

openstates/az/bills.py
This is close, but could use attention from somebody who's more familiar with details of votes than me to verify output. For example, I'm not sure what we should do with "votes" like this one: https://apps.azleg.gov/api/BillStatusFloorAction?billStatusActionId=177494&billStatusId=68871&includeVotes=true. Should we include votes that don't concern passing a bill or amendment like this one?
@jamesturk @mileswwatkins
=> [WIP] AZ: Scrape votes.

openstates/mi/people.py
=> MI: Make people links absolute.

openstates/nc/bills.py
The NC bill scraper fails on master; it looks like the bills page
replaced a bunch of tables with nested divs. This patch updates to the
latest markup.
=> NC: Update bill selectors.

openstates/vt/bills.py, openstates/vt/committees.py, openstates/vt/events.py, openstates/vt/people.py, openstates/vt/utils.py
=> VT: Fix URLs for special sessions.

openstates/nc/bills.py
=> NC: Handle null text in action column.

openstates/ny/bills.py, openstates/ny/models.py, openstates/ny/utils.py
resolves #1960,
Since #2185 worked on this issue earlier, I worked on top of it.
I was facing error with validation of texts.
I have commented the validation part in ny/utils.py, I have added separate commit for that I am not sure how to handle that part, please review this part and suggest what should be done.
=> NY assembly votes

openstates/la/bills.py
=> LA: stop scraper from blowing up on blank server responses

openstates/wy/__init__.py, openstates/wy/bills.py
* Add executive organization
* Comment out unsupported bill version extras
Verified that scraping and importing WY bills works locally with this patch.
=> WY: Fix bill imports.

openstates/nc/bills.py
NC had some PDFs getting tagged as text/html.
=> NC: Fix mimetype on bill versions

openstates/az/bills.py
resolves  #2350 , I have still not been able to test it @showerst a quick test is really appreciated.
=> pupa_id added to az floor votes

openstates/mt/__init__.py, openstates/mt/people.py
Looks like some Montana URLs changed from .asp to .html.
=> MT: Update URLs.

billy_metadata/la.py, openstates/la/__init__.py, openstates/la/bills.py
=> LA: Add 2018 Third Special

openstates/mn/__init__.py
=> MN: Ignore empty 2019 session for now

dbinit.sh
Example at
https://www.leg.state.nv.us/App/Legislator/A/Senate/Current/8.
Also, there's probably a better place to put parties than a shell script in this repo. Should this live in `python-opencivicdata` or another repo? I'm also pretty sure I'm missing more parties, since I haven't been adding them systematically. Do you have a more authoritative list @jamesturk ?
=> Add "nonpartisan" party.

openstates/tx/people.py
Headmaster: There's a vacancy in history.
Tom Irwin: [Thoughtfully] That's very true.
Headmaster: In the school.
Tom Irwin: Ah.
=> TX: Skip vacant districts.

openstates/ne/committees.py
=> NE: Fix committee xpath selectors.

openstates/ma/bills.py
=> MA: widen vote detection regex and add code to scrape individual bill

openstates/tx/people.py
=> TX: change house urls to https and cert verification

openstates/ma/bills.py
=> MA: handle new action naming scheme

billy_metadata/ut.py
=> UT: Add special session to billy metadata.

openstates/fl/__init__.py
=> FL: ignore 2019 session and flake8 formatting

openstates/nh/bills.py
=> NH: fix special session bills

openstates/sc/bills.py
This needs a full run-through test before merge, but i'm about to hop on a plane.
=> SC: remove http protocol downgrades

openstates/sd/people.py
=> SD: new legislator page urls (takes a session now) and flake8 fixes

openstates/sd/bills.py
=> SD: updates for new URL structure

openstates/pr/committees.py
The PR committee scraper linked to an outdated Senate page. We update the page, switching to a web-based version instead of having to download a PDF for each committee.
=> PR: Update committee scraper for Senate

openstates/dc/bills.py
Related to #2464 
Changing self.post to requests.post works here -- but I don't understand why. @jamesturk @jmcarp  @mileswwatkins anyone more familiar with the pupa internals know why this might've made a difference?
=> Change self.post to requests.post and flake8 format.

openstates/tn/committees.py
Should resolve http://bobsled.openstates.org/run-TN-2018-08-14.html.
=> TN: Handle vacant committee roles.

openstates/dc/bills.py
=> DC: Convert self.post to requests.post to avoid server error

openstates/ia/votes.py
Looks like the old links, like https://www.legis.iowa.gov/chambers/journals/index/senate?year=2017, don't resolve anymore.
=> IA: Update journal pdf links.

billy_metadata/nc.py, openstates/nc/__init__.py
I named it 2017E2 to be consistent with the last special, although that may have been a typo at the time. It's the second special in the 2017-2018 term though, so I guess that's ok.
=> NC: 2018 Second Special

openstates/pr/bills.py
=> PR: Fix bad date.

openstates/wy/people.py
See http://bobsled.openstates.org/run-WY-2018-09-09.html
=> WY: Handle null date of birth.

billy_metadata/mo.py
Recommend testing scrapers with postgres locally 😄
=> MO: Add billy metadata for 2018S2.

openstates/pa/bills.py
Looks like these aren't always present now: http://www.legis.state.pa.us/CFDOCS/Legis/RC/Public/rc_view_action2.cfm?sess_yr=2017&sess_ind=0&rc_body=S&rc_nbr=126
=> PA: Handle missing LVE and N/V counts.

billy_metadata/nc.py, openstates/nc/__init__.py
=> NC: Ignore third special for now, add to metadata

openstates/ct/__init__.py, openstates/ct/bills.py, openstates/ct/people.py
See http://bobsled.openstates.org/run-CT-2018-10-07.html.
=> CT: Only fetch html vote pages.

openstates/ct/bills.py
=> CT: Get motion text from PDF links.

openstates/dc/people.py
Resolves #2536 
TODO: Find a better official photo source, the ones on the DC website are 125px thumbs.
=> DC: Update person scraper for new website

openstates/me/__init__.py
=> ME: move session ignoring logic to ignore_scraped_sessions

openstates/dc/__init__.py, openstates/dc/bills.py, openstates/dc/utils.py
Looks like the DC API started returning 404s for requests with the
default requests user agent.
=> DC: Fix and refactor DC API requests.

openstates/sc/__init__.py, openstates/sc/bills.py
=> SC: Skip SSL verification

openstates/ne/__init__.py, openstates/ne/bills.py
Seems easier than getting votes from pdfs, which apparently isn't working right now.
=> NE: Scrape votes from html instead of pdf.

Dockerfile, docker-compose.yml
Still waiting for this to finish locally...
=> Update docker image and mysql version for CA.

openstates/in/__init__.py
Add commented out 2019 session, ignore 2019 session, add dates for finished 2018 special.
=> IN: ignore 2019 session

openstates/mt/__init__.py, openstates/mt/bills.py
I verified that this runs and produces reasonable-looking bills and votes, but it wouldn't hurt to have somebody more familiar with MT spot-check a few records. I'm also not sure what the `_versions_dict` and `add_other_versions` methods do, so I commented out calls to them for now.
=> MT: Handle markup changes.

openstates/mi/__init__.py, openstates/tn/__init__.py, openstates/ut/__init__.py, openstates/vt/__init__.py, openstates/vt/events.py
Re-enable events in MI,TN,UT,VT
=> RE-enable events scrapers part 1

openstates/al/__init__.py, openstates/al/events.py, openstates/nj/__init__.py, openstates/nv/__init__.py, openstates/ny/__init__.py, openstates/pa/__init__.py, openstates/sc/__init__.py
AL, NV, NJ, NY, PA, SC event scrapers
=> Restore more event scrapers

openstates/mo/bills.py
=> MO: Skip junk bill listing

openstates/nv/bills.py
NV changed their website slightly
=> NV: Update selector

openstates/pa/__init__.py
=> PA: Add 2019-2020 session.

openstates/me/__init__.py, openstates/me/people.py
Continues work on the Maine people scraper, working for reps and senators.
Notes:
- some discrepancies with Senators' full names omitting middle names/initials (using the XLS file might help with this)
- some minor discrepancies in addresses (comma where semicolon/newline was previously)
- one legislator (Sara Gideon) has an invalid URL, which is skipped after retry https://legislature.maine.gov/house/house/MemberProfiles/Details/3
=> ME 2019 people scraper fixes

openstates/nd/votes.py
State: ND
Resolves http://bobsled.openstates.org/run-ND-2019-01-03.html
=> ND: Add 2019 session slug to votes scraper

openstates/ca/download.sh
It was changed to mysql, but wasn't updated in one place.
=> Fix user for CA MySQL database

openstates/ca/download.py, openstates/ca/download.sh, openstates/ca/events.py
It seems as if the username is still root, attempt to switch back to fix connection issues.
=> CA: Switch back to root for MySQL user

openstates/ca/bills.py
Missed this one, but the scraper seems to be working now up until this point.
=> CA: Update MySQL username for bills scraper

openstates/mn/people.py
The website changed, so update Minnesota's people scraper. Fixes #2760.
=> MN: Update people scraper

.dockerignore, Dockerfile
* Exclude .git from docker image
* Add and delete build dependencies in the same layer
=> Shrink docker image.

openstates/nc/__init__.py, openstates/nc/bills.py
=> NC: Update bill scraper for new site

openstates/mo/people.py
Everything else on MO's site seems to be the same?
=> MO: Update table ID of house roster

openstates/ct/bills.py
Resolves #2808 -- thanks for flagging @mzagaja
=> CT: Scrape versions from bill page

openstates/tx/__init__.py
Resolves #2494 
Resolves #2812
=> TX: re-enable vote scrapers

openstates/ny/people.py
- Prevent crash on failed capture of addresses
- Record correct type for capitol/district offices
=> NY: people scraper fixes

openstates/ak/__init__.py, openstates/ak/people.py, openstates/ct/bills.py, openstates/tx/__init__.py
Bills & committees scrapers still need updating.
=> AK: point to new website for sessions, prevent crash of people scraper

openstates/ct/__init__.py
Fixes http://bobsled.openstates.org/run-CT-2019-02-03.html.
=> CT: Update skipped sessions.

openstates/ar/bills.py
Fixes http://bobsled.openstates.org/run-AR-2019-02-03.html.
=> AR: Fix csv parse errors.

openstates/ky/__init__.py, openstates/ky/bills.py
=> KY: Updates for new web site

openstates/mt/bills.py
Fixes bills with incorrect categories in pdf links.
Fixes http://bobsled.openstates.org/run-MT-2019-02-04.html
=> MT: Get bill id from url.

openstates/fl/bills.py
=> FL: Fix typo in xpath.

openstates/vt/bills.py
Fixes http://bobsled.openstates.org/run-VT-2019-02-04.html.
=> VT: Pass bill object to vote.

openstates/fl/bills.py
=> FL: Fix more xpaths.

openstates/mt/bills.py
We were skipping some bill types in MT.
=> MT: Scrape HJ,HR,SJ,SR

openstates/md/bills.py
Fixes http://bobsled.openstates.org/run-MD-2019-02-10.html
=> MD: Update vote pdf scraper.

openstates/in/__init__.py, openstates/in/apiclient.py
=> IN: Fix default USER_AGENT for api

openstates/dc/bills.py
Collect all the actions the DC site shows, and remove some of our old custom ones that overlapped but provided less info.
=> DC: Update to show all bill actions, additional classifications

openstates/ky/people.py
Kentucky has a new website. This change adapts the "people" scraper accordingly.
PR for resulting legislator changes forthcoming.
=> KY: rewrite scraper for new website

openstates/ia/bills.py
=> IA: Add special case for bills with odd titles.

openstates/sc/bills.py
=> SC: Handle IncompleteRead errors.

openstates/wy/bills.py
See http://bobsled.openstates.org/run-WY-2019-02-22.html
=> WY: Handle fractional dates

openstates/ks/bills.py
=> KS: Skip broken vote pages gracefully.

openstates/ca/bills.py
This addresses the ongoing corruptions reported in https://github.com/openstates/openstates/issues/2880, but someone will need to fix the database. 
(It is also a poster child for why functions that run on for pages and pages are a bad thing!)
=> CA: fix duplicate bills

openstates/nc/bills.py
NC changed their html a little causing a bunch of bad sponsor names.
=> NC: fix broken sponsors

openstates/ca/bills.py
=> CA: Scrape SJRs

openstates/nm/votes.py
=> NM: Map XHB to HB.

openstates/ca/bills.py
=> CA: Stop filtering sponsors from other chamber, flake8 fixes

openstates/ma/__init__.py, openstates/ma/bills.py
=> Stop verifying bad SSL cert in MA.

openstates/ia/votes.py
=> IA(votes): update motion_re to handle special quote mark

openstates/al/__init__.py
=> AL: Restore session name now that they fixed typo.

openstates/fl/bills.py
=> FL: Skip over bad bill page

openstates/hi/bills.py
If a line in a bill's action log includes "reconsider" after a vote, this patch prepends "Reconsider: " to the next vote's name.
=> HI: Issue 2957: fix duplicate vote pseudo-ids when vote reconsidered.

openstates/ut/__init__.py, openstates/ut/bills.py
=> UT: Update for site markup changes

openstates/mo/__init__.py, openstates/mo/bills.py
State: MO
Change source of sessions to working page, and set a user agent on all senate site requests.
=> Mo 2019 special1

openstates/nh/people.py, scripts/dbinit.sh
Also, remove temp fixes for 2 invalid NH postings that are now fixed or gone..
Add Libertarian party (nationally).
Fixes #3027
=> NH: Fix people scraper (convert from text to CSV).

openstates/ne/bills.py
Fixed issue #3059 by changing 'http' to 'https' within the base url in the bill scraper.
=> Changed http to https in NE bill scraper

openstates/wa/bills.py
We had a few edge cases where WA bills were coming in with the wrong chamber, this should fix that by reading the chamber directly from the bill's XML from the state.
=> WA: clean up chamber logic a little

openstates/nm/__init__.py
No data yet, but doing the legwork in advance for when they start prefiling.
=> NM: Add 2020 Session

openstates/ak/bills.py
Updated Alaska (AK) Bill Scraper. Vote details still don't currently work, but basic vote information is still added.
=> Update ak bills scraper

openstates/ga/bills.py
=> GA: Separate legislator names and districts in votes.

openstates/ri/__init__.py
Added 2020 session to RI. Fixes issue #3084
=> Ri 2020 issue

openstates/nj/__init__.py
NJ started posting data -- #3046
=> NJ: Add 2020 session

Dockerfile, docker-compose.yml, poetry.lock, pyproject.toml
=> Changes required to make CA scraper runnable

openstates/fl/people.py, openstates/ma/people.py, openstates/nj/people.py, openstates/oh/people.py, openstates/ok/people.py, openstates/wy/people.py
Mostly to get them running or running properly.
=> Small tweaks to people scrapers

openstates/nm/bills.py
=> NM: Add new action code

openstates/ky/bills.py
KY: My bad, not sure how that previous commit slipped through.
=> KY: Fix missing trailing comma. Resolves #3133

openstates/or/__init__.py, openstates/or/bills.py, openstates/or/utils.py
NOTE: Don't merge this until there are some bills to check.
=> WIP: OR: Add 2020 Session

openstates/tn/bills.py
=> TN: Check for actions table before processing.

openstates/co/bills.py
Added in a check to see if any voters are found before adding votes. Fixes issues #3146
=> Co scrape 2020

openstates/ma/bills.py
I left the default to @azban 's previous setting of bill number, which makes sense for the general case.
@jamesturk you might want to implement sort=latest on your scrapes, because the scrape takes so many hours.
The quoting changes around 180 are a noop, just the result of running Black on it.
=> MA: Allow optional reverse cron scraper with sort=latest, document flags

openstates/nv/bills.py
and if we happen to catch a page before the versions are added, don't blow up.
=> NV: Fix for dupe versions

openstates/fl/bills.py
Added a line of code to see if votes are listed on committee vote pages.
Flake8 changed a number of spacing issues.
Fixes issue #3166
=> FL: Check to see if any votes are found on committee vote pages

openstates/ky/bills.py
KY: Added try statement before trying to grab vote pdfs
Should take care of issue #3172
=> KY: Added try statement before trying to grab vote pdfs

openstates/co/bills.py
Added a check to see if a bill history action had a date or not.
Related to issue #3167
=> Co bill history action date issue

openstates/mn/vote_events.py
Updated MN Vote scraper. Old code didn't include the current session and had xpaths that were off. I removed several try exceptions as it was catching just about everything, so we had no notice that the code wasn't running.
Fixes issue #1959 
@jamesturk
=> MN Votes Updated

openstates/pr/__init__.py, openstates/pr/bills.py
This scrapes the new PR site and allows for some date windowing. It includes votes but not individual name/vote pairs.
Still needs some code cleanup/formatting.
=> PR: New website

openstates/fl/bills.py
State: FL
Grab bill summaries.
=> FL: Scrape summaries when available

openstates/fl/bills.py
State: FL
Alternate wording for passage, see http://flsenate.gov/Session/Bill/2020/7013/ByCategory
=> FL: Add another passage action classifier

openstates/pa/bills.py
Don't merge this yet, waiting on a successful run to make sure it works.
=> PA: fix bad title skip and add log message

openstates/va/bills.py
Vote scraping in VA has been broken, as the method erased any `cached_vote`s after a continue line was commented out. So that actions will continue to be scraped for votes, this change moves the erasing of `cached_vote` and `cached_action` to when a VoteEvent is saved (and no additional data has been scraped for future processing).
This change also fixes scraping of votes which have links come second in sequence. Previously, individual votes were only scraped if the link came first in the history sequence. We will now scrape individual votes no matter when the link comes, and the placeholder link will be erased upon finding the second link.
=> VA: Fix vote scraping

openstates/ak/events.py
AK published an event with a bad committee code, so don't try to add an org on those.
=> AK: Fallback for events with bad committee code

openstates/ga/__init__.py, openstates/ga/bills.py, openstates/ga/util.py
No data posted yet and I haven't verified the site id so don't merge.
=> GA: Add 2020 special session

openstates/ca/bills.py
Added a special case for SB77 in 2005
=> CA Special Case for SB77 in 2005

openstates/oh/bills.py
Added in a vote motion dictionary to try and clear up what the vote motions actually were.
Relates to Issue #2998.
=> OH: Added in a vote motion dictionary

openstates/me/bills.py
Added code to grab all additional Bill Versions and Documents for ME.
Should fix issue #3022 
Some of the code can be rewritten and made less verbose.
=> ME: additional bill versions

openstates/nv/bills.py
Updated bill listing url. The rest of the scraper still works.
Fixes issue #3236
=> NV: Updated Bill Listing URL

openstates/ak/bills.py
AK: Added check to see if sponsor text existed
Should fix AK bill scraper on Bobsled.
=> AK: Added check to see if sponsor text existed

openstates/in/__init__.py, openstates/wi/__init__.py
IN: Removed an extra 0 in a date in the meta data.
"end_date": "2012-03-014", is now "end_date": "2012-03-14",
=> Metadata Fix Issues

openstates/wi/bills.py
Added documents that were originally skipped.
Related to issue #2200
=> WI: Added documents that were originally skipped.

openstates/ok/__init__.py, openstates/ok/bills.py
Resolves #3279
NOTE: Special doesn't start until Monday
=> WIP: OK: Add 2020 first special

openstates/sd/bills.py
the scraper was only grabbing the html link. modified to grab the pdf link and also added the dates to versions.
=> sd: get version link for pdf

openstates/ar/people.py
Paths are updated to scrap for people data on new website.
=> AR: Updated paths for people scrapping

scrapers/ut/__init__.py
=> ut: fix typo for end date of new special session 2020S4

scrapers/ok/__init__.py
OK started legislating again in the regular session
=> OK: Reset regular to default session

scrapers/oh/bills.py
Added concur_602 to vote motion dictionary.
=> OH Vote Motion

scrapers/wy/bills.py
Added a try-except statement to catch a 404 error.
Should fix issue #3326
=> WY 404 issue

scrapers/wy/__init__.py, scrapers/wy/bills.py
And allow scraping of specials.
#3331 should be knocked out when the next scrape runs.
=> WY: Add 2020 special session

scrapers/md/bills.py
State:MD
Classify bills that became law without gov signature, and capture effective Date(s)
=> MD: Classify bills that became law without gov signature,

scrapers/tx/bills.py
i attempted to get rid of the need to crawl for file names, and use the history XML instead. this works for everything, except for witness lists.
functionally isn't much different, other than grabbing version descriptions for some links that previously were just using the bill type in the note. but seems a little cleaner to me.
=> tx: use history xml for links when available

scrapers/dc/bills.py
@schneidy @jamesturk -- Suppressed those warnings, and also grabbing the lawNumber when available.
=> DC: Suppress unverified ssl cert warnings, and add law citation

scrapers/mi/bills.py
MI: Skip actions with no date
(had a question here but deleted it, sorry if you got an email james)
=> MI: Skip actions with no date

scrapers/mn/bills.py
State: MN
We're currently discarding actions with no action date in the pretty table, but that have the date in the text. Some of these are relevant (governor signings, etc). This patch attempts to parse them and adds when possible.
=> MN: Disable SSL warnings, and add actions when date can be matched

scrapers/pr/bills.py
PR made some asp changes that broke the scraper.
=> PR: Fix pagination

scrapers/pr/bills.py
State: PR
Fixes to pagination, and allow scraping individual chambers and individual bills
=> PR: more fixes

scrapers/nh/bills.py
=> NH: Skip duplicate amendments

scrapers/pr/bills.py
Don't blow up on unknown version types.
=> PR: Move exception to warning

scrapers/ct/__init__.py
Resolves https://bobsled.openstates.org/run/38e08c3a0fe7498c88936e586a51022d
=> CT: Add historical start/end dates

scrapers/nv/__init__.py
Thanks @jessemortenson for the 2021 code.
=> NV: Ignore 2021 session and add stubs

scrapers/nv/__init__.py
..and correct end date for first special.
=> NV: Add 2020 Second Special

scrapers/id/__init__.py, scrapers/id/bills.py
Don't merge until data has posted and we can test.
=> ID: Add 2020 first special

scrapers/ms/bills.py
Resolves https://github.com/openstates/issues/issues/123
=> MS: skip missing vote files

scrapers/mo/bills.py
Resolves https://github.com/openstates/issues/issues/120
=> MO: Fix special session senate URL slug

scrapers/tx/votes.py
Relates to https://github.com/openstates/issues/issues/100 (which involves both this and a state issue).
=> TX: Fix bad vote classification

scrapers/al/__init__.py
https://github.com/openstates/issues/issues/142
=> AL: fix incorrect session name.

scrapers/ma/people.py
Fixes https://github.com/openstates/issues/issues/170.
This may be premature and and presumptuous, but it seemed liked a quick thing to do. I haven't tested it locally; happy to go through the [setup](https://docs.openstates.org/en/latest/contributing/scrapers.html) if requested.
=> Don't change Massachusetts House district names

scrapers/mt/__init__.py
One bill is available on http://laws.leg.mt.gov/legprd/LAW0217W$BAIV.return_all_bills?P_SESS=20211
=> MT: Enable 2021 session as there is at least one bill

openstates/ky/bills.py, openstates/utils/media.py
#3177 
Just a test run of a common media type parser to save code duplication/hand-rolled solutions.
=> WIP Utils: Media type parser

scrapers/ut/__init__.py, scrapers/ut/bills.py
=> UT: add 2021 session metadata, and fix dots in bill id issue going forward

scrapers/wa/bills.py
https://github.com/openstates/issues/issues/203
=> WA: dont overwrite versions on chamber switch

scrapers/ny/__init__.py
=> NY: 2021 metadata

scrapers/wi/__init__.py, scrapers/wi/common.py
will address openstates/issues#214 once bills are present
openstates/issues#161
=> WI: 2021 metadata

scrapers/oh/__init__.py, scrapers/oh/bills.py
openstates/issues#216 and openstates/issues#161
=> OH: 2021 session and adjust SSL verification for some requests

scrapers/ms/__init__.py
Waiting on data, do not merge yet.
=> MS: 2021 session
