openstates/openstates-scrapers

openstates/ne/bills.py

Currently if the text is "Bill withdrawn", the type is "other". This should be "bill:withdrawn".

NE: A bill action of "Bill withdrawn" should map to the action type: bill:withdrawn

---

openstates/ky/__init__.py
openstates/ky/events.py

Currently all events are scraped three times, and attributed to multiple chambers. We can't fix this bug yet, though, since there isn't enough information up on the calendar site.

KY: Small events scraper fix, and error to prevent identical event scraping

---

openstates/mi/events.py
openstates/mi/legislators.py

No bad data ingested now. Committees still aren't posted, but that scraper now just errors from not finding anything.
Also, the janky bill scraper could be re-written to use this RSS, but we'd still have to keep all the current code in place for resolutions, which don't have an RSS. (We could also use this to completely revamp the events scraper.)
http://www.legislature.mi.gov/mileg.aspx?page=rssbills

MI: 2015 Session can go back online

---

openstates/ga/committees.py
openstates/mi/committees.py

The scraper gets committee members from `<a>` tags. Looks like this broke when the site added `<a>` tags with phone numbers (`billy-update mi --committees` was crashing). Skipping those tags.

fixes for #392 (MI committees) and AttributeError crash (GA committees)

---

openstates/ky/committees.py

jumped the gun on the prev PR, now committee-member matching works for a few members incorrectly formatted on KY's site.

KY: fixed double space issue

---

openstates/me/committees.py

page didn't change but location did.
NOTE: the new page (legislature.maine.gov/house/hsecoms.htm) has the wrong legislature number at the top, but includes some newly elected members, so I'm willing to just go with it.

ME: updated link for house committee page

---

openstates/ca/committees.py

committees were unavailable and we had thus manually set to throw an exception. They're available now so commented out the exception. Also a few minor fixes due to changes in class names.

CA: committees available and scraping

---

openstates/md/__init__.py
openstates/md/committees.py
openstates/md/events.py

Should we also turn events off? The hand-indented, blob-of-text that is MD's events schedule has completely changed, and will have to be completely redone if/when we want to scrape events

MD: events throw warning and do not scrape; minor bugfixes

---

openstates/id/bills.py
openstates/id/committees.py

joint committee pages are all different and need custom scrapers. Fixed the one that was crashing, but there are some committees we still aren't scraping.

ID: no longer crashing

---

openstates/az/bills.py

AZ committee votes have explanations of actions. If no action is available, we're now skipping the vote. I think this is rare, because this is the first time we've encountered this problem, and I only saw it once.
Helpful if we decide we want to try to do something else with these?
Here are the possible actions:
http://www.azleg.gov/CommitteeActions.asp
Here's a vote with no action:
http://www.azleg.gov//FormatDocument.asp?inDoc=/legtext/52Leg/1r/bills/sb1204o.asp&Session_ID=114

AZ: skipping committee votes with no action

---

openstates/fl/__init__.py
openstates/fl/bills.py
openstates/fl/legislators.py

We should be able to turn this scraper back on in full. The representative name issue (Jira bug 369) should be resolved as I'm now gathering Rep names from a more reliable page element.

FL: Updated for 2015 session, Rep names fixed

---

openstates/az/bills.py

An amendment did not have a html link, so now taking the pdf link instead if that happens.

AZ: no longer failing

---

openstates/tx/events.py

Trivial change. I'm going to pull this in right away so that our (many) Texas dependents can have their information back up; the scraper's been down since mid last week.

TX: Fix crash from irregular event time string

---

openstates/vt/legislators.py

Photo URLs are apparently case-sensitive in VT; was wondering why they weren't showing up in our photo scrapes! Eg:
`http://legislature.vermont.gov/assets/Documents/Legislators/TBurditt.jpg` (works)
`http://legislature.vermont.gov/assets/Documents/Legislators/tburditt.jpg` (500's)

VT: Fix photo URLs

---

openstates/tx/bills.py

Made an easy enhancement to grab all the other documents available for a bill. PR-review this _after_ #599, since this builds on the FTP crawling developed therein.

TX: Scrape fiscal notes, witness lists, and analyses

---

openstates/ma/legislators.py

thanks VERY much to @mileswwatkins for including the following error:
"AssertionError: Remove the special-casing code for Joseph McGonagle"

removed special case for McGonagle, seems to be standard now

---

openstates/tx/bills.py

Let's throw out all 84th-session `bill`s from the database, and then a fixed run will pull them all back in.

TX: Fix chamber mis-assignment

---

openstates/oh/bills.py

I'm unhappy about doing this, but over the last few days we've seen multiple new action codes per day, which has prevented _any_ of our builds from working, even if I add and rerun within a single day.

OH: Default action categorize to 'other'

---

openstates/ok/bills.py

`SENATE RES` and other such strings were getting captured as voters, and the wrong lines were being used for senate measure names.

OK: Fix senate motion names, avoid fake votes

---

openstates/oh/legislators.py

I think this is all there is to the fix, but as of now the Ohio House website is completely down. So wait until that's back up and test the `legislator` scraper before pulling this change in.

OH: Tweak subcommittee name

---

openstates/ut/bills.py
openstates/ut/legislators.py

This seems to be a fix for a one-off issue, where [SB 235](http://le.utah.gov/~2015/bills/static/SB0235.html) had a duplicate vote listed in its actions. The first of these had a [valid link to the vote](http://le.utah.gov/DynaBill/svotes.jsp?sessionid=2015GS&voteid=1765&house=S), and the second one had a [dead link](http://le.utah.gov/~2015/status/sbillsta/0). Included a `self.warning()` so that this doesn't proliferate without explicitly notifying us.

UT: Skip votes if their webpage returns a 404 error

---

openstates/tn/bills.py

It seems that TN is kind of fickle in terms of page loading - occasionally we're missing some information from a bill. The committed code is functional and no worse than we were before. Should we be doing some kind of check for incomplete pages, though? Anyone have thoughts on the best way to do that?
I spotchecked the data in openstates, and the ones I checked look complete, so possibly it's just a temporary fluke.

TN: not crashing anymore

---

openstates/fl/bills.py

This only allows "X" (standard vote) and "VA" (vote after roll call) as valid votes; it omits "AV" (abstained from voting) and other codes. The code _does_ confirm that the totals match the head counts, so after a full run I'm confident this change is correct.

FL: Increase precision of allowed vote codes for Senate committee rolls

---

openstates/oh/bills.py

I'm seeing `bills` in our database.
We'll need to fix this.

OH: Fix bad bill type

---

openstates/in/bills.py

text contained some extra spaces and thus failed to find some votes.

IN: fixed vote spacing issue

---

openstates/wv/bills.py

For one bill there seems to be no title anywhere (although all other information incl bill text is good and valid) so I'm just using the ID as the title in this case. @paultag, is this OK? Super non-urgent.

WV: workaround for missing bill titles

---

openstates/dc/bills.py

this doesn't fix the University of District of Columbia as a legislator who withdraws a bill - the only way I can think of to do that is to hard-code them in. @paultag how big a deal is it if we have them as a (unresolved) related_entity of type legislator in one bill?

DC: correct actor when mayor or committee withdraws a bill

---

scripts/non_unique_names.py

There is already a potential-duplicate script, but this is different enough that I figured I should give it its own file.

Add script to check for name duplicates that will break OS-OCD conversions

---

openstates/al/__init__.py
openstates/al/bills.py

Wait on @jamesturk's second opinion before pulling this in, but for now 2016's `do postback` doesn't function properly and so that session has to be ignored.

AL: Ignore the 2016 session for now

---

openstates/la/bills.py

On the index page each bill had two matches for the XPath `"//a[contains(@href, 'BillInfo.aspx')]"`.

LA: Stop double-scraping every bill

---

openstates/ms/legislators.py

A few members have other emails, such as cespy@gmail.com: http://billstatus.ls.state.ms.us/members/house/espy.xml

MS: Allow non-state-domain email addresses

---

openstates/co/votes.py

we were not detecting senate bills as new bills. now we are.
doing some research into whether we'll need to hand-delete the bad bills.

CO: fix misparsing of house votes on senate bills

---

openstates/nm/legislators.py

So, couple of questions:
1- do we care about adding area code to phone numbers? (Capital phones are only 7 digits long)
2- Is there a reason that home phone is in 'optional' as well as 'properties'?
if not is there a reason to keep this:
if found is False and key not in optional:
self.warning('bad legislator page %s missing %s' %
(url, id_))
return

NM: allowed for capitol phone if no office phone

---

openstates/wi/bills.py

We've been seeing a production bug involving the SSL for bill-subject HTTPS requests, so I'm just switching to HTTP. Confirmed working locally to the same effect.

WI: Remove SSL to avoid error

---

Dockerfile

Following [some advice](https://serverfault.com/questions/690639/api-get-error-reading-from-server-under-docker) to avoid the errors Docker Hub hit in the past couple builds.

Improve docker stability

---

openstates/ct/bills.py

Connecticut's SSL is causing problems with Scrapelib, so use Requests

CT: Fix SSL bug

---

openstates/ok/legislators.py

Scraper for the OK House was missing a legislator because of an off-by-one error in the index used to control the legislator scraping loop.

OK: Fixed off-by-one error in loop.

---

openstates/ny/events.py

The new version of the Open Legislation API does not appear to serve event data, so I am disabling scraping of upper chamber events until an update can be implemented to allow the other scraper elements to run.

NY: Disabled scraping senate events until an update can be found.

---

openstates/mt/legislators.py

The Montana scraper was running emails through a regex that stripped out the first part of many legislator email addresses. This slightly more permissive regex should fix that.
The old regex truncated emails like Sen.Bradley.Hamlett@mt.gov to Hamlett@mt.gov. This patch correctly parses these emails.

Fix MT email regex

---

openstates/tn/__init__.py

This is meant to be temporary.

TN: Disabled ignoring of 106th session.

---

openstates/in/bills.py

these bill versions don't seem to exist properly in the JSON. The bill I checked has at least 1 working version - my suspicion is that when they flipped the site to the new version in 2015 they only kept the most recent version of some older bill text but irritatingly left the others in the JSON. I'm just skipping the bad versions, there's not much else to be done.
This is super slow, probably because it tries to hit the 500'ing page multiple times with ever-increasing timeouts (that is in place because of other issues we've seen in IN). Presumably that's not a big deal because this only needs to run once to pick up all the historical bills so it doesn't matter if it takes 4 days (also not unheard of in IN...) but if it ends up implicating the new session, that probably needs to be fixed. …

IN: skip missing bill verisons for links that are 500'ing

---

openstates/id/__init__.py

Added 2016 Session information for Idaho.
Note: the display name for the legislature seems out of order from what's already in the code, but I went with the official source at https://www.legislature.idaho.gov/sessioninfo/2016/Journals/journals.htm .
This is my first PR for this repo, so please let me know if I should change how I do it in the future.

Added 2016 session info for Idaho

---

openstates/ri/legislators.py

Sen John A. Pagliarini is missing a District Office Address.

Fill in 'No Address Found' for one missing address to allow rest of scrapers to run.

---

openstates/nm/bills.py

HB0055 has copy versions (http://www.nmlegis.gov/Sessions/16%20Regular/bills/house/), which was breaking the scraper.

skip text versions that have - COPY in name

---

openstates/wa/bills.py

The Washington Legislative Information Center has fixed this issue upstream, so the patch is no longer necessary.

WA: Removed patch for wrong bill data.

---

openstates/al/__init__.py

By the current code if you do a 'billy-update al bills' it tries to pull from the 2015 second special session, because that's the last session identifier in the code. 
The 2016 Regular Session is live, so we need to move that identifier to last so that becomes the default if you don't specify a session.

Move AL 2016 session identifier so it becomes default AL session

---

openstates/mn/legislators.py

Brings the Minnesota scraper's storing of legislators' website urls in line with the API schema.

MN: "url" for legislator's website instead of "leg_url"

---

openstates/wa/bills.py

Thanks to @Skekacs93 for the underlying fix.  Needed to tweak the regex.

WA: Accounted for bill documents not beginning with a bill number.

---

openstates/nj/bills.py

New Jersey added a bill to their DB with an IdenticalBillNumber that existed but was just whitespace, which was causing an error on line 189 of NJ bills.py:
line 189, in scrape_bills
bill.add_companion(rec['IdenticalBillNumber'].split()[0])
IndexError: list index out of range
This patch fixes that issue so that an IdenticalBillNumber of '  ' doesn't evaluate to true and trigger the if loop.

Fixed bug where blank IdenticalBillNumber broke NJ scraper

---

openstates/mn/legislators.py
openstates/ok/legislators.py
openstates/utils/__init__.py

- Handle variances in senators' name, party, and office details format
- Extract representatives' email addresses
- Reuse email validation function from mn.legislators, moving it to
openstates.utils
An example of one of the more aberrant senator pages is that of J.J. Dossett (http://www.oksenate.gov/Senators/biographies/dossett_bio.aspx). If the moving over of the validation function is not the preferred solution, I'm happy to adjust and resubmit.

OK: Modest update

---

openstates/la/events.py

The scraper was failing due to embedded HTML in the last meeting here http://house.louisiana.gov/H_Sched/Hse_MeetingSchedule.aspx -- so strip out the HTML from the table cell we need.

Fixed embedded HTML in LA event location breaking scraper

---

openstates/ia/events.py

The Iowa events scraper wasn't saving any objects due to changes in the page HTML. This update fixes that.

Fix IA Events Scraper

---

openstates/wa/bills.py

WA bill scraper was failing due to a missing ordinal for '5', so I added the next few in the sequence just to be safe.

Added additional ordinals missing in WA bill scraper

---

openstates/ok/bills.py

The scraper was attempting to add the last two Conference Committee Reports as bill versions: http://www.oklegislature.gov/BillInfo.aspx?Bill=SB85&session=1600.

OK: added SCHEDULED CCR to Committee Report document check

---

openstates/ok/bills.py

This is because the URLs we filter on are not in a consistent case.

OK: Made filter regex case-insensitive.

---

openstates/ia/votes.py

The last block of names for S.J.R. 2007 in the [Iowa Senate Journal](https://www.legis.iowa.gov/docs/Pubs/sjweb/PDF2/2016/02-24-2016.pdf) was also pulling in the remaining text of the document because it was not properly reading an indicator for the end of the block.

IA: Added senate resolutions to vote block end indicators.

---

openstates/ca/download.py

This wouldn't work with Feb. 29 as it is an invalid date without a leap
year attached.

CA: Fixed attaching year to download date.

---

openstates/fl/events.py

The FL events scraper was broken because the Senate changed their feed. This rewrite makes it work again for the senate.

Reworked FL Senate Event Scraper for new feed 

---

openstates/ca/legislators.py

See any lower-chamber member; e.g., http://openstates.org/api/v1/legislators/?state=ca&chamber=lower&district=22
This patch fixes:
- "CA" showing up twice in assembly members' addresses
- District addresses being classified as capitol addresses, and capitol addresses not being included at all

CA: Fix assembly member address parsing, address type classification

---

openstates/tn/bills.py

TN is only showing 100 bills at time on their listing page, so scrape the index of listing pages, then hit every listing page link.
Also, remove double-space in bill names.

Fixed TN Bill scraper to respect pagination

---

openstates/nd/legislators.py

Street names in North Dakota appear rife with directional suffixes. This is a tiny patch to prevent ambiguous addresses such as "752 51st Street South Fargo, ND" (the city of Fargo and not South Fargo) and "1822 Brentwood Court West Fargo, ND" (the city is West Fargo and not Fargo).

ND: Preserve vertical whitespace in addresses

---

openstates/ri/events.py

http://status.rilin.state.ri.us/documents/agenda-11786.aspx

RI: minor events scraper fix (catches 'Rise of House' as time)

---

openstates/nm/__init__.py
openstates/nm/committees.py
openstates/nm/legislators.py

This is for [DATA-499](https://sunlight.atlassian.net/projects/DATA/issues/DATA-499).
Data is being pulled from the NM legislature's [new site](http://www.nmlegis.gov:8080/). Specifically, http://www.nmlegis.gov:8080/Committee/Default is the root from which committee scraping starts.
This version of the scraper maintains the use of "interim member," "interim co-chair," etc. that the legislator scraper was assigning when it was used to get committee information. It seems that in NM's case "interim" does not seem to mean "temporary until something permanent comes along." "Interim" seems to mean committees that meet when the legislature is not in session. At least that's what I gathered [by Googling](https://www.google.com/webhp?#q=new%20mexico%20legislature%20interim%20committees). If that …

NM: add committee scraper, remove committee roles from legislators scraper

---

openstates/ri/events.py

http://status.rilin.state.ri.us/documents/agenda-11845.aspx: 2:30 - 3:30 PM was breaking the events scraper, so I added a minor check that just pulls out the start time in this case.

RI: minor fix for event with duration specified in time

---

openstates/az/bills.py

A good amount of bill actions have been being missed because the scraper only looks for actions within the table with class='ContentAreaBackground'. This adds the actions that are outside this table. Example: http://www.azleg.gov//FormatDocument.asp?inDoc=/legtext/52Leg/2r/bills/sb1010o.asp&Session_ID=115.

AZ: fix for missing actions

---

openstates/nm/__init__.py

Retrieve sessions from the options on the main page of the new NM legislature site.

NM: use new site for session scraping

---

openstates/nm/__init__.py
openstates/nm/bills.py

Sets the "source" for each bill to the location of that bill on the new site. (For example, like http://www.nmlegis.gov:8080/Legislation/Legislation?chamber=H&legType=B&legNo=1&year=16)
Main data is still retrieved from the same ftp location.
Documents (like PDFs for votes) are still retrieved from the same locations. (Fior example, like "http://www.nmlegis.gov/Sessions/16%20Regular/firs/")

NM: reference NM legislature's new site in bill scraping

---

openstates/ky/bills.py

KY HB15 has an action with a blank in between two semicolons - "; ;". This is being interpreted as blank actions and blowing up the scraper.
http://www.lrc.ky.gov/record/16RS/HB15.htm
This hotfix ignores blank actions to avoid the validation error and allow the scraper to continue.

don't try to add blank actions to bills in ky

---

openstates/nm/__init__.py
openstates/nm/bills.py
openstates/nm/committees.py
openstates/nm/legislators.py

The new NM legislature site is live and now works without port 8080 in the addresses. This removes `:8080` from all addresses.

NM: remove port 8080 from addresses.

---

openstates/ia/__init__.py

Fail gracefully if disable_warnings not available.
See [this](https://github.com/jkbrzt/httpie/issues/418)

Handle failure when disable_warnings is not available

---

openstates/nh/__init__.py
openstates/nh/bills.py
openstates/nh/legacyBills.py
openstates/nh/utils.py
requirements.txt

NH stopped updating their bulk data, but has exposed a SQL database for 2016 bill data that updates live.
Output differences:
1. Roll calls on all votes
2. Addition of subjects for bills
3. Removal of hearings from bill actions. Events scraper to come.
4. Support for multiple bill versions
5. Cleaner Bill Action and Vote names.
6. IDing of Primary sponsors vs CoSponsors
The Legacy scraper code is untouched except to rename the NHBillScraper class.
Note: to get this running on OSX you'll need to 
brew install freetds 
on ubuntu:
export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1
pip install mssql
on windows:
http://www.pymssql.org/en/latest/freetds.html

NH Bill Rewrite

---

openstates/nm/bills.py

NM was incorrectly tagging all bill versions as text/html. This checks for filenames ending in "pdf" and assigns the appropriate mimetype.

Added check for PDF mimetype instead of assuming text/html

---

openstates/ak/bills.py
openstates/nm/bills.py

The AK scraper was failing on a blank journal entry.
It was also missing all bills with number > 999, which are all the bills from the 5 special sessions. I upped the max bill number to 9999.

AK missing bills and fix error

---

openstates/ny/bills.py

NY bills were adding versions with bad URLs, by just creating a new bill_version with the version name twice instead of the version name and the URL.
This fixes that, and assumes in case of name conflict that updated urls are correct.

Fix broken NY bill version urls

---

openstates/hi/bills.py

Correctly classify vetoes, line-item vetoes, and veto overrides in HI.

Added veto action parsers for HI

---

openstates/tn/legislators.py

As stated in the issue, it looks like lxml parses the DOM tree differently when [BOM](http://unicode.org/faq/utf_bom.html) are at the start of a stream of HTML text.  Running the scrape, it looks like only the pages for Senate District 19 and District 4 are affected in the 109th GA.
The "h1" element holding the name is still present for the District 19 page.  District 4 uses the fallback handler, which was still working despite the BOM.  To handle the normal case for "h1" names, and this BOM case, the diff replaces "body/div/div/h1..." with "//h1".  This still scraped names correctly for the remaining 109th GA senators and house members.
Closes  #1172

Issue 1172 - handle name parsing when BOM messes w/ XML tree

---

openstates/sd/__init__.py
openstates/sd/bills.py
openstates/sd/legislators.py

Requests to `legis.sd.gov` are re-directing to `www.sdlegislature.gov` and scraping will not complete. This is to change the URLs to the new one. Also, some div IDs have changed on the site, and scraping was not working because of those. I have corrected those as well.

SD: change URLs to use www.sdlegislature.gov

---

openstates/ok/__init__.py

OK added some junk to the 2017 session in their dropdown, so until they fix it, change the scraped name.

Workaround for OK website bug with 2017 session display

---

openstates/mo/bills.py
openstates/mo/legislators.py

Absolute minimum code to get MO working for 2017 session. Senate membership (and comms) hasn't been updated yet, but all bills and house members and comms are looking good, including data quality check.
Inferior to https://github.com/openstates/openstates/pull/1075, but quicker to integrate.

MO: Update for 2017 session

---

README.rst

Fix #1222 
Fix the command included in the `README.rst` for running the test suite,
as the previous command specified the command line flags in an incorrect
order.
Signed-off-by: mattjmcnaughton <mattjmcnaughton@gmail.com>

Fix README.rst test command

---

openstates/utils/lxmlize.py

Fix #1214 
Convert the `LXMLMixin.lxmlize` method to use the `get` method defined
by the subclass of `billy.Scraper` for which `LXMLMixin` will serve as a
mixin, instead of `requests.get`. Using the scrapers `get` method uses
cached responses during `--fast` scrapes, which saves time.
Signed-off-by: mattjmcnaughton <mattjmcnaughton@gmail.com>

Use `Scraper.get` in `LXMLMixin.lxmlize`

---

openstates/ms/legislators.py

MS legislator scrape is failing due to new legislators w/out parties. This fixes it.

MS: Adjust list of legislators with manual party assignments

---

openstates/vt/bills.py

We weren't grabbing all the VT bills because there's a stage before 'introduced' in their system.

VT: Add filed bills to list of fetched bills

---

openstates/mo/legislators.py

- Prevent addition of former legislators by referencing only current rosters
- Rewrite of senate scraper due to new layout of senator pages
- Ensure email addresses are included in house members' office details
- Sundry, small adjustments for PEP8 conformance and clarity of variable names
In case of mid-term legislator changes, both members were being added:
- http://www.house.mo.gov/member.aspx?year=2015&district=029
- http://www.house.mo.gov/member.aspx?year=2016&district=029
It turns out that the MO House site will bring up the current legislator if the year is excluded:
- http://www.house.mo.gov/member.aspx?district=029

MO: Prevent legislators from prior sessions from being added, other adjustments

---

openstates/in/__init__.py
openstates/in/bills.py

Scraping votes/versions is causing the scraper to hang, maybe because the session is missing in the openstates api? 
This adds 2017 to the metadata and comments out the function that breaks the bill scraper.

[WIP] IN: Add 2017 session and temporarily stop version scraping

---

openstates/ia/bills.py

IA is currently naming all of their actions $history.getTransformedActionTextWithBillBookUrl() ... so ignore those.

IA: Ignore bill actions that are actually a website error

---

openstates/ar/bills.py

Ar has this stray datetime that ends in .520000000 in their bulk data file (and only one). This is a manual fix. If it happens again I'll look into a more robust solution.

AR: fix for crazy stray float in bulk actions file

---

openstates/ky/bills.py

KY has started posting additional bill versions, amendments, and fiscal notes in their bill pages. (e.g. [HB3](http://www.lrc.ky.gov/record/17RS/HB3.htm)). This patch captures them.

KY: Capture all bill versions and fiscal notes

---

openstates/ny/bills.py

NY has a bill whose JSON object doesn't contain a 'sponsor', which broke the bills scraper. This adds a check for that.

NY: fix missing sponsor breaking scraper

---

openstates/nj/bills.py

NJ has some bad document URLs linked on the site (ending in HTMX when they should end in HTM), so fix them on all documents, not just certain types.

Fix HTMX links in NJ

---

openstates/ar/bills.py

AR started a new bill version url format, just for 2017 bills.

AR: fix 2017 version urls

---

openstates/id/bills.py

Idaho's scraper wasn't picking up a bill versions due to a change in their HTML.

ID: Add missing bill versions and documents

---

openstates/mn/bills.py

MN was missing all sponsors. This fixes, assuming the first in the list is the primary. Resolves #1271 .

MN: Fixes MN sponsors, assuming first is primary. 

---

openstates/vt/bills.py

VT changed the location in the source of their bill version links, but left a comment in the HTML with a TODO to move it back. This updates the versions xpath to take either spot, in case they move it back.

VT: Added new xpath for bill versions

---

README.rst
docker-compose.yml

So that devs don't have to run a separate local mongo, and to make the quickstart Just Work.

Add docker-compose config.

---

openstates/id/bills.py

ID was incorrectly breaking committee sponsors on space, so you would get "Revenue" "Taxation" as sponsors on "Revenue and Taxation Committee". This fixes that.
I'm assuming here that multiple committees can't sponsor a bill in ID, and there aren't any this session or last. If there's a counter-example let me know and i'll PR a more complicated regex.

ID: don't word break committee sponsors

---

openstates/mo/legislators.py

Switch the scraper for the MO senate from http://www.senate.mo.gov/CurrentRoster.htm to http://www.senate.mo.gov/senators-listing/.
The relative position of the table on the new listing page is differentt, but the columns of the table, and the structure of the content within each column is exactly the same.
`if rowcount < 2:` has been changed to `if rowcount <= 2:`. This line of code, as indicated by the comments, is meant to skip the first two rows of the table, both of which are headers. But using strictly `<`, the second row has `rowcount=2` and is not skipped. I don't know if/how this functioned in the original scrape, but have confirmed that with this change, the first row "Dan Brown" is scraped correctly, and without the scrape fails.
Verifying the output, I noticed that the …

MO: Use new senate listings page

---

openstates/nj/committees.py

Only one committee was ever saved per session, because `save_committee` was only being called once at the end of the script.  This updates the script to iterate over the scraped committees at the end of the script and save each one.

NJ: Fix for missing committees

---

openstates/wv/legislators.py

Scraper for WV has been failing for past few days. This small fix allows the scraper to also look for the I standing for Independent party.

WV: Allow scraper to also pull Independent party

---

openstates/ks/committees.py

Fix for #1260
The KS scraper was breaking on Committee documents like [this one](http://www.kslegislature.org/li/api/v7/rev-1/ctte/ctte_hcsf_1/)
```
...
APPOINTMENTS: [ ],
CHAIR: [
{
KPID: "nonleg_hayzlett_gary_1"
}
],
...
```
...because the scraper was looking for a `FULLNAME` key. 
Instead, if there's no fullname provided for the committee info, parse the KPID provided in a bit of a rudimentary way, assuming a standard format for the ID is consistent. In this case, seems like the committee chair was NOT a legislator and so the full information was not provided. However, info could be gotten out of a (hopefully) consistently formed ID.

KS: Update parser for committee chair name to account for no FULLNAME

---

openstates/va/bills.py

VA started linking to some offsite bill versions, but we were always prepending BASE_URL to the versions, which broke non-relative urls.

VA: For bill versions, only add BASE_URL to relative paths

---

openstates/co/bills.py

CO's bill scraper had an off-by-one error that was causing one page of results (25 bills) not to get scraped.

CO: Fix off-by-one error keepign some CO bills from being scraped

---

openstates/az/legislators.py

#1332  The legislator's pages list phone numbers in the (602) xxx-xxxx format.  This caused the old logic to think the area code missing.  Changed the logic to be more permissive, although no current legislator needed their phone number fixed so the usefulness of the check is questionable.

AZ area code detection logic fix #1332

---

openstates/or/legislators.py

#1330 The method that was attempting to remove non-printable characters did not handle the cases where some non-printable characters were not removed via strip(), due to this [issue](https://bugs.python.org/issue13391).  The character being reported in this issue was the unicode zero-width space, this PR removes all control-character from the name and leaves normal unicode characters in place.

OR: Handle valid unicode characters as well as unicode encoded names 1330

---

openstates/mo/committees.py

In addition to "Assigned bills", the link text was also sometimes "Assigned Bills".  This was allowing some links to committee bills to be used as the committee details page, which caused the script to crash.
This also skips sessions without any session details from being scraped.  The script was crashing when it tried to process the 2018 session of the "2017-2018" term, which is not available yet.
Closes #1319

MO: Make "Assigned bills" filter for committee links case insensitive

---

openstates/in/bills.py

This should fix #1287, although i don't have an API key for Indiana's API, and haven't tested it.

strip leading zeros from bill IDs #1287

---

openstates/ri/legislators.py

the colnum is excel_mapping was off,
which caused the array out of index error.
Fixes issue #1351

fixed colnum in excel_mapping for RI #1351:

---

openstates/oh/legislators.py

#1350 The scraper was failing due to two unknown subcommittees.  One subcommittee was new,  "Finance Subcommittee on State Government and Agency Review", the other was just had its punctuation removed(was the only subcommittee that used commas previously).
I thought about trying to recreate the list subcommittees programmatically instead of using static assignment, but the committee list page is using a somewhat archaic way to align the text/divs on the page(hint, it involves pressing the space bar a lot), the odds of anything "smart" being used to detect subcommittee hierarchy seemed too fragile.

OH Legislator scraper failing #1350

---

openstates/nh/legislators.py

Spreadsheet column names changed,
as well as inconsistencies in party
naming (lower and uppercase)--forced all to upper

NH leg fix #1349:

---

openstates/wi/bills.py

Junk characters in the wisconsin vote pages [example](http://docs.legis.wisconsin.gov/2017/related/votes/assembly/av0002) were causing the vote parsing regex to fail. 
The related documents function was grabbing too many site links due to an HTML format change, so I made it stricter so it doesn't add site navigation items as related documents.

WI: Fixed bill vote parser, and made related document xpath stricter

---

openstates/nc/committees.py

This strips leading "Rep. " and "Sen. " from committee members to help with name matching. NameMatcher seems like it is treating "Rep. Adams", for example, as a person whose first name is "Rep. ".
This silences the warning "No matches for" for all but two members.  Member "Brenden Jones" should match Rep. Brendan H. Jones, and  member "R.Turner" should match Rep. Rena W. Turner.
Close #1342.

NC: Strip leading "Rep. " and "Sen. " from committee members to help with matching

---

billy_settings.py

Resolves #1371.
For backwards compatibility, we could only set the data and cache paths if provided in the environment and pass them from docker-compose, but IMO it makes more sense to locate data, cache, and manual data in the same place.

Expose billy data and cache.

---

openstates/wa/bills.py

See for example:  http://app.leg.wa.gov/billsummary?BillNumber=5000&Year=2017
Current Bill Id WAB00013657 has this wrong (so this fix may require cleaning the cache)

Fix off-by one. upper chamber is >= 5000, not > 5000

---

openstates/co/actions.py
openstates/co/bills.py

Fix failing scrape by assuming votes without a chamber are in the bills chamber.
Added committee amendments to versions, which we weren't collecting. Added a few more action categories.
I believe this will resolve #1379 by allowing the broken roll call proceed.

CO: Fixed broken scraper

---

docker-compose.yml
openstates/ca/README.rst
openstates/ca/__init__.py
openstates/ca/bills.py
openstates/ca/download.py
openstates/ca/models.py

Note: optionally running the CA downloads in `__init__` feels like a hack. Anybody have a better idea? Maybe we expose another command in docker-compose to load the CA database?

Run mysql for ca scraper with docker-compose.

---

openstates/wi/__init__.py

WI Added their january special to the website which broke the bills scraper. 
There don't seem to be any bills [here](http://docs.legis.wisconsin.gov/2017/proposals/JR7/) -- given the dates i'm wondering if they didn't make it to the website or if they just got rolled into the Regular.
If they do post the bills back later, let me know and I'll add it as a real session.

WI: Ignore january special session with no bills, fix 2017 end date

---

openstates/la/bills.py

We weren't capturing amendments in LA, and sometimes they don't publish a new full text after passing an amendment, so they're critical.

LA: Capture amendments

---

openstates/ct/legislators.py

Re https://github.com/openstates/openstates/issues/1217
CT Legislator scraper was raising an error on an invalid email address. The scraper was trying to skip contact form URLs in the email field, but looks like a new one was added to the data that looks different from the ones that were there before.
This patch handles all the contact form URLs found in the email field, putting None for email address if the value present is actually a contact form URL, and putting those contact form URLs into an extra field, "contact_form".

Senator Emails are mailforms - CT State Legisaltors #1217

---

openstates/ma/bills.py

#1366 Due to a bug on the MA page, always make a call for cosponsors since we can no longer intelligently find it.  Bills without cosponsors will not fail/except due to this change
@jamesturk You might want to hold off on merging this for a few days.  I contacted the webmaster of the MA website and reported the bug.  I'm submitting the PR now to clean up my branches but would like to give them a chance to respond and fix the issue before we commit to always trying to pull the cosponsor page.

MA_find_cosponsor_1366

---

openstates/ma/bills.py

MA has added a bill type since this scraper was written, and it was overwriting S with SD content.

MA: Edit bill cleaning regex to differentiate S from SD

---

openstates/co/bills.py

if there's no info in the vote header, simply return and then no vote information will be saved. 
There were a few pages [like this one](http://leg.colorado.gov/bills/hb17-1045) that are supposed to have date and committee info in the blue header on the Committee Action page - instead there is just a blank '|' -- if this is the case, you can't seem to get the vote date from another
source, so just return nothing

CO: Check for info in the vote header before trying to parse information

---

openstates/mt/bills.py

MT changed their bill version URLs, so we were adding some broken versions.

MT: Fix bill version URL

---

openstates/ma/legislators.py

It seems MA has changed from R to Republican on their pages.

Fix #1440 by allowing the code to accept a variety of party naming schemes. 

---

openstates/fl/bills.py

Fixes this error:
```
TypeError: not all arguments converted during string formatting
Call stack:
File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
load_entry_point('pupa', 'console_scripts', 'pupa')()
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
subcommands[args.subcommand].handle(args, other)
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 288, in handle
report['scrape'] = self.do_scrape(juris, args, scrapers)
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 166, in do_scrape
report[scraper_name] = scraper.do_scrape(**scrape_args)
File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 101, in do_scrape
for obj in self.scrape(**kwargs) or []:
File …
```

FL: Fix info log.

---

openstates/ok/__init__.py

OK has been putting (mainsys) after various sessions in their dropdown off and on for a few months. Rather than manually change it each time, filter it out of the session_list.

OK: Strip (mainsys) out of session listing

---

openstates/ok/legislators.py

Resolves #1456:
Alternatively, we could scrape seats with no representative and mark them as open in some way.

OK: Handle seats with no representative.

---

scripts/convert_metadata.py

Because some states don't currently include classifications in session details.

Handle missing session type.

---

openstates/ri/legislators.py

This restructure the RI to efficiently retreive the photo_url.
This uses the contact information page to retreive the detail link, instead of trying to match
the link to the representatives name.  On the contact information page, the link is associated
directly to the district.
This moves retreiving the contact information outside of the spreadsheet loop so we can utilize
the contact information more efficiently.
This removes the representatives listings page, e.g. http://www.rilin.state.ri.us/senators/default.aspx, as a source, since it is no longer used.
This prefers the email address in the contact information to that in the spreadsheet. I manually verified that the contact information always has valid email addresses, while the spreadhsheet sometimes has web page links.
This fixes the …

RI: Restructure legislator scrape to efficiently retrieve photo_url

---

scripts/convert_metadata.py

* Skip unused `datetime` import
* Fix indentation on sessions and ignored sessions

Make generated pupa code flake8-compliant.

---

openstates/co/bills.py

CO Bill scraper was dying because they published a version without a pubdate.

CO: Allow versions without publish dates

---

README.rst
docker-compose.yml

I noticed some questions about building docker images on slack, and it occurred to me that there's no reason for most users to be building images in the first place. This patch pulls images from dockerhub instead of building, which is probably how I should have written this in the first place.

Pull images from dockerhub.

---

openstates/de/committees.py

#1445 
Updated committees scrapper by mapping of term names to session numbers for 2017.

de: committee scraper updated for 2017

---

openstates/la/bills.py

The current regular expression was saving "Total --" strings as voter names, because it looked for "Total--", without a space between total and the double dashes.
This also removes vote totals being set directly from the "Total --" count - these are written over using the number of entries in each array at line 187.
Closes #1527.

LA: exclude "Total --" correctly from vote names

---

openstates/hi/bills.py

This fixes the issue with Hawaii names noted in #1528. I've verified the output by searching for sample bad names using the following query:
```js
db.votes.find({"state": "hi", $or: [{"yes_votes": { $elemMatch: {"name": "Onishi; "}}}, {"other_votes": { $elemMatch: {"name": "Onishi; "}}}, {"no_votes": { $elemMatch: {"name": "Onishi; "}}}]})
```

HI: Remove trailing "; " from vote names

---

Dockerfile-pupa

The NM bills data is collected from a Microsoft Access file, and mdbtools is used for reading it. The scrape container needs it to be able to read the file.

NM: add mdbtools to Docker for pupa.

---

openstates/ca/bills.py

CA put a vote into the mysql database missing key information, so skip it so the scraper doesn't choke.

CA: Skip votes with no metadata

---

openstates/nh/bills.py

Fixes two issues with the NH voter name scrape.
* Similar to an earlier fix for the vote counts, this adds `splitlines()` to the file so that it is processed line by line instead of character by character.
* In addition, this handles an extra two columns being returned when splitting each line.
Confirmed that votes were not being saved with the bug in the voter name scrape, and they are with the fix. This fixes the underlying cause of #1563.

NH: Fix vote names scraper

---

scripts/convert_metadata.py

Fixes `E226 missing whitespace around arithmetic operator` in generated jurisdiction classes.

Fix lint in converted jurisdiction.

---

openstates/md/bills.py

Closes #1512.  I don't know what these asterisks represent, but we aren't losing any information by just removing them for now.

Strip "*" from MD voting legislator names

---

openstates/co/bills.py

CO Added some new actions with no chamber marked, which broke the bill scraper. All the current ones without chamber are joint, so adding that to the logic.

CO: Fix chamber-less joint bill actions

---

openstates/az/bills.py

AZ: Add actions for Transmit to [house/senate/governor/secretary of state], and governor sign/veto, and PDF fallback for versions with no HTML copy.

AZ: Add transmit to actions, additional bill version formats

---

openstates/mi/legislators.py

This gets 27 Senator's email addresses, leaving 11 that only have contact forms.

Add code to find emails on MI senator's contact pages.

---

openstates/me/legislators.py

ME phone numbers are mostly 7-digits, missing the 207 area-code prefix.

Fix ME phone numbers to include area-code.

---

scripts/convert_metadata.py

Looks like we accidentally deleted the lower chamber metadata in #1550. This also allows `_ignored_scraped_sessions` to be missing.

Fix regression in metadata conversion.

---

openstates/il/bills.py

Fixed #1665 
Now `as ` is removed from `official_type` field.

IL: "official_type"  field enhancement.

---

openstates/il/events.py

Fixed #1668
New Updates:-
`"description": "Appropriations II, Subject Matter on: FY18 budget request of the following agencies: SB2157-WIU, SB2158-ISU, SB2159-NIU, SB2160-SIU, SB2161-U of I, SB 2157, SB 2158, SB 2159, SB 2160, SB 2161"`
and
`"participant": "Appropriations II",` instead of  `"participant": "Hearing Notice For  Appropriations II"`
Let me know If we don't need `Subject Matter on:` in `description`.

IL: Added subject matter field to description and fixed participant

---

openstates/co/votes.py

Noticed Tuesday misspelled as Tueday in a few different Colorado PDFs. This gets vote scraping working locally and should fix #1695.

CO: Fix date typos.

---

openstates/hi/bills.py

Handle cases like http://capitol.hawaii.gov/measure_indiv.aspx?billtype=SB&billnumber=1183&year=2017, which has the correct url but not the normal markup. Should resolve #1696.

HI: Parse bill identifier from url.

---

openstates/az/action_utils.py
openstates/az/bills.py

Looks like we dropped passage and failure action categories in https://github.com/openstates/openstates/commit/b7f79515647be7a0b6fab9f71bdc41dce2740d50. This restores some categories. Should resolve #1676.
@jamesturk @showerst

AZ: Handle bill passage and failure.

---

billy_metadata/mt.py
billy_metadata/nc.py
openstates/mt/__init__.py
openstates/nc/__init__.py

Just noticed it. So moved `session_list()` to __init__.py file for MT and NC.
Note:- Removed `extract_text()` from Montana's __init__.py file. If we need this one then should I add `text_after_line_numbers() & pdfdata_to_text()` to `openstates/utils`? These functions are used in other state __init__.py files also.

MT, NC: session_list() movement

---

pupa2billy/bills.py
pupa2billy/committees.py

For example, we're setting extras on committee memberships in MO, and on actions and bill documents in GA (WIP).

Add extras to more billy models.

---

billy_metadata/tn.py
flake8.sh
openstates/tn/__init__.py
openstates/tn/bills.py
openstates/tn/committees.py
openstates/tn/common.py
openstates/tn/events.py
openstates/tn/people.py

All conversions followed the generic migration plan outlined [in the pupa conversion docs](http://docs.openstates.org/en/latest/contributing/pupa-conversion.html), except where otherwise noted.
* replaces `HTMLParser` with it's Python3 equivalent `html.parser` (used to unescape the email addresses, maybe unnecssarily but leaving it for now)
* replaces calls to `self.lxmlize` with
```python
html = self.get(url)
page = lxml.html.fromstring(html)
```
Only generic conversion steps
* ignores duplicate fiscal notes for house and senate - see the Amendments section for [this bill]( http://wapp.capitol.tn.gov/apps/BillInfo/default.aspx?BillNumber=HB0018&GA=110) for for an example.
* updates "other" votes to be "not voting", a more accurate reflection of the votes being cast
* Use …

Convert TN to pupa

---

openstates/mi/committees.py

Handle committee titles like "Commerce Committeee", which otherwise
resolves to "Commercee".
Should fix issues like:
If we have a contact at Michigan, we could also ask them to fix the typo in the header of http://www.senate.michigan.gov/committee/commerce.html.

MI: Handle committee names with misspelled "committeee".

---

openstates/ak/events.py

Skip events like http://www.akleg.gov/basis/Meeting/Detail?Meeting=SFIN%202017-05-24%2009:00:00#tab2_4e to avoid validation errors.

AK: Skip events without names.

---

openstates/nj/bills.py

Distinguish between committee and floor votes so that vote counts aren't
combined across different vote events.
Per @fgregg, we might also want to capture the committee as a `bill_action`, but I'm not sure how that would work--cc @jamesturk

NJ: Separate votes by committee.

---

openstates/nd/bills.py

#1790
There is no `Bill ID and Type` listed on [Link](http://www.legis.nd.gov/assembly/65-2017/subject-index/sijudicial+branch.html) for `JUVENILE JUSTICE PROCESS STUDY` and their URLs are also broken.

ND: bills IndexError problem solved in scrape_objects

---

openstates/wv/bills.py

#1794
This PDF file is the main cause of the problem. There may be others in future like this. so not sure how to handle these type of warning/errors.
```
02:04:15 INFO scrapelib: GET - http://www.legis.state.wv.us/legisdocs/2017/1X/votes/house/00662.pdf
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Traceback (most recent call last):
.........................................
```

WV: UnboundLocalError

---

billy_metadata/wi.py
openstates/wi/__init__.py
openstates/wi/bills.py
openstates/wi/common.py

Add the now-active 2017 Special, and don't scrape subjects twice, since the generated mapping is for both lower and upper.

WI: Add 2017 session and remove some redundant scraping.

---

openstates/tx/votes.py

First attempt at addressing issue #1782.
The existing scraper would split the list of names on semi-colons. It looks like, for the latest session at least, the Senate used commas. (The House still used semi-colons.) You can see the effect of this on, for example, [SB 16](https://openstates.org/tx/bills/85/SB16/), where the House vote page lists a separate entry for each person, but the Senate vote page doesn't split out the names.
Good:
Bad:
The attempt in this PR is to split by semi-colons, and if that result doesn't seem to have created a plausible number of separate names, try splitting by commas. This feels admittedly hacky. 
If it's not too much trouble, I would love advice on better ways to attempt the fix as well as a solid strategy for verifying that I didn't make it worse. I'm …

[WIP] TX Votes: parsing legislators' names more successfully

---

openstates/ok/committees.py
openstates/ok/people.py
openstates/ok/utils.py

This is a workaround for getting pages off okhouse.gov's TLS 1.0 server, which python's core ssl module seems to have trouble talking to.
My system `curl` is compiled with GnuTLS, which may be the key to it working. I'm not sure whether a `curl` compiled with OpenSSL will also be successful.

OK: Replace proxy server usage with curl shell command

---

.gitignore

For those that use PyCharm (https://www.jetbrains.com/pycharm/), it creates a hidden directory in the root of the code base called .idea. I simply added this folder to the .gitignore so it does not show up as a change.

Adding pycharm files to .gitignore

---

openstates/ca/bills.py

Fixing issue #1802 since the organization passed into the `VoteEvent` always defaulted to `None` for assembly votes, which was then interpreted by `pupa2billy/votes.py:process_vote()` as always referring to the upper chamber.
Now floor votes are ascribed to the correct chambers, which allows Assembly votes to be pulled in properly.

[bugfix] CA assembly votes assigned proper chamber

---

billy_metadata/ri.py

This fixes issue #1813 by getting rid of a metadata parameter which controls a (seemingly deprecated) hack in billy.

[bugfix] RI votes imported #1813

---

openstates/ak/bills.py

Alaska changed the committee abbreviation for their Arctic Policy committee, which broke the scraper. I left the old one in to allow previous session scraping to continue to work.

AK: add new committee abbreviation

---

openstates/mi/people.py

Sorry, was late in making a PR for this. I see the particular recent broken member URL was special-cased. This will at least prevent future such instances from causing the MI people scraper to terminate.

MI: Handle broken member URLs and missing photos gracefully

---

openstates/nj/people.py

Email addresses for NJ assemblywomen are `Asw[last_name]@njleg.org` and not `Asm[last_name]@njleg.org`.

NJ: Fix email construction for assemblywomen

---

openstates/fl/bills.py

Added to action type elseif to identify executive signature and veto actions.
Fixes #1950

FL: Fix No executive actions recorded 

---

openstates/ct/bills.py

State: CT 
CT has some line-item vetoes now, so correctly classify those actions.
Test bill: 
https://openstates.org/ct/bills/2017/SB1502/

CT: Classify line item vetoes

---

openstates/al/bills.py

Alabama has no entries for 2017 showing bill signature.  In reviewing the data on the Alabama site there doesn't appear to be a specific entry in the actions for the governor's signature, just entries where it is sent to the governor and then an entry where it is "Assigned Act".  This assignment as indicated in their glossary denotes a completed and signed bill.  Lacking a better option, added this to the map to indicate a passed and signed bill.
Eric

AL: Add action for executive-signature to action map

---

pupa-scrape.sh

Tiny change to allow for skipping billy usage via `SKIP_BILLY=true` environment variable. We only need the pupa output for a current project, so figured this would be a nice option for users that may not require billy as well.

Add additional environment variable to allow scrape to skip billy usage

---

README.rst

The service name changed in https://github.com/openstates/openstates/commit/a2e0438bedf982d1b42496fe6f1d77180ebb17f0

Updated README examples to reflect new service name

---

openstates/tn/bills.py

Fixes https://github.com/openstates/openstates/issues/1691#issuecomment-346080631.
Tennessee HTML-escapes motions.
This fix is safe even if they fix the issue.

TN: Unescape ampersands in motions

---

openstates/pa/bills.py

Looks like PA updated their HTML structure so made some minor tweaks to xpath to grab roll call counts and avoid the scraper breaking. I also noticed a couple different HTML formats, so "YEAS" and "NAYS" have conditionals. E.g., one of the `lxml` parsed pages looked like this (snippet):
```html
<div style="margin-left:10px;" id="RCVotesSum">                
<div style="float:left;" class="RCVotesHeaders"><span style="color: green;"><span aria-hidden="true" class="icon icon-thumbs-up"></span></span> <span style="color: black;">YEAS</span></div><div style="float:left; text-align:right; padding-right:5px;" class="RCVotesTotals">143</div><br>
<div style="float:left;" class="RCVotesHeaders"><span style="color: red;"><span aria-hidden="true" class="icon icon-thumbs-up-2"></span></span> <span …
```

Update xpath for roll call in PA to accommodate recent html changes; fixes #1968

---

openstates/sc/bills.py

Patches scraper by preventing the SC server from sending chunked encoding (thanks for the heads up @showerst) via adjusting some `http.client.HTTPConnection` properties. Also remove bypassing of `indexcode=1130` as the HTTP workaround seems to allow that page to load.
I was originally experiencing the error when requesting http://www.scstatehouse.gov/subjectsearch.php?AORB=B&session=122&indexcode=1120. Both `1120` and `1130` are working for me now. Thanks!

Patch SC scraper; fixes #1948

---

openstates/vt/people.py

Fixes #1985.  See comment there for more info.
There's a small risk that Vermont might delete the "wrong" duplicate record sometime, resulting, together with this patch, in there being no Mattos record at all.

VT: Skip duplicate legi record - Christopher Mattos

---

openstates/mo/__init__.py
openstates/mo/bills.py
openstates/mo/committees.py

I also had to deactivate the MO vote scraper for now. It crashes with the error message that it didn't yield any vote objects (which is not surprising given that we're in the bill prefiling phase for 2018)

MO: fixed bill subject scraper and Senate committee scraper - everything should be working now

---

docker-compose.yml

I kept running into the following error when running `docker-compose run --rm ca-download`:
```
inflating: pubinfo_2017/LAW_SECTION_TBL_38203.lob
inflating: pubinfo_2017/LAW_SECTION_TBL_89370.lob
inflating: pubinfo_2017/LAW_SECTION_TBL_120559.lob
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/openstates/openstates/openstates/ca/download.py", line 361, in <module>
get_current_year(contents)
File "/opt/openstates/openstates/openstates/ca/download.py", line 354, in get_current_year
load(dirname)
File "/opt/openstates/openstates/openstates/ca/download.py", line 197, in load
load_bill_versions(connection)
File …
```

Patch California download service

---

openstates/wa/people.py

Fixes #1986.
It might make sense to log the cases where these content details are blank, but I'd guess not.
It might make sense to put an empty-check in add_content_detail, log and skip empties there.

WA: fix leg val errs: skip empty contact details

---

openstates/de/bills.py

Two amendments have a blank status, which was blowing up the scrape.  
No issue yet from bobsled.
Update: fixes #2007

DE: hack for bills with blank status

---

openstates/me/actions.py

State: ME
Add alternate wording for veto override action classifier. See LD 949 ME 127

ME: add alternate wording for veto override action.

---

openstates/id/bills.py

ID was missing one classifier for bill introductions.

ID: properly classify introductions

---

openstates/md/bills.py

State: MD
We were missing classifiers for withdrawals, and veto overrides. I couldn't find a recent veto override that failed, so didn't add that case.

MD: Add misc action classifiers

---

openstates/hi/bills.py
openstates/hi/committees.py
openstates/hi/events.py
openstates/hi/people.py
openstates/hi/utils.py

The state's html element ids all dropped the "ctl00_" prefix.
Fixes #2018, at least in part.

HI: fix html element ids in xpaths

---

openstates/nd/__init__.py

A year early, it's breaking the scrape.  No bobcat issue yet.

ND: Ignore 2019-2020 session

---

openstates/ms/people.py

MS published his party.  No bobsled issue yet; it just failed last night for the first time.
Fixes #2037.

MS: Remove party special-casing for Shane Barnett

---

openstates/sd/__init__.py

SD just changed their nav a little, otherwise bill scraping still works.
Add the current session to get_session_list, and add 2018 metadata.

SD: Add current session to get_session_list()

---

openstates/oh/bills.py

The Ohio legislator ids are scraped as strings, but appear in roll calls as ints.  This patch converts the scraped strings to ints as they are retrieved.
Fixes #2036.

OH: convert legi keys to ints when retrieving for bill scrape.

---

billy_metadata/md.py

Add 2018 to billy session list.  
This refixes #2006, which is already closed.

MD: fix billy_metadata for 2018

---

openstates/mi/committees.py

This fixes a problem mentioned in a comment on #2045 (but not the original problem).
The MI Senate committee list has been moved from a separate page to a dropdown on the main Senate page with the same structure.  Just changing the url was all that was required.

MI: fix senate committee scraping.

---

billy_metadata/nh.py
openstates/nh/__init__.py
openstates/nh/bills.py

Fixes #2073.
This also band-aids a problem where a "bill of address" (similar to impeachment) has no good classification, by just classifying it as a "bill".  An OCD issue is submitted to add a good classification: see https://github.com/opencivicdata/python-opencivicdata/issues/115.

NH: add 2018 session; classify "bill of address" as "bill"

---

billy_metadata/id.py
openstates/id/__init__.py

This patch so far just adds the session.
A partial fix to #2052, but see Jan 12 comment.
There's a second issue pending: the state's legislative subject index page http://legislature.idaho.gov/sessioninfo/2018/legislation/topicind is missing, breaking the scrape.  I've contacted the webmaster and will monitor.

ID: add 2018 session. (READY to merge)

---

openstates/mn/people.py

Fixes #2081.
This kludge ignores any Senator named Dan Schoen.
Dan Schoen resigned in November, but this is reflected in only one of the two source documents we use, breaking the scrape.  A special election in February will probably result in this being corrected at the state website, so I didn't bother them.
Present in http://www.senate.mn/members/member_list_ascii.php?ls=
but removed from http://www.senate.mn/members/index.php

MN: ignore Dan Schoen

---

openstates/ut/committees.py

@jamesturk, I mimicked your fix for Maine the other day; is `legislature` the proper setting in Pupa for these committees, to replace `joint` in Billy?

UT: Fix joint committee chamber classification

---

billy_metadata/ok.py
openstates/ok/__init__.py
openstates/ok/bills.py

Continuing from https://github.com/openstates/openstates/pull/2012, maintains attribution for @estaub's commits.
@jamesturk, can you sanity-check this? Runs successfully for me locally, but I don't know for sure that it won't dup or confuse anything in the database. I _think_ we're good, though ;)

OK: Update session metadata for 2018

---

openstates/id/bills.py

ID changed their bill page markup, so version and documents weren't getting scraped.

ID: Fix broken version and document links

---

openstates/mt/bills.py

There are dup actions in some bills. Perhaps these are accidents, but they look like they _may_ be legitimately different actions, just with the same info. No other clear way to de-duplicate, and Pupa will choke on-`--import` otherwise.
Eg of problematic action lists:
- http://laws.leg.mt.gov/legprd/LAW0203W$BSRV.ActionQuery?P_SESS=20171&P_BLTP_BILL_TYP_CD=&P_BILL_NO=&P_BILL_DFT_NO=LC0267&P_CHPT_NO=&Z_ACTION=Find&P_SBJT_SBJ_CD=&P_ENTY_ID_SEQ=
- http://laws.leg.mt.gov/legprd/LAW0203W$BSRV.ActionQuery?P_SESS=20171&P_BLTP_BILL_TYP_CD=&P_BILL_NO=&P_BILL_DFT_NO=LC0400&P_CHPT_NO=&Z_ACTION=Find&P_SBJT_SBJ_CD=&P_ENTY_ID_SEQ=
Error: http://bobsled.openstates.org/run-MT-2018-01-21.html

MT: De-duplicate actions by adding an extra Pupa ID

---

openstates/ct/bills.py

Addresses #2105 
Convert byte strings back to strings by decoding utf-8
Alternatively: skip encoding `name` at [L337](https://github.com/openstates/openstates/blob/5edbb75a5f99237f4589f0c5fe807878b7a6859b/openstates/ct/bills.py#L337)

CT: Decode sponsor names in Bills

---

billy_metadata/ct.py
openstates/ct/__init__.py

Fixes #2063.
CT blows up differently from other states from lack of bills.
Check the third (`sess_year`) column in ftp://ftp.cga.ct.gov/pub/data/bill_info.csv; when it's 2018, this will be good to go.
I'll monitor.

CT: add 2018 session (HOLD for bills)

---

billy_metadata/ar.py
openstates/ar/__init__.py
openstates/ar/bills.py
openstates/ar/committees.py
openstates/ar/common.py
openstates/ar/people.py

Currently waiting for any `2018F` bills to show up in this CSV: ftp://www.arkleg.state.ar.us/dfadooas/LegislativeMeasures.txt
The pre-files are up on the website, but not in their CSV yet. The session begins in mid-Feb, so should be soon.
Deprecates https://github.com/openstates/openstates/pull/2069

AR: Add 2018 fiscal session, and clean up session slug handling

---

billy_metadata/la.py
openstates/la/__init__.py
openstates/la/bills.py

@jamesturk: requires deployment of special-session-pinned task definition: https://github.com/openstates/task-definitions/commit/2f87e3dff7f61075b2fc5ad20c04762be8856943
I tested locally for both the (March's) 2018 regular session and (February's) 2018 special session, and everything scraped well.
cc https://github.com/openstates/openstates/issues/2139

LA: Add 2018 special session, and handle single-bill sessions

---

openstates/ny/people.py

Also, fix a bug which caused members without emails to be assigned the previously-processed email address.

Fix NY Assembly member missing emails.

---

openstates/mo/people.py

The previous XPath was too picky and got thrown off by a minor change in table structure.

Fix the MO State House email scraper. 

---

openstates/oh/__init__.py

Adding the current session dynamically and removing manually added current session. This fix is for Ohio scraper.
fixes #2159

fix for issue 2159

---

openstates/ok/people.py

Emails are no longer on legislator pages for reps in the lower chamber, but can be found on the contact form.

Fix missing email addresses for OK state house.

---

openstates/fl/__init__.py
openstates/fl/people.py

Note that if you take this PR you may also need to disable whatever is currently overriding the scraper to return some email addresses from the API (ex: FLL000150).

Add code to load FL house emails from their PDF directory.

---

openstates/nv/bills.py

Nevada has the BDR in the title, but it's helpful to have it available as a structured field. This patch doesn't remove it from the title.

NV: Add Bill Draft Request number to extras field

---

openstates/mt/people.py

The code was finding phone numbers and emails and then throwing them away.

Fix MT legislator scraper.

---

openstates/hi/bills.py

resolves #2237
In two cases actor was receiving ```s```(lower case) instead of ```s```(upper case).

HI: Bills, actor dictionary made case insensitive 

---

openstates/la/people.py

resolves #2238
Email, phone is currently not available for Nicholas Muscarello(new representative of LA). Scraper was already skipping empty phone numbers, I have skipped empty emails too.
I think Website will update this info in the coming future, but I think we should get the scraper running anyway.

LA: People, Empty email skipped

---

openstates/de/actions.py
openstates/de/bills.py

Significant enough that I'd love a second pair of eyes. Tweaks and corrections include:
- Now scrapes amended bills. These bills get renamed on the state website, eg from `SB 1` to `SB 1 w/ SA 1`, but are definitively the same bill. Previously, once a bill was successfully amended, we were no longer scraping it at all, leaving stale information in the Open States database.
- Makes the logging much more verbose, to help with development in the future for this confusing state. This is particularly handy since many of the `INFO`-logged requests are `POST`s, and the URL doesn't tell much about what's actually being queried, or indicate progress with the scrape.
- Fixes cosponsor XPath; previously we were scraping extra primary sponsors _also_ as cosponsors
- Eliminate the ability to scrape a …

DE: Prevent duplicates, incorporate amendments, correct cosponsors; closes #2204

---

openstates/md/bills.py
test.txt

resolves #2244
Motion text on http://mgaleg.maryland.gov/2018RS/votes/Senate/1145.pdf, is poorly formatted(non- uniform with previous votes) plus the text itself is not very standard, I have added a text in motion text matching dictionary to fetch this one.

MD: Votes, New keyword added for matching Motion Text

---

openstates/ks/bills.py

Fixes #2223.  The vote header line changed; it now sometimes/rarely has an anchor tag in it,
surrounding an amendment author's name.

KS: fix vote scraper, broken by site change

---

openstates/ok/people.py

resolves  #2249
Oklahoma's thirtieth state senate district is currently vacant. I think scraper should run anyway, hence I made fix to continue running it.

OK: People scraper fixed to continue, even if a district seat is vacant

---

openstates/md/bills.py

resolves #2248
New keyword('committee') added to the motion_text matching dictionary
Exceptions:
1. For SB 747, No motion is given link: http://mgaleg.maryland.gov/2018RS/votes/Senate/0591.pdf
2. For SB 1260, Motion is poorly formatted.

MD: New keyword added to motion text, 2 exceptions handled

---

openstates/ok/actions.py

Via http://guides.ou.edu/OklahomaLegislativeHistory -- engrossed in OK denotes passed chamber.

OK: Identify chamber passage via engrossment

---

openstates/ky/bills.py

in KY, we can correctly classify the chamber for passage actions if we count the number of votes.

KY: identify chamber for passed chamber actions

---

openstates/ca/bills.py

CA: We were just linking to the most recent version of the bill text, but it's possible to permalink into prior versions' PDFs. This patch adds those PDF links to the scraper.
I haven't found a way to permalink to the HTML of a previous version (the version switcher on CA's site performs a POST request, and trying to re-use the url arguments from the PDF download url doesn't work.)

CA: Add versions other than most recent

---

openstates/ma/actions.py

It seems appropriate to add 'referral-committee' to the any rule that has to do with referring to committees. I've also noticed a large chunk of actions that go unclassified. Should new categories be added for larger coverage? Some example are:
Placed on file
Senate concurred
Accompanied a new draft (and several others starting with 'Accompanied')
Hearing scheduled
Reprinted as amended
Committee of conference appointed
Emergency preamble adopted
That's the majority of them. What would you think about either assigning categories to these, and creating new categories where needed? I'd be happy to help of you want to expand on this.

MA: Updated committee rule

---

pupa2billy/bills.py

Resolves scraper run failures due to became-law action. I'll leave this PR in all day in case anyone objects, and if not merge it around COB.

pupa2billy: recognize became-law pupa bill action classification

---

openstates/ca/bills.py

Should resolve http://bobsled.openstates.org/run-CA-2018-05-11.html

CA: fix adding a datetime to a bill_version breaking database import

---

openstates/__init__.py

Fixes #2285, assuming we don't want to validate SSL certs.

Quell InsecureRequestWarning log messages.

---

openstates/ak/bills.py

I believe Alaska's been failing since mid-April because the vote `pupa_id` is just the journal page URL, and a page can have more than one vote on it.  I first tried just appending the motion, but it sometimes overflows the 300-character limit.  So this just keeps a vote index of the votes on a page, and appends that to the `pupa_id`.
Fixes #2254.

AK: Fix DuplicateItemError: disambiguate pupa_id

---

openstates/nc/people.py

The HTML structure changed, such that the scrape was failing because of "no people".  No issue is filed yet.

NC - fix people scraping (site HTML changed)

---

openstates/or/__init__.py

The scrape will continue to fail until results from the May 21st session are posted.  It's so close I didn't bother with a temporary ignore.

OR - add special session

---

openstates/mo/__init__.py

The MO Senate vote scraper was turned off "temporarily" in December, and no one turned it on again.  See #1992.
I've lightly verified that it seems to work.

MO - re-enable Senate vote scraper

---

openstates/oh/people.py

resolves  #2258
In the new web page, committee info of the senator is not given, although long bio can be extracted, whereas previously short bio and committee info was available, hence there was a separate function, extracting those data.
I have not extracted long bio in this one, as it seemed too long to me in comparison to the previously available bio. @jamesturk if you think it should be extracted do comment below.

OH People: Senator scraper updated as per the new page

---

openstates/in/__init__.py
openstates/nh/people.py

There's no issue posted for this, but see comment https://github.com/openstates/openstates/issues/2220#issuecomment-386479706 .  
This problem is not visible in the openstates db because of another problem that I can't fix; I can see it because I've started scraping into my own DB, just so I can have access to NH data, and also perhaps because it's a new DB (so the "former" legislators aren't already in it as legacy data).
This will need to be undone when/if they start validly marking legislators as "Former".

NH: Include supposedly "former" members in legislature.

---

openstates/mo/bills.py

Due to a bug w/ how the scraper handled special sessions, MO special session bills were being output with the regular session's "identifier". This resolves that issue.

MO: fix session assignment for special session bills

---

openstates/mo/__init__.py

The scraper is believed to be working correctly, but pupa errors out if a vote scraper gets no votes, and a special session just started that truly has no votes.

MO - temporarily re-disable Senate vote scraper till special session has votes

---

openstates/il/__init__.py

While I'm sure this is nominally correct, I can't guess at the side-effects when merged with a database containing the incorrect ID.

IL - fix jurisdiction OCD ID: legislature => government

---

openstates/ct/bills.py

resolves #1803
The error was persisting due to the fact that, the condition for recognizing the assembly vote was not correct, hence all votes were getting recognized as Senate votes, hence no assembly vote was retrieved and bad senate votes were also getting retrieved.

CT: Assembly votes retrieved and senate votes fixed

---

Dockerfile-alpine
pupa-scrape.sh

Looks like the alpine docker image got out of sync with the default image. This patch bumps the base alpine version and adds a few missing dependencies. After the update, I'm able to use the alpine image to run scrapes again.
Also, it looks like the alpine image we're publishing on dockerhub is actually the ubuntu image.
Also, wdyt about moving towards using alpine by default? The ubuntu image is big.

Update alpine dockerfile.

---

openstates/il/bills.py

The IL vote parser crashes on votes with multiple vote statuses. We
probably should crash on multiple inconsistent statuses, but not when
there are duplicate statuses with the same value. This patch allows
consistent duplicate status to be processed.
For an example vote with multiple identical statuses, see
http://ilga.gov/legislation/votehistory/100/house/10000HB5231sam003_05312018_078001C.pdf.

IL: Allow consistent duplicate bill vote status.

---

openstates/ny/bills.py
openstates/ny/models.py

This is my first iteration to fix #1960. This sort of reverts [c29e88790b3f462c](https://github.com/openstates/openstates/commit/c29e88790b3f462c854539de9bc7144928ed2517#diff-c0b833d744907b858a610c3983ecd2c8L58) for `models.py`. I've tested each part of the new scraper on the interpreter, but I'm unsure about whether we need to scrape committee votes as well. As of now, this just scrapes individual floor votes.

NY: Fix Assembly vote scraping

---

openstates/nd/people.py

Looks like the markup for district, party, and chamber have changed.

ND: Fix people details selectors.

---

openstates/ny/models.py

Saw the NY scraper failing in bobsled, this should fix it plus it earlier it wasn't scraping motion, motion scraped as well.

NY vote:  pupa_id added, motion scraped

---

openstates/wy/people.py

I was looking at #2354 and noticed that WY doesn't use the same party labels as other states. Now it will.

WY: Standardize parties.

---

openstates/wy/people.py

WY posts use stringified integers as district labels: "1", "2", "3",
etc. But WY people use zero-padded integers with the chamber initial:
"H01", "S02", etc. This patch strips the chamber initial and leading
zeroes from the district label for WY people so that we can import them
via pupa.

WY: Fix person district labels.

---

openstates/ia/bills.py

IA changed their website in a way that broke action scraping, this restores it.
If you're running a production copy of the Openstates database for IA, you may need to manually delete any copies of the IA action "video", as it's an errant link that got scraped as an action due to how they changed the markup.
@jmcarp @estaub -- tagging you in case you run your own OS DB.

IA: fix bill action table xpath

---

README.rst
dbinit.sh
docker-compose.yml

Docs for importing data into postgres have been pending for a while. Here's a start: this patch adds postgres with postgis to the docker-compose config and adds the initial database migration. When I try to import data, though, pupa chokes because things like parties don't exist in the database:
```
cannot resolve pseudo id to Organization: ~{"classification": "party", "name": "Democratic"}
```
Am I missing a step for loading organizations?

Add postgres with postgis to docker-compose.

---

openstates/pa/__init__.py

Resolves #2388 hopefully in a more scaleable way.
@jamesturk I think we talked about this (mass ignoring old PA sessions as they add backdata) in the past at some point, just flagging that i'm doing it.

PA: Mass ignore sessions before 2000

---

openstates/nv/__init__.py

Or should we disable the 2019 session until it starts?

NV: Fix session scraping and add 2019 session.

---

openstates/sd/people.py

SD has removed email addresses from detail pages, fetch them from the Contact Legislators page instead.  Fixes issue 2414.

Fix SD email address scraping

---

openstates/va/bills.py

Currently, we only scrape vote details for votes prefixed with "VOTE".
This patch scrapes vote details for all votes with detail urls.
Hopefully resolves #2144. cc @estaub

VA: Scrape senate roll calls.

---

openstates/mt/__init__.py

* Skip 2019 session until it starts
* Skip 2017 special session, which throws a 404 on listing bills at the
moment: https://leg.mt.gov/bills/specsess/1117/BillHtml/

MT: Skip future and broken sessions.

---

openstates/dc/people.py

We previously added the office address scraped for DC legislators as the address of their district office, but these offices are really their capitol offices. We also scraped but didn't add their fax information as a contact detail. We now add their fax information correctly, and interpret all information as being about their capitol office.

Update contact info scraping for DC legislators

---

openstates/de/people.py

The text on a DE legislator's page that indicates their address is now "Legislative Office" instead of "Legislative Address". For example, see: https://legis.delaware.gov/LegislatorDetail?personId=133.

Adjust text for scraping DE legislator addresses

---

openstates/pr/people.py

Fixes #1611. This is a pretty complete overhaul of the people scraper for Puerto Rico, as both the House and Senate pages changed. We now have to scrape the page for each individual legislator to get the information we want, as well as occasionally getting information from the main legislators page as some information is easier to scrape from that page.

Update Puerto Rico people scrapers

---

openstates/md/people.py

Maryland has fax numbers for most legislators included in their contact info, but we were not scraping it, and instead leaving it as part of the address. We will now scrape the faxes, making the address fields cleaner in the process.

MD: Parse fax numbers

---

openstates/md/people.py

I accidentially forgot to use an elif in #2460, so when a phone number was included in the address field, it would be parsed and included in the parsed address as well. Clean it up by only adding it to the parsed address if it's not a fax line or a phone line.

MD: Don't include phone numbers in address

---

openstates/tn/people.py

Tennessee publishes fax numbers for most legislators. This change updates the scraper to recognize the fax numbers and add them as contact details.

TN: Scrape fax numbers

---

billy_metadata/tx.py
openstates/tx/__init__.py
openstates/tx/bills.py
openstates/tx/committees.py
openstates/tx/events.py
openstates/tx/people.py
openstates/tx/votes.py
scripts/newsblogs/urls/tx.txt

Texas has a new domain! Good, because SSL certs were a bit off on the old domain!
The old domains for the most part serve redirects to the new domains, except for some of the House member URLs whose SSL certs on old domain are too messed up for the redirect to work.

*.state.tx.us -> *.texas.gov 

---

openstates/ks/bills.py

I was going to fix the `KeyError` in the `except` block here, but taking a closer look, I'm not sure why we're ignoring scrape errors in the first place. I'm running the scraper now to see if this introduces any new problems.

KS: Fail on bill scrape errors.

---

openstates/pr/__init__.py

Fixes #2502. We previously did not account for At-Large representatives when setting up the upper and lower house organizations, which caused scraping to error out. Consistent with the Open Civic Data guidelines, the `division_id` for these At-Large posts is simply the lower or upper house itself.

PR: Add post for At-Large representatives

---

openstates/il/bills.py

Yield rather than return from `scrape_bill` method to avoid returning
`None` and attempting to iterate over it. See
http://bobsled.openstates.org/run-IL-2018-09-09.html.

IL: Refactor yields in bill scraper.

---

openstates/pr/people.py

Fixes #2512. Since we do not currently have the "Independiente" party in the database, pupa cannot convert this into an actual membership to an organization. Being an independent is a universal construct, so we can just convert it to English to prevent this error.

PR: Convert Independent party membership to English

---

dbinit.sh
openstates/pr/__init__.py

It looks like the at-large divisions we added for PR in #2507 don't exist in https://github.com/opencivicdata/ocd-division-ids. This patch replaces them with divisions that exist in our database. I also added some PR parties to `dbinit.sh` so that I can run the import locally.
@showerst @csnardi

Pr add parties

---

openstates/pr/bills.py

Fixes #2518. By the time the date is in `parse_action`, it is in datetime form, so we need to make sure that we compare and modify it in datetime form.

PR: Update fix for PS0623 year error

---

openstates/pr/people.py

Some senators have their names in all-caps. To avoid this, normalize names into title case to make them easier to read.

PR: Convert senator names into title case

---

dbinit.sh

`sh` seems to split up some strings, so "Partido Independentista Puertorriqueño" wouldn't be added to the database as one party, it would be added as several different fragments. Switching to `bash` seems to fix this.

Use /bin/bash instead of /bin/sh for dbinit

---

openstates/pr/people.py

A member of the lower chamber (Albelo) recently became an independent, and they seem to have removed the span with a class of `partyBio` for him. Make the scraper account for this oddity.

PR: Account for independent member of lower chamber

---

billy_metadata/in.py
openstates/in/committees.py
openstates/in/people.py
openstates/in/utils.py

This includes many fixes. First, don't limit the session name to 5 characters as this cuts off the end of `2018ss1`. Secondly, `senate` and `house` apparently need to be completely lowercase for the API URLs. Thirdly, adjust the read timeout to start at 8 seconds, as 2 seconds seems to be too low for many pages.
Finally, add `2018ss1` as an acceptable session for the 2017-2018 term, and fix a typo in the legislative term to be `2017-2018` instead of `2017-2017`. (Hopefully that typo fix won't break anything? Not sure if anything relies on that staying the same.)
Fixes #2228.

IN: Fix people and committee scrapers

---

Dockerfile-alpine

Fixes NJ scrape with alpine image.

Don't drop glib; required for mdbtools.

---

openstates/oh/bills.py

If we go this route, I think we'll want to reimport existing OH votes to avoid duplicates.
[Fixes #2327]

OH: Concatenate bill and vote ids to avoid collisions.

---

dbinit.sh
openstates/ca/download.sh
openstates/dc/__init__.py
openstates/dc/bills.py
scripts/backup
scripts/backup-ocd
scripts/build-thumbdrive.sh

After switching to the alpine docker image, bash isn't available unless
we install it. We can switch to sh unless we need bash-specific
features.

Switch bash scripts to sh.

---

.travis.yml
openstates/ia/bills.py

The bill history link seems to use js now and doesn't set the href
attribute; build the url from the bill and session ids instead.

IA: Build history url.

---

openstates/ga/__init__.py
openstates/ga/util.py

This doesn't actually work so far--looks like the GA API doesn't know about the new session yet. I'll check on this in a few days once the special starts.

GA: Add 2018 special session.

---

Dockerfile

This reorders the Dockerfile to improve cache usage and changes the ENTRYPOINT command so that it functions outside of docker-compose.

Dockerfile - ENTRYPOINT syntax change + reorder Dockerfile

---

openstates/nm/__init__.py

NOTE: This scrape won't work even with 2019 ignored because FTP files are missing, but at least it's ready for 2019.

NM: Ignore 2019 session until filing

---

billy_metadata/ky.py
openstates/ky/__init__.py

I've also added 2019, but not by default. The prefiles can be scraped by:
```
pupa update ky bills --scrape session='2019RS' prefile=True
```

KY: Add 2018 Dec Special Session

---

openstates/ca/models.py

In investigating a way to resolve #2672 I ran into the following error:
```
/opt/openstates/venv-pupa/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py:2745: SAWarning: relationship 'CAVoteDetail.summary' will copy column bill_summary_vote_tbl.bill_id to column bill_detail_vote_tbl.bill_id, which conflicts with relationship(s): 'CAVoteDetail.bill' (copies bill_tbl.bill_id to bill_detail_vote_tbl.bill_id). Consider applying viewonly=True to read-only relationships, or provide a primaryjoin condition marking writable columns with the foreign() annotation.
```
when running `docker-compose run --rm scrape ca bills`
I don't know for sure if that's why CA is not running in your system, but once I made this change, I was able to successful run that command and see output that seemed to …

CA: Resolve sqlalchemy error on CAVoteDetail relationships

---

README.rst
openstates/or/apiclient.py

I emailed them for an API key but they said it does not require auth. Ran the scraper without it and it works great, but data has not been updated for 2019 yet.

Updated docs regarding oregon API auth

---

openstates/oh/bills.py

My bill number cleanup regex in Ohio had an error that would've split double-digit numbered bills wrong. I noticed it in testing and caught it before any went live.

OH regex fix

---

openstates/il/people.py

This bumps the term to current (101).
Tidies up the addresses we're scraping to have less extraneous data.

Illinois people scraper updates

---

openstates/ct/people.py

A couple malformed legislator URLs from the source document are causing the scraper to crash.

CT people scraper: handle malformed legislator URLs

---

openstates/fl/bills.py

Fixes http://bobsled.openstates.org/run-FL-2019-02-03.html.

FL: More flexible date xpath.

---

openstates/ia/votes.py

Fixes http://bobsled.openstates.org/run-IA-2019-02-03.html, although the scraper will still crash because there aren't any votes yet.

IA: Add current session to vote site ids.

---

openstates/wi/bills.py

Handle votes with common name and date, like
http://docs.legis.wisconsin.gov/2019/related/votes/assembly/av0004 and
http://docs.legis.wisconsin.gov/2019/related/votes/assembly/av0005.

WI: Set unique vote id.

---

openstates/oh/bills.py

By providing a legislation type filter, OH's website will return bills again.

OH: Fix empty listing page

---

openstates/il/bills.py
openstates/ky/people.py

This hacks the source url for committees, used in pseudo-id resolution, to set the session back from 101 to 100, to match the urls in the openstates/people committees.  This is intended to provide time to consider support for committees when not under the gun.
Issue: https://github.com/openstates/openstates/issues/2821 .

[IL] Temporary fix for committee resolution

---

requirements.txt

As I was dealing with a namespace issue with Cali's MySQL, I noticed that we don't protect against major-version bumps in our `requirements.txt`, which could contribute to those sorts of issues.
If this is intended behavior, then absolutely close this PR without merging, though; I could imagine a world where we always want the newest version of a Python library, and any breaking change will just be obvious to us (via a break in the production Bobsled logs), so prevention of a major-version bump is undesirable.

Add major-version pinning to the Python requirements

---

docker-compose.yml

Running the CA download and import using MySQL 8 instead of 5 is working smoothly. I'm not very familiar with the MySQL community, though; is using 5.7 still standard/best-practice?

CA: Upgrade MySQL container from version 5 to 8

---

openstates/wy/bills.py

WY: Truncate microseconds in action timestamps.

---

openstates/ut/bills.py

UT changed site structure slightly causing us to silently skip the first voter in of each type (y/n/a), and get the counts off by one.

UT: Fix votes skipping first member in each column

---

openstates/mi/bills.py

Due to a site change we were registering MI versions with the absolute URL twice.

MI: Fix broken version urls

---

requirements.txt

Not sure what happened here, but apparently `python-dateutil` isn't in the image anymore. Maybe some upstream dependency changed its dependencies. Anyway, best to list in the requirements explicitly.

Restore dateutil dependency.

---

openstates/az/bills.py

Fixes #2917. Not sure if there's something better to do with actions that don't have report dates, but this at least makes the scraper stop failing.

AZ: Skip bill actions without report date.

---

openstates/tn/bills.py

Fixes #2916. Not sure why, but HB1064 shows up twice in the bills list right now.

TN: Handle duplicate bill links.

---

openstates/ky/bills.py

We were missing the bolded actions on the bill page action listing due to a narrow xpath.

KY: Included bolded actions from list

---

docker-compose.yml

Ugh, actually @showerst, the environment we should've been reproducing in Docker Compose is MariaDB. Alpine apparently switched from MySQL to MariaDB in their 3.2 release, and our Dockerfile uses MariaDB packages when installing (and then running in production).

Switch Docker Compose to MariaDB container, to mimic Alpine server used in production

---

openstates/ks/bills.py
openstates/ks/ksapi.py

Resolves #2921 this is another rate-limiting issue. This patch will get the scraper finishing by skipping some votes, we may need to drop the RPM as well here.

KS: Deal with new rate limit error, and add one action type

---

openstates/mi/bills.py

Due to a change in MI's html, we were picking up district links and adding them as bill sponsors, like "58".

MI: Stop adding district numbers as sponsors

---

Dockerfile

`MAINTAINER` instruction is deprecated [according to Docker docs](https://docs.docker.com/engine/reference/builder/#maintainer), so updated `Dockerfile` using suggestion in docs.
Tested rebuilding the image locally via `docker build -t openstates/test-build:1.0 .`:
```
REPOSITORY                                           TAG                 IMAGE ID            CREATED              SIZE
openstates/test-build                                1.0                 eb981864cd8f        About a minute ago   830MB
```

Use LABEL instead of deprecated MAINTAINER instruction

---

openstates/al/__init__.py

Resolves #2954
Thanks to @jessemortenson for flagging; the state's list had a leading space typo.
Note that we'd usually strip those in the get_session_list function, but in this case we need the exact string to submit a form on the website later to get a session cookie.

Add space to scraped 2019 al session.

---

openstates/ca/actions.py

State: CA
In https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB1586 and other bills, we were mis-classifying "From committee: Without further action pursuant to Joint Rule 62(a)." as committee passage.
Change the regex to exclude matches for that.

CA: Fix overly broad action classifier

---

openstates/wv/__init__.py

Add 2020 to list of ignored scrape sessions for WV (at least while it has no data)

Patches: WV 2020

---

openstates/al/bills.py

I found a handful of bills in AL where there is a space (nbsp) in a table cell that the scraper code was checking to look for amendments (which get turned into bill versions). This is an error or typo on the AL website side, which results in broken bill versions, like [HB 70](https://openstates.org/graphql?operationName=null&query=%7B%0A%20%20bill(id%3A%20%22ocd-bill%2Fa4e55a92-f6d2-4b78-bcc7-d52a6b260786%22)%20%7B%0A%0A%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20title%2C%0A%20%20%20%20identifier%0A%20%20%20%20legislativeSession%20%7B%0A%20%20%20%20%20%20identifier%0A%20%20%20%20%7D%0A%20%20%20%20sources%20%7B%0A%20%20%20%20%20%20url%0A%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20versions%20%7B%0A%20%20%20%20%20%20%20%20%20%20note%0A%20%20%20%20%20%20%20%20%20%20date%2C%0A%20%2 …

AL: Fix bill version is an amendment with empty name/filename

---

openstates/nj/utils.py

New Jersey posted their 2018-2019 mdb file unzipped in their FTP repository, where it always used to be zipped.  This PR downloads the mdb for 2018-2019 and later.
There may be downstream problems that this fix will reveal.

NJ 2904: ftp download unzipped mdb file

---

openstates/il/bills.py

Fixes #2949 (I think)
The IL scraper goes to the "Full Text" link on the bill page to find bill versions ([HB 2698 example](http://ilga.gov/legislation/fulltext.asp?DocName=&SessionId=108&GA=101&DocTypeId=HB&DocNum=2698&GAID=15&LegID=118910&SpecSess=&Session=)). For bills that do *not* have HTML bill text available, the scraper attempts to locate PDF urls for each bill version. However, there is a link on the "Full Text" page labeled "PDF" that does not go to a unique bill version. Instead, it goes to a PDF file that appears to be an alias/duplicate of the most recent bill version (LV = Last Version? Latest Version?). For HB 2968, it is [10100HB2698lv.pdf](http://ilga.gov/legislation/101/HB/PDF/10100HB2698lv.pdf). Since the alias is actually a duplicate of an actual bill version, as the …

IL: fix duplicate 'lv' versions causing "Duplicate Entry" errors

---

openstates/mi/bills.py

I investigated #3029 and found problems. Hopefully this is an easy fix.
MI scrape was halting at an error NoneType object is not subscriptable when parse_roll_call() returned None. Check for None before calling the vote yielding logic. Also fixed the guard in parse_roll_call() so that it can find the text its looking for even when there are spaces/newlines/span tags between the words (which was causing None to be returned).

MI: avoid error when vote roll call data is not as expected

---

openstates/mi/bills.py

404 on request for a roll call document (vote details) would cause whole scrape to fail
Should fix additional issue identified on #3029

MI: Handle HTTP error when fetching roll call document

---

Dockerfile

image size went from 730MB to 1.1GB, not ideal, but since GDAL is broken (again) in Alpine, looks like this will be needed
(branch name is incorrect, this is Debian based)

replace base image with python 3.7-slim, based on Debian stable #3034

---

openstates/wi/bills.py

And scrape fiscal notes as documents, under their new name.

WI: read alternate vote motion HTML

---

openstates/ny/bills.py

By default NY HTML urls weren't pulling the bill's text, you had to click a button. This changes the URLs to include the billtext.

NY: Make text url load full billtext

---

openstates/ia/bills.py

Created a special case for IA Marked Up bill versions. The correct url for these bill versions was hidden within the iframe.
Fixes issue #3068

Added a special case for IA Marked Up bill versions

---

openstates/nm/bills.py

Added a special case for Roberto J. Gonzales in NM Bill Scraper within the sponsor section. Gonzales has moved from the House to the Senate, but was still marked down as a sponsor for several bills.
Related to issue #3080

Nm scrape failing

---

openstates/ut/__init__.py
openstates/ut/bills.py

UT sometimes posts session data without adding an actual link to their sessions index page, but the session IDs always follow a predictable pattern.
In this case they've been prefiling for 2020 for a while, but without linking it up correctly.

UT: Simplify session logic and add 2020 session

---

openstates/ma/bills.py

addresses https://github.com/openstates/openstates/issues/3058
changes:
- specify a list of expected bill types, and check against that. (this was verified against all bills that are coming back from most recent session. only failures were https://malegislature.gov/Bills/191/S2405,AppendixA and other appendix links for S2405. these links are broken anyway, and were already failing.. however https://malegislature.gov/Bills/191/S2405A works, do we want to make an issue for that?)
- non sequitur: sort by bill number when scraping chambers for better usability 
confirmed that this change fixes the import issue for MA/191/SR1

ma: senate resolution handling

---

openstates/ma/bills.py

there was significant trailing whitespace on people names and committees, that would need to be stripped later, and also was preventing people name matching. not sure if this is the best way to handle this.

ma: strip whitespace on persons and committees

---

openstates/hi/bills.py

HI was skipping the first bill in the versions table for every bill with > 1 version, perhaps because of a header row that used to be in the markup. This resolves that.
NOTE: I had another PR for this and closed it, branch issues on my end.

HI: Don't skip first bill version in multi-version bills

---

openstates/va/bills.py

@jamesturk currently the VA scraper is skipping adding actions for votes, which makes our pages not match the source. I restored that (and the committee sub action, which a customer asked us about, so i guess is relevant).
Let me know if you'd rather not have those as actions since they're also getting broken out as votes. I think both are useful, since often people just skim the actions section.

VA: Add action for successful votes, committee subs

---

openstates/hi/__init__.py
openstates/hi/bills.py
openstates/hi/events.py
openstates/hi/utils.py

State: HI
1. Allow the versions table to have a header (it appears on some pages and not on others)
1. Collect document links to witness testimony and committee reports
1. Fix and re-enable the events scraper

HI: Collect additional documents and fix events

---

openstates/in/bills.py

Currently, the API's bill title is used as its title to store in the database. However, this title is not very helpful. For instance, this year's HB 1001 title is:
> A BILL FOR AN ACT concerning education.
Versus the description:
> School accountability.
This changes the stored title to be the bill description and not the API title.
Comments are welcome as to which is the preferred title (I presume as the more descriptive item the description is), and whether or not this will create any problems for already existing bills.

IN: Switch title to bill description

---

openstates/nh/bills.py

I was getting some occasional weirdness from NH where occasionally I'd be served broken versions of legislators.txt -- adding a cachebreaker in the format that they do on the NH legistlative data site fixed it.

NH: Add cachebreaker to legislators file download

---

openstates/in/bills.py

The Indiana bill API makes digests available, so add it as a bill abstract if available.

IN: Add abstract if available

---

openstates/ny/bills.py

Status quo behavior is that each amendment to a bill gets scraped and recorded as a separate bill. Each bill has two versions, the HTML and the PDF version. Issue raised as #3017 
This change uses `basePrintNo` to identify the bill uniquely, and then `printNo` to identify each version of the bill. Results in a versions array that looks like:
```
"versions": [
{
"note": "S6513 HTML",
"links": [
{
"url": "http://assembly.state.ny.us/leg/?sh=printbill&bn=S6513&term=2019&Text=Y",
"media_type": "text/html",
"text": ""
}
],
"date": ""
},
{
"note": "S6513 PDF",
"links": [
{
"url": "http://legislation.nysenate.gov/pdf/bills/2019/S6513",
"media_type": "application/pdf",
"text": ""
}
],
"date": ""
},
{
"note": "S6513A PDF",
"links": [
{
"url": …
```

NY: Scrape amendments to bills as versions on the base bill

---

openstates/co/bills.py

CO: Fixed the if statement where bill history actions are checked to see if they have a date listed.
Related to issue #3167 
@jamesturk

CO Bill Document Actions With No Date Skipped

---

openstates/ny/bills.py

Also fix bug when encountered a previously unknown vote status EL. I could not find any reference material on the web that would explain what "EL" status is for a vote, so I left it as "other".
Improvement to previous code change based on my colleague's [comment](https://github.com/openstates/openstates/pull/3179#issuecomment-592190629) re: fix for #3017
New versions array looks like:
```
"versions": [
{
"note": "S4389",
"links": [
{
"url": "http://assembly.state.ny.us/leg/?sh=printbill&bn=S4389&term=2019&Text=Y",
"media_type": "text/html",
"text": ""
},
{
"url": "http://legislation.nysenate.gov/pdf/bills/2019/S4389",
"media_type": "application/pdf",
"text": ""
}
],
"date": ""
},
{
"note": "S4389A",
"links": [
{
"url": "http://legislation.nysenate.gov/pdf/bills/2019/S4389A",
"media_type": …
```

NY: fix different file types being saved as different versions

---

openstates/il/bills.py

The xpath searching for sponsors in Illinois bills assumes that links to sponsors will only have the class `content`. However, tags after the first sponsor also contain the class `notranslate`. Update the xpath to account for this so we catch each sponsor for a bill.

IL: Adjust sponsor xpath for tags with multiple classes

---

openstates/pa/bills.py

In roll call votes, the bill scraper grabs all the text in the vote div as the member's name. However, the div also contains a Y/N/E/X in a child element to record what the member's vote was. By using only the text of the div itself, we will only capture the member's name and not their vote.

PA: Strip vote from member name in roll call votes

---

openstates/mi/bills.py

The House and Senate journals occasionally have newlines in place of spaces, leading to the phrases "Not Voting" and "In The Chair" not being recognized. Replace these newline characters with spaces so the phrases are recognized correctly.
Also split lines with names on multiple spaces as Rep. O'Malley's name is sometimes recorded in the journal as "O Malley", causing his name to be split across two votes.

MI: Convert newlines in roll call votes to spaces

---

openstates/pa/bills.py

In #3193, I adjusted the way member's names were found for roll call votes. However, `.text` does not actually provide the member's name, since the text comes after the child element. Adjust the code to instead use text that comes after the first child element.

PA: Fix member name for vote

---

openstates/az/bills.py
openstates/az/utils.py

The AZ bill scraper currently marks first readings as occurring in the wrong chamber due to the upper and lower chamber being flipped in `action_chamber_map`. It misses second readings because their dates have milliseconds whereas those for first readings do not. These bugs are fixed in the scraper.
Additionally, the scraper contains old code sorting the bill actions, seemingly from a time when it was important that actions be sorted according to their dates. Since the website should do this itself now, and the code had the side effect of lower-casing action descriptions, remove the sorting code entirely.

AZ: Fixes to bill scraper

---

openstates/ma/bills.py

There's an additional markup style they're using for some bills, that doesn't seem to change 'back' to the standard after a few days.

MA: dont skip bills with alt title markup

---

openstates/ak/bills.py

State: AK
https://www.akleg.gov/basis/Bill/Detail/31?Root=HB204#tab5_4 was breaking the scraper due to removal of the long title. Fall back to the short title in that case, and only fail if there's no title at all.

AK: Fall back to short title if title is removed

---

openstates/ia/votes.py

The journal URL changed slightly, which prevented the scraper from working.

IA: Update URL for vote scraper

---

openstates/ma/bills.py

Due to a markup change in MA, the scraper is picking up a bunch of sponsor names ending in "(whitespace) This sponsor is an original petitioner. (whitespace) *". Strip that out.
Due to a recent attempt to fix titles w/ alternate markup, we were overwriting the title in many cases w/ the bill number. This restores the titles.

MA: Remove junk text from sponsor names, Fix titles

---

openstates/ca/actions.py

The CA parser was marking bills that had died as 'passed committee' due to the actions starting with 'From Committee:' -- this fixes that.
Ex: http://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB700
@schneidy I don't think this conflicts w/ your CA work but let me know if so.

CA: Updates to action parser for joint rule 56

---

openstates/ar/__init__.py

Updated sessions as AR now has a new page that lists what sessions we can search.
Page listing: [https://www.arkleg.state.ar.us/Bills/Search](https://www.arkleg.state.ar.us/Bills/Search)
Should fix issue #3195

AR: Updated Sessions in Init

---

openstates/ca/bills.py

Added in additional long titles by grabbing the title from the status page on the bills' pages.
Should fix issue 1380.

CA: Added in additional long titles

---

openstates/va/bills.py

`zip` drops the last element of the list, since `b` is shorter than `a`. However, `zip_longest` makes the zipped object be as long as `a`. #3227

VA: Fix scraping of last action

---

openstates/va/bills.py

AttributeError's are thrown since the next attribute might be None; ignore these exceptions as well.

VA: Ignore AttributeError when checking next attribute

---

openstates/nh/bills.py

New Hampshire: Sponsor names extra spaces have been removed.
Related to issue #3261

NH: Sponsor names extra spaces have been removed.

---

openstates/hi/bills.py

Hawaii:
Removed '(Introduced by request of another party)' from sponsor names.
Added a function to remove extra periods and spaces from voter names.
Should fix issue #3257

HI Vote and Sponsor Name Issues

---

openstates/wv/bills.py

West Virginia no longer has * showing up before voter names.
Also removed any voter names that had the word "committee" in them.
Related to issue #3263

WV: voter name issue

---

openstates/nv/bills.py

Nevada:
Removed "Assemblyman", "Assemblywoman", "Senator" from sponsor names.
Resolves issue #3262 
I recommend running session 79 after code is merged.

NV: Added code to remove leg position from sponsor name.

---

openstates/ar/__init__.py

Arkansas' Fiscal Session 2020 is starting tomorrow, so moving it to the bottom of the sessions list so that ingestion can begin. (I believe some bills are already filed).

AR: Enable ingestion for Fiscal Session 2020 starting Apr 8

---

openstates/or/bills.py
openstates/or/utils.py

the Oregon site has URL's with whitespace in them that were not being encoded, causing issues for people following the link outside of a browser.
i included a utility function to fix the URL for this specific issue, based off of a [werkzeug util](https://github.com/pallets/werkzeug/blob/51860032cc780fa4a120b4a3c0457a36bbe91715/src/werkzeug/urls.py#L608). don't know if it makes sense to integrate this more generally.. it seems like this is fairly isolated.
i also made a [PR](https://github.com/opencivicdata/pupa/pull/333) to tighten up validation in pupa to catch this.

or: encode whitespace in urls

---

openstates/nc/bills.py

North Carolina:
Voter names had extra "\r" appended to the end of each name.
Rerun sessions: 2017, 2019.

NC: Voter and Sponsor Name Issues

---

openstates/ct/bills.py

Connecticut:
Clean up sponsor names. Current sponsor names can include "Rep", "Sen", and "Dist'.
@jamesturk Once you merge it, can you rerun sessions 207, 2018, and 2019?

CT Sponsor Name Cleanup

---

openstates/vt/bills.py

Vermont was having duplication issues with votes. An identifier field was added to the vote. It is made up of the status date, the motion text, and the vote url.
An additional check was also added to actions to make sure that a json file was actually loaded and that it has data within it.
Should resolve issue #3298

VT Duplicate Error

---

.gitignore
docker-compose.yml

This PR makes the following small changes:
- Update the California download script path in Docker compose.
- Ignore the `.venv/` directory, allowing a virtualenv to be placed within the project root for local testing.
Let me know if there are any issues. Thanks!

Patch Docker Compose CA download

---

scrapers/ar/__init__.py

AR: Added First Extraordinary Session, 1999 to list of ignored sessions. It was previously not found at https://www.arkleg.state.ar.us/Bills/Search

AR: Added First Extraordinary Session, 1999 to list of ignored sessions

---

openstates/mt/bills.py

Montana originally was setting the chamber based on the url. However, this led to the script believing that all bills were in one chamber. The chamber is now based on the bill id which starts with either HB or SB.
This should fix the issue that was brought up in #3299

MT Chamber Issue

---

scrapers/ga/__init__.py

GA Started Legislating in the regular again.

GA: restore 2020 regular as default session

---

scrapers/ak/bills.py
scrapers/co/bills.py
scrapers/vt/bills.py

Add related document format as pdf, strip .pdf from doc names, and add conferees from House and Senate as related docs

AK: edit document links, add conferees

---

scrapers/la/__init__.py
scrapers/la/events.py

This PR enables the LA events scraper. It also adds a small patch to trim leading and trailing whitespace characters surrounding the `date` and `time` combined string as it was previously failing on certain events (e.g., times such as `"10 a.m.  "`). Thanks!

Enable LA events

---

scrapers/oh/bills.py

OH: Added Concur_622 to Vote Motion Dict.
The issue popped up on [HB-168](http://search-prod.lis.state.oh.us/solarapi/v1/general_assembly_133/bills/hb168/votes). Bill info [here](https://www.legislature.ohio.gov/legislation/legislation-status?id=GA133-HB-168).

OH: Added Concur_622 to Vote Motion Dict

---

scrapers/hi/bills.py

The scraper has been missing HI versions recently due to a site markup change. This will put them back.

HI: Restore bill versions after site markup change

---

scrapers/tx/bills.py

i found that TX resolutions did not contain versions, and looks like were also missing fiscal notes, witnesses and analyses.
the issue is that the file paths for resolutions omit the 'R' in the identifier, causing issues when we look up associated files by bill ID. i modified the function used to extract bill id to fix this when we create the lookup mapping.
i also added PDF version links for all documents. let me know if you concerns about that or want me to separate that out to a different PR.

TX: add some missing info for resolutions, add PDF version links for all bill types

---

scrapers/dc/bills.py

Handle attachments not in version type list, URLs that already have a schema, and dedupe between bills and versions.
@schneidy FYI attachments are usually a version OR a document, but not in both places.

DC: new API updates

---

scrapers/oh/bills.py

Trying to fix the most [recent OH error](https://bobsled.openstates.org/run/32301a3420bd4845a5e5696be94c7cc9). Maybe someday this scraper will run to completion lol
[This is the error bill, btw](http://search-prod.lis.state.oh.us/solarapi/v1/general_assembly_133/bills/hb656/)
Attempts to fix #3347

OH: Fix error when API data is empty

---

scrapers/oh/bills.py

instead fallback to 'results' field and warn
Attempted to solve #3363 This is similar to the behavior now implemented for the `action_dict`. As mentioned in the issue, sounds like these codes are not documented anywhere. In the case of the error encountered, it's not clear what relationship the code has to any text that the end user would see when [viewing the vote in the legislature.](https://www.legislature.ohio.gov/legislation/legislation-votes?id=GA133-HB-425). Decided to fall back to the "passed" value on the vote data because that matches the string found on the leg page ("Passed")

OH: Do not error when an unrecognized vote code is encountered

---

scrapers/mn/vote_events.py

Adds the URL for 2020S1 special session.
However looks like this doesn't fix the current error that is interrupting the scraper run in bobsled: ["openstates.exceptions.ScrapeError: no objects returned from MNVoteScraper scrape"](https://bobsled.openstates.org/run/a49b7fee21124280b48db8a86dcc6f2e)
As a result currently bills in the special session are not being scraped

MN: Add 2020S1 votes URL

---

scrapers/mn/bills.py

Found 7 bills in the new special session where the URL for fetching versions was returning 404 errors, thus no versions were saved for those bills.
SC1
SR 1 through SR 6
Example 404 URL yielded by scraper vs. correct URL: 
https://www.revisor.mn.gov/bin/getbill.php?session_year=2020&session_number=1&number=SC0001&version=list
https://www.revisor.mn.gov/bin/getbill.php?session_year=2020&session_number=1&number=SC1&version=list
Just strips leading zeroes from the numeric part of the bill identifier

MN: Fix 404 error with some bills when leading zeros in bill version url

---

scrapers/nj/bills.py

NJ published some docs with .WPD endings which broke the scraper, this resolves that.

NJ: match mixed case for media type of attachments

---

scrapers/il/bills.py

This PR grabs all the summary elements' text and concatenates it together. Previously, the scraper was only grabbing the first text node.

IL summaries

---

scrapers/ct/bills.py

We were missing some bill versions due to the regex casing, such as on https://www.cga.ct.gov/asp/cgabillstatus/cgabillstatus.asp?selBillType=Bill&bill_num=HB-6001

CT: widen bill version regex

---

scrapers/ny/bills.py

Resolves current NY scraper issue.

NY: return properly on bills without titles

---

scrapers/vt/bills.py

VT scraper failed the last two days on a date string that failed validation. Looks like VT has typos in the dates of actions once in a while. Tried to fix here a little more generally than the previous fix (finding/replacing a specific typo string). Seems better to have a small number of stupid dates on bill actions (the year 200) rather than a scraper that totally stops if one action on one bill doesn't validate.
Interestingly `strftime` formats dates differently on different platforms! so `%Y` doesn't necessarily give you 4 digits back. This might point to a need for a more general error-correction method across scrapers.

VT: Fix invalid date string for bill action

---

scrapers/tx/bills.py

Fix for https://github.com/openstates/issues/issues/100. The versions node was empty in the xml causing the scraper to fail when trying to parse the non-existant versionDescription child node. Updated to bounce out if the versions node is empty.

Issue 100: bounce out of versions if node is empty

---

scrapers/tn/__init__.py
scrapers/tn/bills.py

This PR is a workaround for the TN [special session archive page](http://wapp.capitol.tn.gov/apps/indexes/SPSession1.aspx) 404'ing. The [existing TN index page](http://wapp.capitol.tn.gov/apps/indexes/) contained links to the latest two specials, so this PR also adapts some of the XPath paths and skips some validation to fetch the latest special session data as well.

Port over TN 111S1 and 111S2 workarounds with some extra explanations.

---

scrapers/nv/bills.py

Fixes openstates/issues#103 
Recent NV bill are duplicated.
I think the `bill_list_url` is intended to be a multi-line string, but it's effectively truncated due to missing multi-line string syntax.
This likely led to multiple passes of querying the same bill and resulted in certain NV bills being duplicated.
Use parenthesis to ensure multiple lines of the url's query string
are accounted for.  Use f-string for the entirety of the multi-line string for consistency.
Note: as mentioned in https://github.com/openstates/issues/issues/103#issuecomment-672020483, some manual bill removal may be needed to fix preexisting data.

Fix `bill_list_url` query string in NV bill scrape

---

scrapers/ma/bills.py

Hoping to provide a workaround/mitigation for https://github.com/openstates/issues/issues/107
My goals are:
- have a smaller daily task that would be *very likely* to complete and yield *most* bill data updates (ensure some data is updated frequently)
- could keep the existing full run (maybe less frequently) to *hopefully* yield *all* bill data updates
So in addition to merging this code, y'all would need to add an MA-scrape-lite job that did something like:
```
docker-compose run --rm scrape ma bills sort=latest page_limit=20 --scrape
```
- I can imagine a structure wherein bill scrape yields bills and jobs. In MA, there are several related entities that need to be scraped in association with each bill. Instead of making these additional scrape requests as part of the bill-scrape …

MA: add optional page_limit to allow a limited-latest bill scrape

---

scrapers/de/bills.py

openstates/issues#135
Fixes the new style used by DE legislative site for indicating amendments as (H/S)B### -(H/S)A, saw this id style in a number of new bills for both the house and senate

Fix DE scraper error - openstates/issues#135

---

scrapers/mn/__init__.py

It's not clear they're going to hold this -- so remove it from the scraper.

MN: Ignore 6th special for now

---

scrapers/mn/__init__.py

Looks like MN 6th special session will open today (Thurs): https://www.house.leg.state.mn.us/SessionDaily/Story/15418
Un-ignoring the session.

MN: enable scraping for 2020 6th special session

---

scrapers/de/__init__.py

DE website now shows the 2020-2022 session. I can't tell if DE is still in special session or if it ended a week ago. If it's totally closed, then the scraper probably doesn't need to be fixed by merging this.

DE: added 2020-2022 session to ignored session list for now

---

scrapers/tx/bills.py

Scraper was returning 87R on related bills instead of 87.

TX: Fix session id for 2021 related bills

---

scrapers/nm/bills.py

session_slug method did not expect there to be a second special session
Currently, all NM 2020S2 bill version URLs are wrong - they link to 2020 regular session bills.

NM: Fix special session 2 bill version URLs

---

scrapers/me/__init__.py
scrapers/me/bills.py

Appears that no bills are available yet in session 130, so impossible to verify this is working. However, the bill advanced search interface does not seem to have changed. It does now list session 130:
http://www.mainelegislature.org/LawMakerWeb/advancedsearch.asp

ME: Add 130th session which starts Dec 2

---

scrapers/tx/__init__.py

will need to re-enable in Jan, when (presumably) votes will begin to be available.
Fixes https://github.com/openstates/issues/issues/164

TX: Disable vote scraping so we can ingest prefiled bills

---

.dockerignore
scrapers/mt/bills.py

Start ingesting LCXXXX bills in MT under the proposed bills classification.
https://github.com/openstates/issues/issues/193
One wrinkle in here is that some "unintroduced" bills are attributed to organizations, eg the "Economic Affairs Interim Committee". In that case I omit any sponsor, and arbitrarily assign chamber="lower". Is that horrible?

MT: Ingest proposed bills (LCXXXX) aka unintroduced

---

scrapers/wv/__init__.py

... and add 2021 metadata for when they start posting.

WV: Skip 2021 and 2029 sessions for now

---

scrapers/nh/bills.py

* Some New Hampshire bills are missing version because some GET request to require `x` query string to be set to current time. 
* Also added pdf links for bill version

NH: missing version fix

---

scrapers/mt/bills.py

MT server is now redirecting PDF urls from HTTP to HTTPS (302) so this seems more correct
Don't know if this causes duplicate versions the way that OS logic tries to merge in versions? (eg will it create a new version based on the URL being different?) If that causes a headache we could solve this downstream by parsing OS data.

MT: switch PDF links to HTTPS

---

scrapers/in/bills.py

Some versions on the API are misnamed, so added a sanity check to make sure that the name matches the chamber of the version url and printed name. Should fix for most versions.

IN: Version Name Check

---

scrapers/ok/bills.py

OK was adding 'author not found' as a sponsor if we happened to catch a bill before they finished updating a bill.

OK: skip author not found

---

scrapers/mn/__init__.py

MN 2021 bills are now appearing at https://www.revisor.mn.gov/bills/reference.php
running `docker-compose run --rm scrape mn bills --fastmode --scrape` worked locally for me with this change

MN: enable 2021-2022 session scraping

---

scrapers/in/bills.py

Scraper failed since a typecheck was missed. Should work now.

IN: add typecheck to avoid errors
